#!/usr/bin/env python3
"""Generate local differential FIPS 202 fixtures using Python hashlib.

These are independent expected SHA3/SHAKE outputs for the HLS unit interface.
They are not NIST ACVP vectors, official ML-KEM-1024 KAT, or certification.
The generated header embeds every vector so C/RTL co-simulation needs no
working-directory-dependent file access.  The JSON retains readable evidence.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import platform
import ssl
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TB = ROOT / "tb"
SCOPE = "local differential FIPS 202 unit vectors; not official ML-KEM-1024 KAT"
MODES = ("shake128", "shake256", "sha3_256", "sha3_512")
RATES = (168, 136, 136, 72)


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def patterned_input(label: str, length: int) -> bytes:
    """Reproducible varied bytes, separate from the SHA3/SHAKE oracle."""
    state = int.from_bytes(hashlib.sha256(label.encode("ascii")).digest()[:4], "little") or 1
    result = bytearray()
    for _ in range(length):
        state ^= (state << 13) & 0xFFFFFFFF
        state ^= state >> 17
        state ^= (state << 5) & 0xFFFFFFFF
        state &= 0xFFFFFFFF
        result.append(state & 0xFF)
    return bytes(result)


def expected(mode: int, message: bytes, output_len: int) -> bytes:
    if mode == 0:
        return hashlib.shake_128(message).digest(output_len)
    if mode == 1:
        return hashlib.shake_256(message).digest(output_len)
    answer = (hashlib.sha3_256 if mode == 2 else hashlib.sha3_512)(message).digest()
    assert len(answer) == output_len
    return answer


def make_case(name: str, mode: int, input_len: int, output_len: int,
              message: bytes | None = None) -> dict:
    message = patterned_input(name, input_len) if message is None else message
    assert len(message) == input_len and input_len <= 2048 and output_len <= 4096
    return {
        "name": name,
        "mode": mode,
        "algorithm": MODES[mode],
        "input_len": input_len,
        "output_len": output_len,
        "input_hex": message.hex(),
        "expected_hex": expected(mode, message, output_len).hex(),
    }


def make_fixtures() -> dict:
    hashes = []
    for mode, name in enumerate(MODES):
        rate = RATES[mode]
        fixed_len = 32 if mode == 2 else 64
        default_out = (32 if mode == 0 else 64) if mode < 2 else fixed_len
        hashes.append(make_case(f"{name}_empty", mode, 0, default_out, b""))
        hashes.append(make_case(f"{name}_abc", mode, 3, default_out, b"abc"))
        for length in (rate - 1, rate, rate + 1):
            out = 2 * rate + 13 if mode < 2 else fixed_len
            hashes.append(make_case(f"{name}_in_rate_{length}", mode, length, out))
        hashes.append(make_case(f"{name}_multi_block_input", mode, 2 * rate + 7,
                                2 * rate + 1 if mode < 2 else fixed_len))
        for length in (33, 34, 64, 1568, 1600, 2048):
            out = {33: 128, 34: (504 if mode == 0 else 128), 64: 64,
                   1568: 32, 1600: 32, 2048: 37}[length] if mode < 2 else fixed_len
            hashes.append(make_case(f"{name}_k4_input_{length}", mode, length, out))
        for variant in (0, 1):
            hashes.append(make_case(f"{name}_same_size_data_{variant}", mode, 34,
                                    256 if mode < 2 else fixed_len))
        random_len = (597, 913, 1283, 2011)[mode]
        hashes.append(make_case(f"{name}_deterministic_random", mode, random_len,
                                733 if mode < 2 else fixed_len))
        if mode < 2:
            for length in (0, rate - 1, rate, rate + 1, 2 * rate + 1, 4096):
                hashes.append(make_case(f"{name}_out_boundary_{length}", mode, 34, length))
            hashes.append(make_case(f"{name}_max_input_and_output", mode, 2048, 4096))
    assert len(hashes) == 74
    continuations = [make_case(f"{MODES[mode]}_split_13_0_491_168", mode, 34, 672)
                     for mode in range(2)]
    interleaved = [make_case("shake128_interleaved_A", 0, 33, 337),
                   make_case("shake256_interleaved_B", 1, 34, 273)]
    return {
        "schema_version": 1,
        "scope": SCOPE,
        "oracle": "Python standard-library hashlib SHA3/SHAKE",
        "input_construction": "SHA256(label)-seeded xorshift32, low byte per step; empty/abc literal",
        "hash_cases": hashes,
        "continuation_cases": continuations,
        "interleaved_cases": interleaved,
    }


def c_literal(text: str) -> str:
    if not text:
        return '        ""'
    return "\n".join('        "' + text[i:i + 96] + '"' for i in range(0, len(text), 96))


def header(fixtures: dict) -> bytes:
    lines = ["// Generated by scripts/generate_vectors.py; do not hand-edit.",
             "// Local hashlib differential vectors, NOT official ML-KEM-1024 KAT.",
             "#ifndef MLKEM1024_KECCAK_LOCAL_VECTORS_H",
             "#define MLKEM1024_KECCAK_LOCAL_VECTORS_H", "",
             "struct KeccakLocalVector {",
             "    const char *name;",
             "    unsigned char mode;",
             "    unsigned input_len;",
             "    unsigned output_len;",
             "    const char *input_hex;",
             "    const char *expected_hex;",
             "};", ""]
    for key, c_name in (("hash_cases", "HASH_VECTORS"),
                        ("continuation_cases", "CONTINUATION_VECTORS"),
                        ("interleaved_cases", "INTERLEAVED_VECTORS")):
        lines.append(f"static const KeccakLocalVector {c_name}[] = {{")
        for vector in fixtures[key]:
            lines.append('    {"%s", %d, %d, %d,' % (vector["name"], vector["mode"],
                         vector["input_len"], vector["output_len"]))
            lines.append(c_literal(vector["input_hex"]) + ",")
            lines.append(c_literal(vector["expected_hex"]) + "},")
        lines += ["};", f"static const unsigned {c_name}_COUNT = sizeof({c_name}) / sizeof({c_name}[0]);", ""]
    lines += ["#endif", ""]
    return "\n".join(lines).encode("ascii")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify committed fixtures without rewriting files")
    args = parser.parse_args()
    fixtures = make_fixtures()
    generated = {
        "local_fips202_vectors.json": (json.dumps(fixtures, indent=2) + "\n").encode("ascii"),
        "generated_keccak_vectors.h": header(fixtures),
    }
    manifest_path = TB / "vector_manifest.json"
    if args.check:
        for name, data in generated.items():
            actual = (TB / name).read_bytes()
            if actual != data:
                raise SystemExit(f"Fixture drift: {TB / name}")
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        if manifest["generator_sha256"] != sha256(Path(__file__).read_bytes()):
            raise SystemExit("Generator hash differs from fixture provenance")
        for name, data in generated.items():
            if manifest["fixture_sha256"][name] != sha256(data):
                raise SystemExit(f"Manifest hash mismatch: {name}")
        print("KECCAK_LOCAL_FIXTURES_CHECK_PASS hash_vectors=74 continuation_vectors=2 interleaved_vectors=2")
        return 0
    TB.mkdir(parents=True, exist_ok=True)
    for name, data in generated.items():
        (TB / name).write_bytes(data)
    manifest = {
        "schema_version": 1,
        "scope": SCOPE,
        "python_version": sys.version,
        "python_implementation": platform.python_implementation(),
        "hashlib_sha3_provider_type": type(hashlib.sha3_256()).__module__ + "." + type(hashlib.sha3_256()).__name__,
        "hashlib_shake_provider_type": type(hashlib.shake_128()).__module__ + "." + type(hashlib.shake_128()).__name__,
        "runtime_openssl_version": ssl.OPENSSL_VERSION,
        "generator": "scripts/generate_vectors.py",
        "generator_sha256": sha256(Path(__file__).read_bytes()),
        "fixture_sha256": {name: sha256(data) for name, data in generated.items()},
        "hash_vector_count": len(fixtures["hash_cases"]),
        "continuation_vector_count": len(fixtures["continuation_cases"]),
        "interleaved_vector_count": len(fixtures["interleaved_cases"]),
        "limitations": ["Byte-aligned FIPS 202 unit tests, not bit-oriented input tests.",
                        "No official ML-KEM KAT, CPU integration, board validation or certification claim."],
    }
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8", newline="\n")
    print("KECCAK_LOCAL_FIXTURES_GENERATED hash_vectors=74 continuation_vectors=2 interleaved_vectors=2")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
