`timescale 1ns/1ps

// MMIO and native HLS integration test.  The vectors are generated by
// scripts/mlkem512_basemul_k2/generate_vectors.py and checked through the
// adapter's public bus, so this test exercises packing, control, HLS memory
// timing, result writes, and result readback together.
module tb_mlkem512_basemul_k2_mmio #(
    parameter string VEC_DIR = ".",
    parameter integer CASES = 3
);
    localparam logic [31:0] BASE_ADDR = 32'h5000_1000;
    localparam integer N = 256;
    localparam integer K = 2;
    localparam integer Q = 3329;

    logic clk = 1'b0;
    always #5 clk = ~clk;

    logic resetn = 1'b0;
    logic bus_valid = 1'b0;
    logic bus_write = 1'b0;
    logic [31:0] bus_addr = 32'b0;
    logic [31:0] bus_wdata = 32'b0;
    logic [3:0] bus_wstrb = 4'b0;
    wire bus_ready;
    wire bus_rvalid;
    wire [31:0] bus_rdata;
    wire accel_busy;
    wire accel_done;
    wire accel_error;
    wire [31:0] core_cycles;
    wire [31:0] load_transactions;
    wire [31:0] store_transactions;
    wire [31:0] total_cycles;

    mlkem512_basemul_k2_mmio_adapter #(.BASE_ADDR(BASE_ADDR)) dut (
        .clk(clk), .resetn(resetn),
        .bus_valid(bus_valid), .bus_write(bus_write), .bus_addr(bus_addr),
        .bus_wdata(bus_wdata), .bus_wstrb(bus_wstrb), .bus_ready(bus_ready),
        .bus_rvalid(bus_rvalid), .bus_rdata(bus_rdata),
        .accel_busy(accel_busy), .accel_done(accel_done),
        .accel_error(accel_error), .core_cycles(core_cycles),
        .load_transactions(load_transactions), .store_transactions(store_transactions),
        .total_cycles(total_cycles)
    );

    logic [15:0] a0 [0:255];
    logic [15:0] a1 [0:255];
    logic [15:0] b0 [0:255];
    logic [15:0] b1 [0:255];
    logic [15:0] cache0 [0:127];
    logic [15:0] cache1 [0:127];
    logic [15:0] expected [0:255];
    string vec_dir;
    integer failures = 0;
    integer checks = 0;
    longint first_load, last_load, start_tick, done_tick, first_store, last_store;
    integer job_loads=0, job_stores=0;
    always @(posedge clk) begin
        if (bus_valid && bus_ready) begin
            if (bus_write && bus_addr >= BASE_ADDR && bus_addr < BASE_ADDR+'ha00) begin
                if (job_loads == 0) first_load = ticks;
                last_load = ticks;
                job_loads = job_loads + 1;
            end
            if (bus_write && bus_addr == BASE_ADDR+'h1000 && bus_wdata[0]) start_tick = ticks;
            if (!bus_write && bus_addr >= BASE_ADDR+'ha00 && bus_addr < BASE_ADDR+'hc00) begin
                if (job_stores == 0) first_store = ticks;
                last_store = ticks;
                job_stores = job_stores + 1;
            end
        end
        if (dut.busy && dut.hls_done) done_tick = ticks;
    end

    longint ticks = 0;
    always @(posedge clk) ticks <= ticks + 1;
    task automatic mmio_write_mask(input logic [31:0] offset, input logic [31:0] data, input logic [3:0] mask);
        integer guard;
        begin
            @(negedge clk);
            bus_addr = BASE_ADDR + offset; bus_wdata = data;
            bus_wstrb = mask; bus_write = 1; bus_valid = 1;
            guard = 0;
            @(posedge clk);
            while (!bus_ready) begin
                @(posedge clk); guard++;
                if (guard > 20) $fatal(1,"Write timeout offset=%h",offset);
            end
            @(negedge clk);
            bus_valid = 0; bus_write = 0; bus_wstrb = 0; bus_addr = 0;
        end
    endtask
    task automatic mmio_write(input logic [31:0] offset, input logic [31:0] data);
        mmio_write_mask(offset,data,4'hf);
    endtask
    task automatic mmio_read(input logic [31:0] offset, output logic [31:0] data);
        integer guard;
        begin
            @(negedge clk);
            bus_addr = BASE_ADDR + offset; bus_write = 0; bus_valid = 1;
            bus_wstrb = 0; guard = 0;
            @(posedge clk);
            while (!bus_ready) begin
                @(posedge clk); guard++;
                if (guard > 20) $fatal(1,"Read timeout offset=%h",offset);
            end
            @(negedge clk); bus_valid = 0; bus_addr = 0;
            guard = 0;
            while (!bus_rvalid) begin
                @(negedge clk); guard++;
                if (guard > 20) $fatal(1,"Response timeout offset=%h",offset);
            end
            data = bus_rdata;
        end
    endtask
    initial begin
        #1000000;
        $fatal(1,"Global timeout");
    end

    task automatic load_case(input integer case_index);
        string path;
        integer i;
        logic [31:0] word;
        begin
            path = $sformatf("%s/case_%03d_a0.mem", vec_dir, case_index); $readmemh(path, a0);
            path = $sformatf("%s/case_%03d_a1.mem", vec_dir, case_index); $readmemh(path, a1);
            path = $sformatf("%s/case_%03d_b0.mem", vec_dir, case_index); $readmemh(path, b0);
            path = $sformatf("%s/case_%03d_b1.mem", vec_dir, case_index); $readmemh(path, b1);
            path = $sformatf("%s/case_%03d_cache0.mem", vec_dir, case_index); $readmemh(path, cache0);
            path = $sformatf("%s/case_%03d_cache1.mem", vec_dir, case_index); $readmemh(path, cache1);
            path = $sformatf("%s/case_%03d_expected.mem", vec_dir, case_index); $readmemh(path, expected);

            for (i = 0; i < 128; i = i + 1) begin
                word = {a0[2*i+1], a0[2*i]}; mmio_write(32'h0000 + i*4, word);
                word = {a1[2*i+1], a1[2*i]}; mmio_write(32'h0200 + i*4, word);
                word = {b0[2*i+1], b0[2*i]}; mmio_write(32'h0400 + i*4, word);
                word = {b1[2*i+1], b1[2*i]}; mmio_write(32'h0600 + i*4, word);
            end
            for (i = 0; i < 64; i = i + 1) begin
                word = {cache0[2*i+1], cache0[2*i]}; mmio_write(32'h0800 + i*4, word);
                word = {cache1[2*i+1], cache1[2*i]}; mmio_write(32'h0900 + i*4, word);
            end
        end
    endtask

    task automatic run_case(input integer case_index);
        integer i;
        integer timeout;
        logic [31:0] got;
        logic [31:0] expected_word;
        begin
            job_loads=0; job_stores=0;
            $display("CASE_BEGIN index=%0d",case_index);
            load_case(case_index);
            mmio_write(32'h1000, 32'h0000_0001);
            timeout = 0;
            while (!accel_done) begin
                @(posedge clk);
                timeout = timeout + 1;
                if (timeout > 1000) begin
                    $display("FAIL case=%0d timeout busy=%0d hls_done=%0d hls_idle=%0d hls_ready=%0d start=%0d en0=%0d iter1=%0d i=%0d done_int=%0d", case_index, accel_busy, dut.hls_done, dut.hls_idle, dut.hls_ready, dut.hls_start, dut.hls_core.ap_enable_reg_pp0_iter0, dut.hls_core.ap_enable_reg_pp0_iter1, dut.hls_core.i1_fu_66, dut.hls_core.ap_done_int);
                    failures = failures + 1;
                    disable run_case;
                end
            end
            if (accel_error) begin
                $display("FAIL case=%0d adapter error", case_index);
                failures = failures + 1;
            end
            for (i = 0; i < 128; i = i + 1) begin
                mmio_read(32'h0a00 + i*4, got);
                expected_word = {expected[2*i+1], expected[2*i]};
                checks = checks + 2;
                if (got !== expected_word) begin
                    $display("FAIL case=%0d word=%0d got=%08x expected=%08x", case_index, i, got, expected_word);
                    failures = failures + 1;
                    if (failures > 12) disable run_case;
                end
            end
            if (job_loads != 640 || job_stores != 128) $fatal(1,"Wrong transaction count");
            if (core_cycles != done_tick-start_tick || total_cycles != last_store-first_load+1)
                $fatal(1,"Cycle counter boundaries disagree with bus monitor");
            $display("CASE_PASS index=%0d core_cycles=%0d total_cycles=%0d load_cycles=%0d launch_cycles=%0d drain_to_read=%0d store_cycles=%0d loads=%0d stores=%0d", case_index, core_cycles, total_cycles, last_load-first_load+1, start_tick-last_load, first_store-done_tick-1, last_store-first_store+1, job_loads, job_stores);
        end
    endtask

    task automatic protocol_checks;
        logic [31:0] got, original;
        integer i, timeout;
        begin
            // Each byte lane and input readback, including the RAM mux.
            mmio_read(0,original);
            mmio_write_mask(0,32'h12345678,4'b0101);
            mmio_read(0,got);
            if (got !== {original[31:24],8'h34,original[15:8],8'h78}) $fatal(1,"Byte enables broken");
            mmio_write(0,original);
            mmio_write('h1000,6);
            mmio_read('h1004,got);
            if (got[2:0] !== 0) $fatal(1,"Sticky clear broken");
            mmio_write('h1000,1);
            // Rejected operations may not alter operands or launch another job.
            mmio_write(0,32'hbad0bad0);
            mmio_write('h1000,1);
            mmio_read('ha00,got);
            if (got !== 0) $fatal(1,"Busy result read must be rejected");
            mmio_read('h1004,got);
            if (got[2:0] !== 3'b101) $fatal(1,"Busy/error status broken got=%h",got);
            timeout=0;
            while (!accel_done) begin
                @(negedge clk); timeout++;
                if (timeout>300) $fatal(1,"Repeated job timeout");
            end
            for(i=0;i<128;i++) begin
                mmio_read('ha00+i*4,got);
                if(got !== {expected[2*i+1],expected[2*i]}) $fatal(1,"Rejected access changed result");
            end
            mmio_write('h1000,4);
            mmio_write('ha00,32'hffffffff);
            mmio_read('h1004,got);
            if (!got[2]) $fatal(1,"Read-only result write not rejected");
            mmio_write('h1000,4);
            mmio_read('hc00,got);
            if (got !== 0 || !accel_error) $fatal(1,"Unmapped read not rejected");
            mmio_write('h1000,4);
            mmio_write(1,0);
            if (!accel_error) $fatal(1,"Unaligned write not rejected");
            // Reset must abort a live job without leaving stale start/done.
            mmio_write('h1000,5);
            repeat(10) @(negedge clk);
            resetn=0;
            repeat(4) @(negedge clk);
            resetn=1;
            repeat(2) @(negedge clk);
            if(accel_busy !== 0 || accel_done !== 0 || accel_error !== 0 || dut.hls_start !== 0)
                $fatal(1,"Abort reset broken");
            // BRAM survives reset; running unchanged operands must still work.
            mmio_write('h1000,1);
            timeout=0;
            while(!accel_done) begin
                @(negedge clk); timeout++;
                if(timeout>300) $fatal(1,"Post-reset job timeout");
            end
            for(i=0;i<128;i++) begin
                mmio_read('ha00+i*4,got);
                if(got !== {expected[2*i+1],expected[2*i]}) $fatal(1,"Post-reset result mismatch");
            end
            $display("MMIO_PROTOCOL_PASS byte_enables=1 busy_protection=1 illegal_access=1 repeat=1 reset_abort=1 extra_coefficients=512");
        end
    endtask

    initial begin : test_main
        integer case_index;
        integer plusarg_ok;
        vec_dir = VEC_DIR;
        plusarg_ok = $value$plusargs("VEC_DIR=%s", vec_dir);
        $display("MMIO_TB_START vec_dir=%s", vec_dir);
        repeat (5) @(posedge clk);
        resetn <= 1'b1;
        repeat (3) @(posedge clk);
        for (case_index = 0; case_index < CASES; case_index = case_index + 1)
            run_case(case_index);
        protocol_checks();
        if (checks != 768) $fatal(1,"Missing coefficient checks count=%0d",checks);
        if (failures == 0)
            $display("MLKEM512_BASEMUL_MMIO_RTL_PASS cases=%0d checks=%0d", CASES, checks);
        else
            $display("MLKEM512_BASEMUL_MMIO_RTL_FAIL failures=%0d checks=%0d", failures, checks);
        if (failures != 0) $fatal(1, "RTL MMIO BaseMul test failed");
        $finish;
    end
endmodule
