// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mlkem_poly_mul256_v39e_true_one_dsp_issue39d (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        src_address0,
        src_ce0,
        src_q0,
        src_address1,
        src_ce1,
        src_q1,
        ant_address0,
        ant_ce0,
        ant_q0,
        bnt_address0,
        bnt_ce0,
        bnt_q0,
        bm_in_0_address0,
        bm_in_0_ce0,
        bm_in_0_q0,
        bm_in_4_address0,
        bm_in_4_ce0,
        bm_in_4_q0,
        mode,
        len,
        zparam,
        group_r,
        rq_din,
        rq_full_n,
        rq_write,
        rq_num_data_valid,
        rq_fifo_cap
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
output  [6:0] src_address0;
output   src_ce0;
input  [23:0] src_q0;
output  [6:0] src_address1;
output   src_ce1;
input  [23:0] src_q1;
output  [6:0] ant_address0;
output   ant_ce0;
input  [23:0] ant_q0;
output  [6:0] bnt_address0;
output   bnt_ce0;
input  [23:0] bnt_q0;
output  [5:0] bm_in_0_address0;
output   bm_in_0_ce0;
input  [11:0] bm_in_0_q0;
output  [5:0] bm_in_4_address0;
output   bm_in_4_ce0;
input  [11:0] bm_in_4_q0;
input  [1:0] mode;
input  [7:0] len;
input  [7:0] zparam;
input  [2:0] group_r;
output  [75:0] rq_din;
input   rq_full_n;
output   rq_write;
input  [31:0] rq_num_data_valid;
input  [31:0] rq_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [7:0] zparam_read_reg_198;
reg    ap_block_state1;
reg   [7:0] len_read_reg_203;
reg   [1:0] mode_read_reg_208;
wire   [6:0] empty_fu_133_p1;
reg   [6:0] empty_reg_213;
wire   [1:0] empty_43_fu_138_p1;
reg   [1:0] empty_43_reg_218;
wire   [6:0] empty_44_fu_143_p1;
reg   [6:0] empty_44_reg_223;
wire   [0:0] icmp_ln15_fu_148_p2;
reg   [0:0] icmp_ln15_reg_228;
reg   [6:0] prevlen_i_reg_233;
wire   [0:0] icmp_ln22_fu_166_p2;
reg   [0:0] icmp_ln22_reg_238;
reg   [0:0] tmp_reg_243;
wire   [7:0] add_ln19_fu_182_p2;
reg   [7:0] add_ln19_reg_248;
wire   [8:0] shl_ln_i_fu_189_p3;
reg   [8:0] shl_ln_i_reg_253;
wire    grp_issue39d_Pipeline_issue39d_loop_fu_100_ap_start;
wire    grp_issue39d_Pipeline_issue39d_loop_fu_100_ap_done;
wire    grp_issue39d_Pipeline_issue39d_loop_fu_100_ap_idle;
wire    grp_issue39d_Pipeline_issue39d_loop_fu_100_ap_ready;
wire   [75:0] grp_issue39d_Pipeline_issue39d_loop_fu_100_rq_din;
wire    grp_issue39d_Pipeline_issue39d_loop_fu_100_rq_write;
wire   [6:0] grp_issue39d_Pipeline_issue39d_loop_fu_100_src_address0;
wire    grp_issue39d_Pipeline_issue39d_loop_fu_100_src_ce0;
wire   [6:0] grp_issue39d_Pipeline_issue39d_loop_fu_100_src_address1;
wire    grp_issue39d_Pipeline_issue39d_loop_fu_100_src_ce1;
wire   [6:0] grp_issue39d_Pipeline_issue39d_loop_fu_100_ant_address0;
wire    grp_issue39d_Pipeline_issue39d_loop_fu_100_ant_ce0;
wire   [6:0] grp_issue39d_Pipeline_issue39d_loop_fu_100_bnt_address0;
wire    grp_issue39d_Pipeline_issue39d_loop_fu_100_bnt_ce0;
wire   [5:0] grp_issue39d_Pipeline_issue39d_loop_fu_100_bm_in_0_address0;
wire    grp_issue39d_Pipeline_issue39d_loop_fu_100_bm_in_0_ce0;
wire   [5:0] grp_issue39d_Pipeline_issue39d_loop_fu_100_bm_in_4_address0;
wire    grp_issue39d_Pipeline_issue39d_loop_fu_100_bm_in_4_ce0;
reg    grp_issue39d_Pipeline_issue39d_loop_fu_100_ap_start_reg;
reg    ap_block_state1_ignore_call28;
wire    ap_CS_fsm_state2;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 grp_issue39d_Pipeline_issue39d_loop_fu_100_ap_start_reg = 1'b0;
end

mlkem_poly_mul256_v39e_true_one_dsp_issue39d_Pipeline_issue39d_loop grp_issue39d_Pipeline_issue39d_loop_fu_100(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_issue39d_Pipeline_issue39d_loop_fu_100_ap_start),
    .ap_done(grp_issue39d_Pipeline_issue39d_loop_fu_100_ap_done),
    .ap_idle(grp_issue39d_Pipeline_issue39d_loop_fu_100_ap_idle),
    .ap_ready(grp_issue39d_Pipeline_issue39d_loop_fu_100_ap_ready),
    .rq_din(grp_issue39d_Pipeline_issue39d_loop_fu_100_rq_din),
    .rq_full_n(rq_full_n),
    .rq_write(grp_issue39d_Pipeline_issue39d_loop_fu_100_rq_write),
    .rq_num_data_valid(rq_num_data_valid),
    .rq_fifo_cap(rq_fifo_cap),
    .add_ln19_i(add_ln19_reg_248),
    .prevlen_i(prevlen_i_reg_233),
    .empty_36(mode_read_reg_208),
    .src_address0(grp_issue39d_Pipeline_issue39d_loop_fu_100_src_address0),
    .src_ce0(grp_issue39d_Pipeline_issue39d_loop_fu_100_src_ce0),
    .src_q0(src_q0),
    .src_address1(grp_issue39d_Pipeline_issue39d_loop_fu_100_src_address1),
    .src_ce1(grp_issue39d_Pipeline_issue39d_loop_fu_100_src_ce1),
    .src_q1(src_q1),
    .empty_37(empty_44_reg_223),
    .icmp_ln15_i(icmp_ln15_reg_228),
    .empty_38(empty_reg_213),
    .zext_ln10_i(shl_ln_i_reg_253),
    .icmp_ln22_i(icmp_ln22_reg_238),
    .len_cast11_i_i(len_read_reg_203),
    .ant_address0(grp_issue39d_Pipeline_issue39d_loop_fu_100_ant_address0),
    .ant_ce0(grp_issue39d_Pipeline_issue39d_loop_fu_100_ant_ce0),
    .ant_q0(ant_q0),
    .bnt_address0(grp_issue39d_Pipeline_issue39d_loop_fu_100_bnt_address0),
    .bnt_ce0(grp_issue39d_Pipeline_issue39d_loop_fu_100_bnt_ce0),
    .bnt_q0(bnt_q0),
    .empty_39(empty_43_reg_218),
    .empty_40(tmp_reg_243),
    .bm_in_0_address0(grp_issue39d_Pipeline_issue39d_loop_fu_100_bm_in_0_address0),
    .bm_in_0_ce0(grp_issue39d_Pipeline_issue39d_loop_fu_100_bm_in_0_ce0),
    .bm_in_0_q0(bm_in_0_q0),
    .bm_in_4_address0(grp_issue39d_Pipeline_issue39d_loop_fu_100_bm_in_4_address0),
    .bm_in_4_ce0(grp_issue39d_Pipeline_issue39d_loop_fu_100_bm_in_4_ce0),
    .bm_in_4_q0(bm_in_4_q0),
    .empty(zparam_read_reg_198)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (grp_issue39d_Pipeline_issue39d_loop_fu_100_ap_done == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_issue39d_Pipeline_issue39d_loop_fu_100_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state1_ignore_call28) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_issue39d_Pipeline_issue39d_loop_fu_100_ap_start_reg <= 1'b1;
        end else if ((grp_issue39d_Pipeline_issue39d_loop_fu_100_ap_ready == 1'b1)) begin
            grp_issue39d_Pipeline_issue39d_loop_fu_100_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        add_ln19_reg_248 <= add_ln19_fu_182_p2;
        empty_43_reg_218 <= empty_43_fu_138_p1;
        empty_44_reg_223 <= empty_44_fu_143_p1;
        empty_reg_213 <= empty_fu_133_p1;
        icmp_ln15_reg_228 <= icmp_ln15_fu_148_p2;
        icmp_ln22_reg_238 <= icmp_ln22_fu_166_p2;
        len_read_reg_203 <= len;
        mode_read_reg_208 <= mode;
        prevlen_i_reg_233 <= {{len[7:1]}};
        shl_ln_i_reg_253[8 : 1] <= shl_ln_i_fu_189_p3[8 : 1];
        tmp_reg_243 <= group_r[32'd2];
        zparam_read_reg_198 <= zparam;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_issue39d_Pipeline_issue39d_loop_fu_100_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_issue39d_Pipeline_issue39d_loop_fu_100_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_issue39d_Pipeline_issue39d_loop_fu_100_ap_done == 1'b1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_issue39d_Pipeline_issue39d_loop_fu_100_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln19_fu_182_p2 = ($signed(len) + $signed(8'd255));

assign ant_address0 = grp_issue39d_Pipeline_issue39d_loop_fu_100_ant_address0;

assign ant_ce0 = grp_issue39d_Pipeline_issue39d_loop_fu_100_ant_ce0;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call28 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign bm_in_0_address0 = grp_issue39d_Pipeline_issue39d_loop_fu_100_bm_in_0_address0;

assign bm_in_0_ce0 = grp_issue39d_Pipeline_issue39d_loop_fu_100_bm_in_0_ce0;

assign bm_in_4_address0 = grp_issue39d_Pipeline_issue39d_loop_fu_100_bm_in_4_address0;

assign bm_in_4_ce0 = grp_issue39d_Pipeline_issue39d_loop_fu_100_bm_in_4_ce0;

assign bnt_address0 = grp_issue39d_Pipeline_issue39d_loop_fu_100_bnt_address0;

assign bnt_ce0 = grp_issue39d_Pipeline_issue39d_loop_fu_100_bnt_ce0;

assign empty_43_fu_138_p1 = group_r[1:0];

assign empty_44_fu_143_p1 = len[6:0];

assign empty_fu_133_p1 = zparam[6:0];

assign grp_issue39d_Pipeline_issue39d_loop_fu_100_ap_start = grp_issue39d_Pipeline_issue39d_loop_fu_100_ap_start_reg;

assign icmp_ln15_fu_148_p2 = ((len == 8'd128) ? 1'b1 : 1'b0);

assign icmp_ln22_fu_166_p2 = ((len == 8'd2) ? 1'b1 : 1'b0);

assign rq_din = grp_issue39d_Pipeline_issue39d_loop_fu_100_rq_din;

assign rq_write = grp_issue39d_Pipeline_issue39d_loop_fu_100_rq_write;

assign shl_ln_i_fu_189_p3 = {{len}, {1'd0}};

assign src_address0 = grp_issue39d_Pipeline_issue39d_loop_fu_100_src_address0;

assign src_address1 = grp_issue39d_Pipeline_issue39d_loop_fu_100_src_address1;

assign src_ce0 = grp_issue39d_Pipeline_issue39d_loop_fu_100_src_ce0;

assign src_ce1 = grp_issue39d_Pipeline_issue39d_loop_fu_100_src_ce1;

assign start_out = real_start;

always @ (posedge ap_clk) begin
    shl_ln_i_reg_253[0] <= 1'b0;
end

endmodule //mlkem_poly_mul256_v39e_true_one_dsp_issue39d
