// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mlkem_poly_mul256_v39e_true_one_dsp_batch39d (
        src_address0,
        src_ce0,
        src_d0,
        src_q0,
        src_we0,
        src_address1,
        src_ce1,
        src_d1,
        src_q1,
        src_we1,
        dst_address0,
        dst_ce0,
        dst_d0,
        dst_q0,
        dst_we0,
        dst_address1,
        dst_ce1,
        dst_d1,
        dst_q1,
        dst_we1,
        ant_address0,
        ant_ce0,
        ant_d0,
        ant_q0,
        ant_we0,
        ant_address1,
        ant_ce1,
        ant_d1,
        ant_q1,
        ant_we1,
        bnt_address0,
        bnt_ce0,
        bnt_d0,
        bnt_q0,
        bnt_we0,
        bnt_address1,
        bnt_ce1,
        bnt_d1,
        bnt_q1,
        bnt_we1,
        bm_in_0_address0,
        bm_in_0_ce0,
        bm_in_0_d0,
        bm_in_0_q0,
        bm_in_0_we0,
        bm_in_4_address0,
        bm_in_4_ce0,
        bm_in_4_d0,
        bm_in_4_q0,
        bm_in_4_we0,
        bm_out_0_address0,
        bm_out_0_ce0,
        bm_out_0_d0,
        bm_out_0_q0,
        bm_out_0_we0,
        bm_out_1_address0,
        bm_out_1_ce0,
        bm_out_1_d0,
        bm_out_1_q0,
        bm_out_1_we0,
        bm_out_2_address0,
        bm_out_2_ce0,
        bm_out_2_d0,
        bm_out_2_q0,
        bm_out_2_we0,
        bm_out_3_address0,
        bm_out_3_ce0,
        bm_out_3_d0,
        bm_out_3_q0,
        bm_out_3_we0,
        bm_out_4_address0,
        bm_out_4_ce0,
        bm_out_4_d0,
        bm_out_4_q0,
        bm_out_4_we0,
        bm_out_5_address0,
        bm_out_5_ce0,
        bm_out_5_d0,
        bm_out_5_q0,
        bm_out_5_we0,
        bm_out_6_address0,
        bm_out_6_ce0,
        bm_out_6_d0,
        bm_out_6_q0,
        bm_out_6_we0,
        bm_out_7_address0,
        bm_out_7_ce0,
        bm_out_7_d0,
        bm_out_7_q0,
        bm_out_7_we0,
        bm_final_0_address0,
        bm_final_0_ce0,
        bm_final_0_d0,
        bm_final_0_q0,
        bm_final_0_we0,
        bm_final_1_address0,
        bm_final_1_ce0,
        bm_final_1_d0,
        bm_final_1_q0,
        bm_final_1_we0,
        output_r_address0,
        output_r_ce0,
        output_r_d0,
        output_r_q0,
        output_r_we0,
        output_r_address1,
        output_r_ce1,
        output_r_d1,
        output_r_q1,
        output_r_we1,
        mode,
        len,
        zparam,
        group_r,
        ap_clk,
        ap_rst,
        mode_ap_vld,
        len_ap_vld,
        zparam_ap_vld,
        group_r_ap_vld,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


output  [6:0] src_address0;
output   src_ce0;
output  [23:0] src_d0;
input  [23:0] src_q0;
output   src_we0;
output  [6:0] src_address1;
output   src_ce1;
output  [23:0] src_d1;
input  [23:0] src_q1;
output   src_we1;
output  [6:0] dst_address0;
output   dst_ce0;
output  [23:0] dst_d0;
input  [23:0] dst_q0;
output   dst_we0;
output  [6:0] dst_address1;
output   dst_ce1;
output  [23:0] dst_d1;
input  [23:0] dst_q1;
output   dst_we1;
output  [6:0] ant_address0;
output   ant_ce0;
output  [23:0] ant_d0;
input  [23:0] ant_q0;
output   ant_we0;
output  [6:0] ant_address1;
output   ant_ce1;
output  [23:0] ant_d1;
input  [23:0] ant_q1;
output   ant_we1;
output  [6:0] bnt_address0;
output   bnt_ce0;
output  [23:0] bnt_d0;
input  [23:0] bnt_q0;
output   bnt_we0;
output  [6:0] bnt_address1;
output   bnt_ce1;
output  [23:0] bnt_d1;
input  [23:0] bnt_q1;
output   bnt_we1;
output  [5:0] bm_in_0_address0;
output   bm_in_0_ce0;
output  [11:0] bm_in_0_d0;
input  [11:0] bm_in_0_q0;
output   bm_in_0_we0;
output  [5:0] bm_in_4_address0;
output   bm_in_4_ce0;
output  [11:0] bm_in_4_d0;
input  [11:0] bm_in_4_q0;
output   bm_in_4_we0;
output  [5:0] bm_out_0_address0;
output   bm_out_0_ce0;
output  [11:0] bm_out_0_d0;
input  [11:0] bm_out_0_q0;
output   bm_out_0_we0;
output  [5:0] bm_out_1_address0;
output   bm_out_1_ce0;
output  [11:0] bm_out_1_d0;
input  [11:0] bm_out_1_q0;
output   bm_out_1_we0;
output  [5:0] bm_out_2_address0;
output   bm_out_2_ce0;
output  [11:0] bm_out_2_d0;
input  [11:0] bm_out_2_q0;
output   bm_out_2_we0;
output  [5:0] bm_out_3_address0;
output   bm_out_3_ce0;
output  [11:0] bm_out_3_d0;
input  [11:0] bm_out_3_q0;
output   bm_out_3_we0;
output  [5:0] bm_out_4_address0;
output   bm_out_4_ce0;
output  [11:0] bm_out_4_d0;
input  [11:0] bm_out_4_q0;
output   bm_out_4_we0;
output  [5:0] bm_out_5_address0;
output   bm_out_5_ce0;
output  [11:0] bm_out_5_d0;
input  [11:0] bm_out_5_q0;
output   bm_out_5_we0;
output  [5:0] bm_out_6_address0;
output   bm_out_6_ce0;
output  [11:0] bm_out_6_d0;
input  [11:0] bm_out_6_q0;
output   bm_out_6_we0;
output  [5:0] bm_out_7_address0;
output   bm_out_7_ce0;
output  [11:0] bm_out_7_d0;
input  [11:0] bm_out_7_q0;
output   bm_out_7_we0;
output  [5:0] bm_final_0_address0;
output   bm_final_0_ce0;
output  [11:0] bm_final_0_d0;
input  [11:0] bm_final_0_q0;
output   bm_final_0_we0;
output  [5:0] bm_final_1_address0;
output   bm_final_1_ce0;
output  [11:0] bm_final_1_d0;
input  [11:0] bm_final_1_q0;
output   bm_final_1_we0;
output  [7:0] output_r_address0;
output   output_r_ce0;
output  [15:0] output_r_d0;
input  [15:0] output_r_q0;
output   output_r_we0;
output  [7:0] output_r_address1;
output   output_r_ce1;
output  [15:0] output_r_d1;
input  [15:0] output_r_q1;
output   output_r_we1;
input  [31:0] mode;
input  [31:0] len;
input  [31:0] zparam;
input  [31:0] group_r;
input   ap_clk;
input   ap_rst;
input   mode_ap_vld;
input   len_ap_vld;
input   zparam_ap_vld;
input   group_r_ap_vld;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    issue39d_U0_ap_start;
wire    issue39d_U0_ap_done;
wire    issue39d_U0_ap_continue;
wire    issue39d_U0_ap_idle;
wire    issue39d_U0_ap_ready;
wire    issue39d_U0_start_out;
wire    issue39d_U0_start_write;
wire   [6:0] issue39d_U0_src_address0;
wire    issue39d_U0_src_ce0;
wire   [6:0] issue39d_U0_src_address1;
wire    issue39d_U0_src_ce1;
wire   [6:0] issue39d_U0_ant_address0;
wire    issue39d_U0_ant_ce0;
wire   [6:0] issue39d_U0_bnt_address0;
wire    issue39d_U0_bnt_ce0;
wire   [5:0] issue39d_U0_bm_in_0_address0;
wire    issue39d_U0_bm_in_0_ce0;
wire   [5:0] issue39d_U0_bm_in_4_address0;
wire    issue39d_U0_bm_in_4_ce0;
wire   [1:0] issue39d_U0_mode;
wire   [7:0] issue39d_U0_len;
wire   [7:0] issue39d_U0_zparam;
wire   [2:0] issue39d_U0_group_r;
wire   [75:0] issue39d_U0_rq_din;
wire    issue39d_U0_rq_write;
wire   [31:0] issue39d_U0_rq_num_data_valid;
wire   [31:0] issue39d_U0_rq_fifo_cap;
wire    pe39c_U0_ap_start;
wire    pe39c_U0_ap_done;
wire    pe39c_U0_ap_continue;
wire    pe39c_U0_ap_idle;
wire    pe39c_U0_ap_ready;
wire    pe39c_U0_rq_read;
wire   [38:0] pe39c_U0_rs_din;
wire    pe39c_U0_rs_write;
wire   [31:0] pe39c_U0_rs_num_data_valid;
wire   [31:0] pe39c_U0_rs_fifo_cap;
wire    pe39c_U0_start_out;
wire    pe39c_U0_start_write;
wire    write39d_U0_ap_start;
wire    write39d_U0_ap_done;
wire    write39d_U0_ap_continue;
wire    write39d_U0_ap_idle;
wire    write39d_U0_ap_ready;
wire    write39d_U0_rs_read;
wire   [6:0] write39d_U0_dst_address0;
wire    write39d_U0_dst_ce0;
wire    write39d_U0_dst_we0;
wire   [23:0] write39d_U0_dst_d0;
wire   [5:0] write39d_U0_bm_out_0_address0;
wire    write39d_U0_bm_out_0_ce0;
wire    write39d_U0_bm_out_0_we0;
wire   [11:0] write39d_U0_bm_out_0_d0;
wire   [5:0] write39d_U0_bm_out_1_address0;
wire    write39d_U0_bm_out_1_ce0;
wire    write39d_U0_bm_out_1_we0;
wire   [11:0] write39d_U0_bm_out_1_d0;
wire   [5:0] write39d_U0_bm_out_2_address0;
wire    write39d_U0_bm_out_2_ce0;
wire    write39d_U0_bm_out_2_we0;
wire   [11:0] write39d_U0_bm_out_2_d0;
wire   [5:0] write39d_U0_bm_out_3_address0;
wire    write39d_U0_bm_out_3_ce0;
wire    write39d_U0_bm_out_3_we0;
wire   [11:0] write39d_U0_bm_out_3_d0;
wire   [5:0] write39d_U0_bm_out_4_address0;
wire    write39d_U0_bm_out_4_ce0;
wire    write39d_U0_bm_out_4_we0;
wire   [11:0] write39d_U0_bm_out_4_d0;
wire   [5:0] write39d_U0_bm_out_5_address0;
wire    write39d_U0_bm_out_5_ce0;
wire    write39d_U0_bm_out_5_we0;
wire   [11:0] write39d_U0_bm_out_5_d0;
wire   [5:0] write39d_U0_bm_out_6_address0;
wire    write39d_U0_bm_out_6_ce0;
wire    write39d_U0_bm_out_6_we0;
wire   [11:0] write39d_U0_bm_out_6_d0;
wire   [5:0] write39d_U0_bm_out_7_address0;
wire    write39d_U0_bm_out_7_ce0;
wire    write39d_U0_bm_out_7_we0;
wire   [11:0] write39d_U0_bm_out_7_d0;
wire   [5:0] write39d_U0_bm_final_0_address0;
wire    write39d_U0_bm_final_0_ce0;
wire    write39d_U0_bm_final_0_we0;
wire   [11:0] write39d_U0_bm_final_0_d0;
wire   [5:0] write39d_U0_bm_final_1_address0;
wire    write39d_U0_bm_final_1_ce0;
wire    write39d_U0_bm_final_1_we0;
wire   [11:0] write39d_U0_bm_final_1_d0;
wire   [7:0] write39d_U0_output_r_address0;
wire    write39d_U0_output_r_ce0;
wire    write39d_U0_output_r_we0;
wire   [15:0] write39d_U0_output_r_d0;
wire   [2:0] write39d_U0_group_r;
wire    rq_full_n;
wire   [75:0] rq_dout;
wire    rq_empty_n;
wire   [2:0] rq_num_data_valid;
wire   [2:0] rq_fifo_cap;
wire    rs_full_n;
wire   [38:0] rs_dout;
wire    rs_empty_n;
wire   [2:0] rs_num_data_valid;
wire   [2:0] rs_fifo_cap;
wire   [0:0] start_for_pe39c_U0_din;
wire    start_for_pe39c_U0_full_n;
wire   [0:0] start_for_pe39c_U0_dout;
wire    start_for_pe39c_U0_empty_n;
wire   [0:0] start_for_write39d_U0_din;
wire    start_for_write39d_U0_full_n;
wire   [0:0] start_for_write39d_U0_dout;
wire    start_for_write39d_U0_empty_n;

mlkem_poly_mul256_v39e_true_one_dsp_issue39d issue39d_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(issue39d_U0_ap_start),
    .start_full_n(start_for_pe39c_U0_full_n),
    .ap_done(issue39d_U0_ap_done),
    .ap_continue(issue39d_U0_ap_continue),
    .ap_idle(issue39d_U0_ap_idle),
    .ap_ready(issue39d_U0_ap_ready),
    .start_out(issue39d_U0_start_out),
    .start_write(issue39d_U0_start_write),
    .src_address0(issue39d_U0_src_address0),
    .src_ce0(issue39d_U0_src_ce0),
    .src_q0(src_q0),
    .src_address1(issue39d_U0_src_address1),
    .src_ce1(issue39d_U0_src_ce1),
    .src_q1(src_q1),
    .ant_address0(issue39d_U0_ant_address0),
    .ant_ce0(issue39d_U0_ant_ce0),
    .ant_q0(ant_q0),
    .bnt_address0(issue39d_U0_bnt_address0),
    .bnt_ce0(issue39d_U0_bnt_ce0),
    .bnt_q0(bnt_q0),
    .bm_in_0_address0(issue39d_U0_bm_in_0_address0),
    .bm_in_0_ce0(issue39d_U0_bm_in_0_ce0),
    .bm_in_0_q0(bm_in_0_q0),
    .bm_in_4_address0(issue39d_U0_bm_in_4_address0),
    .bm_in_4_ce0(issue39d_U0_bm_in_4_ce0),
    .bm_in_4_q0(bm_in_4_q0),
    .mode(issue39d_U0_mode),
    .len(issue39d_U0_len),
    .zparam(issue39d_U0_zparam),
    .group_r(issue39d_U0_group_r),
    .rq_din(issue39d_U0_rq_din),
    .rq_full_n(rq_full_n),
    .rq_write(issue39d_U0_rq_write),
    .rq_num_data_valid(issue39d_U0_rq_num_data_valid),
    .rq_fifo_cap(issue39d_U0_rq_fifo_cap)
);

mlkem_poly_mul256_v39e_true_one_dsp_pe39c pe39c_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(pe39c_U0_ap_start),
    .start_full_n(start_for_write39d_U0_full_n),
    .ap_done(pe39c_U0_ap_done),
    .ap_continue(pe39c_U0_ap_continue),
    .ap_idle(pe39c_U0_ap_idle),
    .ap_ready(pe39c_U0_ap_ready),
    .rq_dout(rq_dout),
    .rq_empty_n(rq_empty_n),
    .rq_read(pe39c_U0_rq_read),
    .rq_num_data_valid(rq_num_data_valid),
    .rq_fifo_cap(rq_fifo_cap),
    .rs_din(pe39c_U0_rs_din),
    .rs_full_n(rs_full_n),
    .rs_write(pe39c_U0_rs_write),
    .rs_num_data_valid(pe39c_U0_rs_num_data_valid),
    .rs_fifo_cap(pe39c_U0_rs_fifo_cap),
    .start_out(pe39c_U0_start_out),
    .start_write(pe39c_U0_start_write)
);

mlkem_poly_mul256_v39e_true_one_dsp_write39d write39d_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(write39d_U0_ap_start),
    .ap_done(write39d_U0_ap_done),
    .ap_continue(write39d_U0_ap_continue),
    .ap_idle(write39d_U0_ap_idle),
    .ap_ready(write39d_U0_ap_ready),
    .rs_dout(rs_dout),
    .rs_empty_n(rs_empty_n),
    .rs_read(write39d_U0_rs_read),
    .rs_num_data_valid(rs_num_data_valid),
    .rs_fifo_cap(rs_fifo_cap),
    .dst_address0(write39d_U0_dst_address0),
    .dst_ce0(write39d_U0_dst_ce0),
    .dst_we0(write39d_U0_dst_we0),
    .dst_d0(write39d_U0_dst_d0),
    .bm_out_0_address0(write39d_U0_bm_out_0_address0),
    .bm_out_0_ce0(write39d_U0_bm_out_0_ce0),
    .bm_out_0_we0(write39d_U0_bm_out_0_we0),
    .bm_out_0_d0(write39d_U0_bm_out_0_d0),
    .bm_out_1_address0(write39d_U0_bm_out_1_address0),
    .bm_out_1_ce0(write39d_U0_bm_out_1_ce0),
    .bm_out_1_we0(write39d_U0_bm_out_1_we0),
    .bm_out_1_d0(write39d_U0_bm_out_1_d0),
    .bm_out_2_address0(write39d_U0_bm_out_2_address0),
    .bm_out_2_ce0(write39d_U0_bm_out_2_ce0),
    .bm_out_2_we0(write39d_U0_bm_out_2_we0),
    .bm_out_2_d0(write39d_U0_bm_out_2_d0),
    .bm_out_3_address0(write39d_U0_bm_out_3_address0),
    .bm_out_3_ce0(write39d_U0_bm_out_3_ce0),
    .bm_out_3_we0(write39d_U0_bm_out_3_we0),
    .bm_out_3_d0(write39d_U0_bm_out_3_d0),
    .bm_out_4_address0(write39d_U0_bm_out_4_address0),
    .bm_out_4_ce0(write39d_U0_bm_out_4_ce0),
    .bm_out_4_we0(write39d_U0_bm_out_4_we0),
    .bm_out_4_d0(write39d_U0_bm_out_4_d0),
    .bm_out_5_address0(write39d_U0_bm_out_5_address0),
    .bm_out_5_ce0(write39d_U0_bm_out_5_ce0),
    .bm_out_5_we0(write39d_U0_bm_out_5_we0),
    .bm_out_5_d0(write39d_U0_bm_out_5_d0),
    .bm_out_6_address0(write39d_U0_bm_out_6_address0),
    .bm_out_6_ce0(write39d_U0_bm_out_6_ce0),
    .bm_out_6_we0(write39d_U0_bm_out_6_we0),
    .bm_out_6_d0(write39d_U0_bm_out_6_d0),
    .bm_out_7_address0(write39d_U0_bm_out_7_address0),
    .bm_out_7_ce0(write39d_U0_bm_out_7_ce0),
    .bm_out_7_we0(write39d_U0_bm_out_7_we0),
    .bm_out_7_d0(write39d_U0_bm_out_7_d0),
    .bm_final_0_address0(write39d_U0_bm_final_0_address0),
    .bm_final_0_ce0(write39d_U0_bm_final_0_ce0),
    .bm_final_0_we0(write39d_U0_bm_final_0_we0),
    .bm_final_0_d0(write39d_U0_bm_final_0_d0),
    .bm_final_1_address0(write39d_U0_bm_final_1_address0),
    .bm_final_1_ce0(write39d_U0_bm_final_1_ce0),
    .bm_final_1_we0(write39d_U0_bm_final_1_we0),
    .bm_final_1_d0(write39d_U0_bm_final_1_d0),
    .output_r_address0(write39d_U0_output_r_address0),
    .output_r_ce0(write39d_U0_output_r_ce0),
    .output_r_we0(write39d_U0_output_r_we0),
    .output_r_d0(write39d_U0_output_r_d0),
    .group_r(write39d_U0_group_r)
);

mlkem_poly_mul256_v39e_true_one_dsp_fifo_w76_d2_S rq_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(issue39d_U0_rq_din),
    .if_full_n(rq_full_n),
    .if_write(issue39d_U0_rq_write),
    .if_dout(rq_dout),
    .if_empty_n(rq_empty_n),
    .if_read(pe39c_U0_rq_read),
    .if_num_data_valid(rq_num_data_valid),
    .if_fifo_cap(rq_fifo_cap)
);

mlkem_poly_mul256_v39e_true_one_dsp_fifo_w39_d2_S rs_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pe39c_U0_rs_din),
    .if_full_n(rs_full_n),
    .if_write(pe39c_U0_rs_write),
    .if_dout(rs_dout),
    .if_empty_n(rs_empty_n),
    .if_read(write39d_U0_rs_read),
    .if_num_data_valid(rs_num_data_valid),
    .if_fifo_cap(rs_fifo_cap)
);

mlkem_poly_mul256_v39e_true_one_dsp_start_for_pe39c_U0 start_for_pe39c_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pe39c_U0_din),
    .if_full_n(start_for_pe39c_U0_full_n),
    .if_write(issue39d_U0_start_write),
    .if_dout(start_for_pe39c_U0_dout),
    .if_empty_n(start_for_pe39c_U0_empty_n),
    .if_read(pe39c_U0_ap_ready)
);

mlkem_poly_mul256_v39e_true_one_dsp_start_for_write39d_U0 start_for_write39d_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_write39d_U0_din),
    .if_full_n(start_for_write39d_U0_full_n),
    .if_write(pe39c_U0_start_write),
    .if_dout(start_for_write39d_U0_dout),
    .if_empty_n(start_for_write39d_U0_empty_n),
    .if_read(write39d_U0_ap_ready)
);

assign ant_address0 = issue39d_U0_ant_address0;

assign ant_address1 = 7'd0;

assign ant_ce0 = issue39d_U0_ant_ce0;

assign ant_ce1 = 1'b0;

assign ant_d0 = 24'd0;

assign ant_d1 = 24'd0;

assign ant_we0 = 1'b0;

assign ant_we1 = 1'b0;

assign ap_done = write39d_U0_ap_done;

assign ap_idle = (write39d_U0_ap_idle & pe39c_U0_ap_idle & issue39d_U0_ap_idle);

assign ap_ready = issue39d_U0_ap_ready;

assign bm_final_0_address0 = write39d_U0_bm_final_0_address0;

assign bm_final_0_ce0 = write39d_U0_bm_final_0_ce0;

assign bm_final_0_d0 = write39d_U0_bm_final_0_d0;

assign bm_final_0_we0 = write39d_U0_bm_final_0_we0;

assign bm_final_1_address0 = write39d_U0_bm_final_1_address0;

assign bm_final_1_ce0 = write39d_U0_bm_final_1_ce0;

assign bm_final_1_d0 = write39d_U0_bm_final_1_d0;

assign bm_final_1_we0 = write39d_U0_bm_final_1_we0;

assign bm_in_0_address0 = issue39d_U0_bm_in_0_address0;

assign bm_in_0_ce0 = issue39d_U0_bm_in_0_ce0;

assign bm_in_0_d0 = 12'd0;

assign bm_in_0_we0 = 1'b0;

assign bm_in_4_address0 = issue39d_U0_bm_in_4_address0;

assign bm_in_4_ce0 = issue39d_U0_bm_in_4_ce0;

assign bm_in_4_d0 = 12'd0;

assign bm_in_4_we0 = 1'b0;

assign bm_out_0_address0 = write39d_U0_bm_out_0_address0;

assign bm_out_0_ce0 = write39d_U0_bm_out_0_ce0;

assign bm_out_0_d0 = write39d_U0_bm_out_0_d0;

assign bm_out_0_we0 = write39d_U0_bm_out_0_we0;

assign bm_out_1_address0 = write39d_U0_bm_out_1_address0;

assign bm_out_1_ce0 = write39d_U0_bm_out_1_ce0;

assign bm_out_1_d0 = write39d_U0_bm_out_1_d0;

assign bm_out_1_we0 = write39d_U0_bm_out_1_we0;

assign bm_out_2_address0 = write39d_U0_bm_out_2_address0;

assign bm_out_2_ce0 = write39d_U0_bm_out_2_ce0;

assign bm_out_2_d0 = write39d_U0_bm_out_2_d0;

assign bm_out_2_we0 = write39d_U0_bm_out_2_we0;

assign bm_out_3_address0 = write39d_U0_bm_out_3_address0;

assign bm_out_3_ce0 = write39d_U0_bm_out_3_ce0;

assign bm_out_3_d0 = write39d_U0_bm_out_3_d0;

assign bm_out_3_we0 = write39d_U0_bm_out_3_we0;

assign bm_out_4_address0 = write39d_U0_bm_out_4_address0;

assign bm_out_4_ce0 = write39d_U0_bm_out_4_ce0;

assign bm_out_4_d0 = write39d_U0_bm_out_4_d0;

assign bm_out_4_we0 = write39d_U0_bm_out_4_we0;

assign bm_out_5_address0 = write39d_U0_bm_out_5_address0;

assign bm_out_5_ce0 = write39d_U0_bm_out_5_ce0;

assign bm_out_5_d0 = write39d_U0_bm_out_5_d0;

assign bm_out_5_we0 = write39d_U0_bm_out_5_we0;

assign bm_out_6_address0 = write39d_U0_bm_out_6_address0;

assign bm_out_6_ce0 = write39d_U0_bm_out_6_ce0;

assign bm_out_6_d0 = write39d_U0_bm_out_6_d0;

assign bm_out_6_we0 = write39d_U0_bm_out_6_we0;

assign bm_out_7_address0 = write39d_U0_bm_out_7_address0;

assign bm_out_7_ce0 = write39d_U0_bm_out_7_ce0;

assign bm_out_7_d0 = write39d_U0_bm_out_7_d0;

assign bm_out_7_we0 = write39d_U0_bm_out_7_we0;

assign bnt_address0 = issue39d_U0_bnt_address0;

assign bnt_address1 = 7'd0;

assign bnt_ce0 = issue39d_U0_bnt_ce0;

assign bnt_ce1 = 1'b0;

assign bnt_d0 = 24'd0;

assign bnt_d1 = 24'd0;

assign bnt_we0 = 1'b0;

assign bnt_we1 = 1'b0;

assign dst_address0 = write39d_U0_dst_address0;

assign dst_address1 = 7'd0;

assign dst_ce0 = write39d_U0_dst_ce0;

assign dst_ce1 = 1'b0;

assign dst_d0 = write39d_U0_dst_d0;

assign dst_d1 = 24'd0;

assign dst_we0 = write39d_U0_dst_we0;

assign dst_we1 = 1'b0;

assign issue39d_U0_ap_continue = 1'b1;

assign issue39d_U0_ap_start = ap_start;

assign issue39d_U0_group_r = {{group_r[(3 - 32'd1):0]}};

assign issue39d_U0_len = {{len[(8 - 32'd1):0]}};

assign issue39d_U0_mode = {{mode[(2 - 32'd1):0]}};

assign issue39d_U0_rq_fifo_cap = rq_fifo_cap;

assign issue39d_U0_rq_num_data_valid = rq_num_data_valid;

assign issue39d_U0_zparam = {{zparam[(8 - 32'd1):0]}};

assign output_r_address0 = write39d_U0_output_r_address0;

assign output_r_address1 = 8'd0;

assign output_r_ce0 = write39d_U0_output_r_ce0;

assign output_r_ce1 = 1'b0;

assign output_r_d0 = write39d_U0_output_r_d0;

assign output_r_d1 = 16'd0;

assign output_r_we0 = write39d_U0_output_r_we0;

assign output_r_we1 = 1'b0;

assign pe39c_U0_ap_continue = 1'b1;

assign pe39c_U0_ap_start = start_for_pe39c_U0_empty_n;

assign pe39c_U0_rs_fifo_cap = rs_fifo_cap;

assign pe39c_U0_rs_num_data_valid = rs_num_data_valid;

assign src_address0 = issue39d_U0_src_address0;

assign src_address1 = issue39d_U0_src_address1;

assign src_ce0 = issue39d_U0_src_ce0;

assign src_ce1 = issue39d_U0_src_ce1;

assign src_d0 = 24'd0;

assign src_d1 = 24'd0;

assign src_we0 = 1'b0;

assign src_we1 = 1'b0;

assign start_for_pe39c_U0_din = 1'b1;

assign start_for_write39d_U0_din = 1'b1;

assign write39d_U0_ap_continue = ap_continue;

assign write39d_U0_ap_start = start_for_write39d_U0_empty_n;

assign write39d_U0_group_r = {{group_r[(3 - 32'd1):0]}};

endmodule //mlkem_poly_mul256_v39e_true_one_dsp_batch39d
