// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mlkem_poly_mul256_v39e_true_one_dsp_issue39d_Pipeline_issue39d_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        rq_din,
        rq_full_n,
        rq_write,
        rq_num_data_valid,
        rq_fifo_cap,
        add_ln19_i,
        prevlen_i,
        empty_36,
        src_address0,
        src_ce0,
        src_q0,
        src_address1,
        src_ce1,
        src_q1,
        empty_37,
        icmp_ln15_i,
        empty_38,
        zext_ln10_i,
        icmp_ln22_i,
        len_cast11_i_i,
        ant_address0,
        ant_ce0,
        ant_q0,
        bnt_address0,
        bnt_ce0,
        bnt_q0,
        empty_39,
        empty_40,
        bm_in_0_address0,
        bm_in_0_ce0,
        bm_in_0_q0,
        bm_in_4_address0,
        bm_in_4_ce0,
        bm_in_4_q0,
        empty
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [75:0] rq_din;
input   rq_full_n;
output   rq_write;
input  [31:0] rq_num_data_valid;
input  [31:0] rq_fifo_cap;
input  [7:0] add_ln19_i;
input  [6:0] prevlen_i;
input  [1:0] empty_36;
output  [6:0] src_address0;
output   src_ce0;
input  [23:0] src_q0;
output  [6:0] src_address1;
output   src_ce1;
input  [23:0] src_q1;
input  [6:0] empty_37;
input  [0:0] icmp_ln15_i;
input  [6:0] empty_38;
input  [8:0] zext_ln10_i;
input  [0:0] icmp_ln22_i;
input  [7:0] len_cast11_i_i;
output  [6:0] ant_address0;
output   ant_ce0;
input  [23:0] ant_q0;
output  [6:0] bnt_address0;
output   bnt_ce0;
input  [23:0] bnt_q0;
input  [1:0] empty_39;
input  [0:0] empty_40;
output  [5:0] bm_in_0_address0;
output   bm_in_0_ce0;
input  [11:0] bm_in_0_q0;
output  [5:0] bm_in_4_address0;
output   bm_in_4_ce0;
input  [11:0] bm_in_4_q0;
input  [7:0] empty;

reg ap_idle;
reg rq_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
reg    ap_block_state6_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln10_fu_753_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [11:0] zetas39c_q0;
wire   [6:0] zetas39c_address1;
wire   [11:0] zetas39c_q1;
reg    rq_blk_n;
wire    ap_block_pp0_stage0;
reg   [1:0] r_tag_3_i_i_reg_473;
reg   [2:0] r_tag_3_ph_i_i_reg_483;
wire   [11:0] grp_fu_695_p3;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln10_reg_1664;
reg   [0:0] icmp_ln10_reg_1664_pp0_iter3_reg;
reg   [1:0] tmp_10_reg_1625;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg   [7:0] tmp_reg_1587;
reg   [0:0] tmp_6_reg_1592;
reg   [1:0] tmp_7_reg_1596;
reg   [0:0] icmp_ln22_i_read_reg_1601;
reg   [6:0] tmp_8_reg_1607;
reg   [0:0] icmp_ln15_i_read_reg_1613;
reg   [6:0] tmp_9_reg_1619;
reg   [6:0] prevlen_i_read_reg_1631;
wire   [31:0] len_cast11_i_i_cast_fu_709_p1;
reg   [31:0] len_cast11_i_i_cast_reg_1637;
wire   [31:0] zext_ln10_i_cast_fu_713_p1;
reg   [31:0] zext_ln10_i_cast_reg_1642;
wire  signed [31:0] sext_ln19_fu_717_p1;
reg  signed [31:0] sext_ln19_reg_1647;
wire   [31:0] zext_ln21_fu_721_p1;
reg   [31:0] zext_ln21_reg_1652;
reg   [7:0] n_5_reg_1657;
reg   [0:0] icmp_ln10_reg_1664_pp0_iter2_reg;
reg   [0:0] icmp_ln10_reg_1664_pp0_iter4_reg;
wire   [6:0] trunc_ln10_fu_775_p1;
reg   [6:0] trunc_ln10_reg_1668;
reg   [6:0] trunc_ln10_reg_1668_pp0_iter2_reg;
wire   [6:0] trunc_ln10_2_fu_779_p1;
reg   [6:0] trunc_ln10_2_reg_1674;
wire   [7:0] trunc_ln10_4_fu_787_p1;
reg   [7:0] trunc_ln10_4_reg_1681;
wire   [0:0] lane_2_fu_800_p1;
reg   [0:0] lane_2_reg_1687;
reg   [0:0] lane_2_reg_1687_pp0_iter2_reg;
reg   [0:0] lane_2_reg_1687_pp0_iter3_reg;
reg   [0:0] lane_2_reg_1687_pp0_iter4_reg;
wire   [5:0] bi_i_fu_804_p4;
reg   [5:0] bi_i_reg_1698;
reg   [5:0] bi_i_reg_1698_pp0_iter2_reg;
reg   [5:0] bi_i_reg_1698_pp0_iter3_reg;
reg   [5:0] bi_i_reg_1698_pp0_iter4_reg;
wire   [6:0] biw_fu_820_p3;
wire   [6:0] lane_fu_858_p3;
reg   [6:0] lane_reg_1725;
wire   [1:0] sel_tmp_i_fu_877_p3;
reg   [1:0] sel_tmp_i_reg_1731;
reg   [1:0] sel_tmp_i_reg_1731_pp0_iter2_reg;
wire   [0:0] grp_fu_636_p2;
reg   [0:0] icmp_ln26_reg_1737;
reg   [7:0] current_reg_1742;
wire   [6:0] prev_fu_924_p2;
reg   [6:0] prev_reg_1747;
wire   [1:0] sel_tmp5_i_fu_941_p3;
reg   [1:0] sel_tmp5_i_reg_1753;
reg   [1:0] sel_tmp5_i_reg_1753_pp0_iter2_reg;
reg   [23:0] x_21_reg_1759;
reg   [23:0] x_21_reg_1759_pp0_iter3_reg;
reg   [23:0] x_21_reg_1759_pp0_iter4_reg;
wire   [11:0] r_a_2_fu_1019_p3;
reg   [11:0] r_a_2_reg_1780;
reg   [11:0] r_a_2_reg_1780_pp0_iter3_reg;
wire   [7:0] r_addr_2_fu_1065_p2;
wire   [7:0] j_fu_1087_p2;
wire   [7:0] r_addr_fu_1119_p2;
reg   [7:0] r_addr_reg_1825;
reg   [7:0] r_addr_reg_1825_pp0_iter3_reg;
reg   [7:0] r_addr_reg_1825_pp0_iter4_reg;
reg   [0:0] tmp_11_reg_1835;
wire   [11:0] trunc_ln62_6_fu_1131_p1;
wire   [11:0] r_b_2_fu_1185_p3;
reg   [11:0] r_b_2_reg_1850;
wire   [11:0] b_fu_1204_p9;
reg   [11:0] b_reg_1855;
wire   [11:0] a_fu_1223_p9;
reg   [11:0] a_reg_1860;
wire   [11:0] r_aux_fu_1263_p9;
wire   [11:0] r_b_fu_1282_p9;
wire   [11:0] x_11_fu_1314_p3;
reg   [11:0] x_11_reg_1885;
reg   [11:0] x_11_reg_1885_pp0_iter4_reg;
wire   [11:0] r_b_1_fu_1379_p3;
wire   [11:0] r_aux_1_fu_1409_p3;
wire   [22:0] a2_fu_1473_p2;
reg   [22:0] a2_reg_1904;
reg   [6:0] ap_phi_mux_ai_2_i_i_phi_fu_458_p4;
wire   [6:0] ap_phi_reg_pp0_iter0_ai_2_i_i_reg_455;
reg   [6:0] ap_phi_reg_pp0_iter1_ai_2_i_i_reg_455;
reg   [6:0] ap_phi_reg_pp0_iter2_ai_2_i_i_reg_455;
wire   [6:0] ai_fu_992_p1;
reg   [6:0] ap_phi_mux_ai_2_ph_i_i_phi_fu_467_p4;
reg   [6:0] ap_phi_reg_pp0_iter2_ai_2_ph_i_i_reg_464;
wire   [6:0] ap_phi_reg_pp0_iter0_ai_2_ph_i_i_reg_464;
reg   [6:0] ap_phi_reg_pp0_iter1_ai_2_ph_i_i_reg_464;
wire   [1:0] zext_ln12_fu_1337_p1;
wire   [1:0] ap_phi_reg_pp0_iter4_r_tag_3_i_i_reg_473;
reg    ap_predicate_pred401_state5;
wire   [1:0] r_tag_2_fu_1329_p3;
reg    ap_predicate_pred409_state5;
wire   [2:0] select_ln12_cast_i_cast_fu_1341_p3;
wire   [2:0] ap_phi_reg_pp0_iter4_r_tag_3_ph_i_i_reg_483;
reg    ap_predicate_pred417_state5;
wire   [2:0] r_tag_3_fu_1321_p3;
reg    ap_predicate_pred423_state5;
reg   [11:0] ap_phi_mux_r_a_3_phi_fu_496_p12;
wire   [11:0] ap_phi_reg_pp0_iter0_r_a_3_reg_493;
reg   [11:0] ap_phi_reg_pp0_iter1_r_a_3_reg_493;
reg   [11:0] ap_phi_reg_pp0_iter2_r_a_3_reg_493;
reg   [11:0] ap_phi_reg_pp0_iter3_r_a_3_reg_493;
reg   [11:0] ap_phi_reg_pp0_iter4_r_a_3_reg_493;
reg   [11:0] ap_phi_reg_pp0_iter5_r_a_3_reg_493;
reg    ap_predicate_pred450_state4;
reg    ap_predicate_pred455_state4;
reg   [11:0] ap_phi_mux_r_b_3_phi_fu_514_p12;
wire   [11:0] ap_phi_reg_pp0_iter0_r_b_3_reg_511;
reg   [11:0] ap_phi_reg_pp0_iter1_r_b_3_reg_511;
reg   [11:0] ap_phi_reg_pp0_iter2_r_b_3_reg_511;
reg   [11:0] ap_phi_reg_pp0_iter3_r_b_3_reg_511;
reg   [11:0] ap_phi_reg_pp0_iter4_r_b_3_reg_511;
reg   [11:0] ap_phi_reg_pp0_iter5_r_b_3_reg_511;
wire   [11:0] trunc_ln62_7_fu_1490_p1;
reg   [11:0] ap_phi_mux_r_aux_2_phi_fu_533_p12;
wire   [11:0] ap_phi_reg_pp0_iter0_r_aux_2_reg_529;
reg   [11:0] ap_phi_reg_pp0_iter1_r_aux_2_reg_529;
reg   [11:0] ap_phi_reg_pp0_iter2_r_aux_2_reg_529;
reg   [11:0] ap_phi_reg_pp0_iter3_r_aux_2_reg_529;
reg   [11:0] ap_phi_reg_pp0_iter4_r_aux_2_reg_529;
reg   [11:0] ap_phi_reg_pp0_iter5_r_aux_2_reg_529;
reg   [22:0] ap_phi_mux_r_direct_product_1_phi_fu_555_p12;
wire   [22:0] ap_phi_reg_pp0_iter0_r_direct_product_1_reg_551;
reg   [22:0] ap_phi_reg_pp0_iter1_r_direct_product_1_reg_551;
reg   [22:0] ap_phi_reg_pp0_iter2_r_direct_product_1_reg_551;
reg   [22:0] ap_phi_reg_pp0_iter3_r_direct_product_1_reg_551;
reg   [22:0] ap_phi_reg_pp0_iter4_r_direct_product_1_reg_551;
reg   [22:0] ap_phi_reg_pp0_iter5_r_direct_product_1_reg_551;
wire   [22:0] direct_fu_1518_p2;
reg   [7:0] ap_phi_mux_r_addr_3_phi_fu_577_p12;
wire   [7:0] ap_phi_reg_pp0_iter0_r_addr_3_reg_574;
reg   [7:0] ap_phi_reg_pp0_iter1_r_addr_3_reg_574;
reg   [7:0] ap_phi_reg_pp0_iter2_r_addr_3_reg_574;
reg   [7:0] ap_phi_reg_pp0_iter3_r_addr_3_reg_574;
reg   [7:0] ap_phi_reg_pp0_iter4_r_addr_3_reg_574;
reg   [7:0] ap_phi_reg_pp0_iter5_r_addr_3_reg_574;
wire   [7:0] zext_ln28_fu_1479_p1;
reg   [3:0] ap_phi_mux_r_tag_4_phi_fu_595_p12;
wire   [3:0] ap_phi_reg_pp0_iter0_r_tag_4_reg_591;
reg   [3:0] ap_phi_reg_pp0_iter1_r_tag_4_reg_591;
reg   [3:0] ap_phi_reg_pp0_iter2_r_tag_4_reg_591;
reg   [3:0] ap_phi_reg_pp0_iter3_r_tag_4_reg_591;
reg   [3:0] ap_phi_reg_pp0_iter4_r_tag_4_reg_591;
reg   [3:0] ap_phi_reg_pp0_iter5_r_tag_4_reg_591;
wire   [3:0] r_tag_fu_1507_p3;
wire   [3:0] zext_ln12_2_fu_1485_p1;
wire   [3:0] zext_ln12_1_fu_1494_p1;
reg   [0:0] ap_phi_mux_r_use_direct_phi_fu_616_p12;
wire   [0:0] ap_phi_reg_pp0_iter0_r_use_direct_reg_612;
reg   [0:0] ap_phi_reg_pp0_iter1_r_use_direct_reg_612;
reg   [0:0] ap_phi_reg_pp0_iter2_r_use_direct_reg_612;
reg   [0:0] ap_phi_reg_pp0_iter3_r_use_direct_reg_612;
reg   [0:0] ap_phi_reg_pp0_iter4_r_use_direct_reg_612;
reg   [0:0] ap_phi_reg_pp0_iter5_r_use_direct_reg_612;
wire   [63:0] zext_ln35_fu_828_p1;
wire   [63:0] zext_ln36_1_fu_842_p1;
wire   [63:0] zext_ln35_2_fu_997_p1;
wire   [63:0] zext_ln35_1_fu_1002_p1;
wire   [63:0] zext_ln36_fu_1014_p1;
wire   [63:0] zext_ln22_fu_1031_p1;
wire   [63:0] zext_ln23_fu_1041_p1;
wire   [63:0] zext_ln23_1_fu_1056_p1;
wire   [63:0] zext_ln15_fu_1091_p1;
wire   [63:0] zext_ln16_fu_1100_p1;
wire   [63:0] zext_ln16_1_fu_1114_p1;
wire   [63:0] zext_ln10_fu_984_p1;
wire   [63:0] zext_ln25_fu_1246_p1;
wire   [63:0] zext_ln18_fu_1305_p1;
reg   [7:0] n_fu_198;
wire   [7:0] add_ln10_fu_759_p2;
wire    ap_loop_init;
reg   [31:0] pair_base_fu_202;
wire   [31:0] pair_base_2_fu_1075_p3;
reg   [31:0] start_fu_206;
wire   [31:0] start_2_fu_953_p3;
reg   [31:0] offset_fu_210;
wire   [31:0] grp_fu_650_p3;
reg   [31:0] block_fu_214;
wire   [31:0] grp_fu_658_p3;
reg    ap_block_pp0_stage0_01001;
reg    bnt_ce0_local;
reg    bm_in_0_ce0_local;
reg    bm_in_4_ce0_local;
reg    ant_ce0_local;
reg   [6:0] ant_address0_local;
reg    zetas39c_ce1_local;
reg    zetas39c_ce0_local;
reg   [6:0] zetas39c_address0_local;
reg    src_ce0_local;
reg   [6:0] src_address0_local;
reg    src_ce1_local;
reg   [6:0] src_address1_local;
wire   [31:0] grp_fu_645_p2;
wire   [31:0] grp_fu_640_p2;
wire   [0:0] grp_fu_681_p3;
wire   [11:0] grp_fu_689_p2;
wire   [0:0] xor_ln31_fu_814_p2;
wire   [0:0] icmp_ln23_fu_848_p2;
wire   [6:0] sub_ln23_fu_853_p2;
wire   [0:0] xor_ln22_fu_866_p2;
wire   [0:0] and_ln23_fu_871_p2;
wire   [0:0] trunc_ln10_3_fu_783_p1;
wire   [6:0] trunc_ln14_1_i_fu_907_p4;
wire   [6:0] select_ln16_fu_917_p3;
wire   [0:0] xor_ln15_fu_930_p2;
wire   [0:0] and_ln10_fu_935_p2;
wire   [31:0] start_1_fu_948_p2;
wire   [6:0] zext_ln36_i_cast_fu_1007_p3;
wire   [6:0] trunc_ln10_1_fu_988_p1;
wire   [6:0] add_ln22_fu_1026_p2;
wire   [6:0] add_ln23_fu_1036_p2;
wire   [6:0] add_ln23_1_fu_1046_p2;
wire   [6:0] add_ln23_2_fu_1050_p2;
wire   [7:0] trunc_ln25_fu_1061_p1;
wire   [31:0] pair_base_1_fu_1070_p2;
wire   [6:0] add_ln16_fu_1096_p2;
wire   [6:0] add_ln16_1_fu_1105_p2;
wire   [6:0] add_ln16_2_fu_1109_p2;
wire   [0:0] tmp_15_fu_1143_p3;
wire   [11:0] add_ln50_6_fu_1151_p2;
wire   [11:0] z_fu_1157_p3;
wire   [0:0] icmp_ln37_fu_1165_p2;
wire   [11:0] sub_ln37_fu_1171_p2;
wire   [11:0] select_ln37_fu_1177_p3;
wire   [11:0] b_fu_1204_p2;
wire   [11:0] b_fu_1204_p4;
wire   [11:0] b_fu_1204_p6;
wire   [11:0] b_fu_1204_p7;
wire   [11:0] a_fu_1223_p2;
wire   [11:0] grp_fu_665_p3;
wire   [11:0] a_fu_1223_p4;
wire   [11:0] a_fu_1223_p6;
wire   [11:0] a_fu_1223_p7;
wire   [6:0] sub_ln25_fu_1242_p2;
wire   [11:0] r_aux_fu_1263_p2;
wire   [11:0] r_aux_fu_1263_p4;
wire   [11:0] r_aux_fu_1263_p6;
wire   [11:0] r_aux_fu_1263_p7;
wire   [11:0] r_b_fu_1282_p2;
wire   [11:0] r_b_fu_1282_p4;
wire   [11:0] r_b_fu_1282_p6;
wire   [11:0] r_b_fu_1282_p7;
wire   [6:0] add_ln18_fu_1301_p2;
wire   [11:0] x_9_fu_1310_p1;
wire   [12:0] zext_ln58_fu_1349_p1;
wire   [12:0] zext_ln58_1_fu_1352_p1;
wire   [12:0] d_fu_1355_p2;
wire   [11:0] trunc_ln58_fu_1369_p1;
wire   [0:0] tmp_14_fu_1361_p3;
wire   [11:0] add_ln58_fu_1373_p2;
wire   [12:0] s_fu_1387_p2;
wire   [11:0] trunc_ln54_fu_1399_p1;
wire   [0:0] icmp_ln54_fu_1393_p2;
wire   [11:0] add_ln54_fu_1403_p2;
wire   [21:0] shl_ln1_i_fu_1417_p3;
wire   [19:0] shl_ln40_1_i_fu_1424_p3;
wire   [22:0] zext_ln40_fu_1431_p1;
wire   [22:0] zext_ln40_1_fu_1435_p1;
wire   [18:0] shl_ln40_2_i_fu_1445_p3;
wire   [22:0] a0_fu_1439_p2;
wire   [22:0] zext_ln40_2_fu_1452_p1;
wire   [16:0] shl_ln40_3_i_fu_1462_p3;
wire   [22:0] a1_fu_1456_p2;
wire   [22:0] zext_ln40_3_fu_1469_p1;
wire   [22:0] zext_ln41_fu_1515_p1;
wire   [74:0] or_ln48_5_i_fu_1524_p10;
reg    ap_predicate_pred1147_state4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_450;
reg    ap_condition_455;
reg    ap_condition_367;
reg    ap_condition_276;
reg    ap_condition_390;
reg    ap_condition_447;
reg    ap_condition_1295;
reg    ap_condition_655;
reg    ap_condition_668;
reg    ap_condition_677;
reg    ap_condition_685;
reg    ap_condition_1308;
reg    ap_condition_1312;
wire  signed [1:0] b_fu_1204_p1;
wire   [1:0] b_fu_1204_p3;
wire   [1:0] b_fu_1204_p5;
wire  signed [1:0] a_fu_1223_p1;
wire   [1:0] a_fu_1223_p3;
wire   [1:0] a_fu_1223_p5;
wire  signed [1:0] r_aux_fu_1263_p1;
wire   [1:0] r_aux_fu_1263_p3;
wire   [1:0] r_aux_fu_1263_p5;
wire  signed [1:0] r_b_fu_1282_p1;
wire   [1:0] r_b_fu_1282_p3;
wire   [1:0] r_b_fu_1282_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 n_fu_198 = 8'd0;
#0 pair_base_fu_202 = 32'd0;
#0 start_fu_206 = 32'd0;
#0 offset_fu_210 = 32'd0;
#0 block_fu_214 = 32'd0;
#0 ap_done_reg = 1'b0;
end

mlkem_poly_mul256_v39e_true_one_dsp_issue39d_Pipeline_issue39d_loop_zetas39c_ROM_AUTO_1R #(
    .DataWidth( 12 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
zetas39c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(zetas39c_address0_local),
    .ce0(zetas39c_ce0_local),
    .q0(zetas39c_q0),
    .address1(zetas39c_address1),
    .ce1(zetas39c_ce1_local),
    .q1(zetas39c_q1)
);

(* dissolve_hierarchy = "yes" *) mlkem_poly_mul256_v39e_true_one_dsp_sparsemux_7_2_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 12 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 12 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 12 ),
    .def_WIDTH( 12 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 12 ))
sparsemux_7_2_12_1_1_U3(
    .din0(b_fu_1204_p2),
    .din1(b_fu_1204_p4),
    .din2(b_fu_1204_p6),
    .def(b_fu_1204_p7),
    .sel(sel_tmp_i_reg_1731_pp0_iter2_reg),
    .dout(b_fu_1204_p9)
);

(* dissolve_hierarchy = "yes" *) mlkem_poly_mul256_v39e_true_one_dsp_sparsemux_7_2_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 12 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 12 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 12 ),
    .def_WIDTH( 12 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 12 ))
sparsemux_7_2_12_1_1_U4(
    .din0(a_fu_1223_p2),
    .din1(a_fu_1223_p4),
    .din2(a_fu_1223_p6),
    .def(a_fu_1223_p7),
    .sel(sel_tmp_i_reg_1731_pp0_iter2_reg),
    .dout(a_fu_1223_p9)
);

(* dissolve_hierarchy = "yes" *) mlkem_poly_mul256_v39e_true_one_dsp_sparsemux_7_2_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 12 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 12 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 12 ),
    .def_WIDTH( 12 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 12 ))
sparsemux_7_2_12_1_1_U5(
    .din0(r_aux_fu_1263_p2),
    .din1(r_aux_fu_1263_p4),
    .din2(r_aux_fu_1263_p6),
    .def(r_aux_fu_1263_p7),
    .sel(sel_tmp5_i_reg_1753_pp0_iter2_reg),
    .dout(r_aux_fu_1263_p9)
);

(* dissolve_hierarchy = "yes" *) mlkem_poly_mul256_v39e_true_one_dsp_sparsemux_7_2_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 12 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 12 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 12 ),
    .def_WIDTH( 12 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 12 ))
sparsemux_7_2_12_1_1_U6(
    .din0(r_b_fu_1282_p2),
    .din1(r_b_fu_1282_p4),
    .din2(r_b_fu_1282_p6),
    .def(r_b_fu_1282_p7),
    .sel(sel_tmp5_i_reg_1753_pp0_iter2_reg),
    .dout(r_b_fu_1282_p9)
);

mlkem_poly_mul256_v39e_true_one_dsp_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_276)) begin
        if ((1'b1 == ap_condition_367)) begin
            ap_phi_reg_pp0_iter2_ai_2_i_i_reg_455 <= biw_fu_820_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_ai_2_i_i_reg_455 <= ap_phi_reg_pp0_iter1_ai_2_i_i_reg_455;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_276)) begin
        if ((1'b1 == ap_condition_390)) begin
            ap_phi_reg_pp0_iter2_ai_2_ph_i_i_reg_464 <= biw_fu_820_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_ai_2_ph_i_i_reg_464 <= ap_phi_reg_pp0_iter1_ai_2_ph_i_i_reg_464;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_276)) begin
        if (((icmp_ln10_fu_753_p2 == 1'd0) & (tmp_10_reg_1625 == 2'd0))) begin
            ap_phi_reg_pp0_iter2_r_direct_product_1_reg_551 <= 23'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_r_direct_product_1_reg_551 <= ap_phi_reg_pp0_iter1_r_direct_product_1_reg_551;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_276)) begin
        if (((icmp_ln10_fu_753_p2 == 1'd0) & (tmp_10_reg_1625 == 2'd0))) begin
            ap_phi_reg_pp0_iter2_r_tag_4_reg_591 <= 4'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_r_tag_4_reg_591 <= ap_phi_reg_pp0_iter1_r_tag_4_reg_591;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_276)) begin
        if (((icmp_ln10_fu_753_p2 == 1'd0) & (tmp_10_reg_1625 == 2'd0))) begin
            ap_phi_reg_pp0_iter2_r_use_direct_reg_612 <= 1'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_r_use_direct_reg_612 <= ap_phi_reg_pp0_iter1_r_use_direct_reg_612;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if (((tmp_10_reg_1625 == 2'd2) & (icmp_ln10_reg_1664 == 1'd0))) begin
            ap_phi_reg_pp0_iter3_r_addr_3_reg_574 <= r_addr_2_fu_1065_p2;
        end else if (((tmp_10_reg_1625 == 2'd0) & (icmp_ln10_reg_1664 == 1'd0))) begin
            ap_phi_reg_pp0_iter3_r_addr_3_reg_574 <= j_fu_1087_p2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_r_addr_3_reg_574 <= ap_phi_reg_pp0_iter2_r_addr_3_reg_574;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (((tmp_7_reg_1596 == 2'd2) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1) & (icmp_ln10_reg_1664 == 1'd0)) | ((tmp_7_reg_1596 == 2'd3) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1) & (icmp_ln10_reg_1664 == 1'd0)))) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (((tmp_7_reg_1596 == 2'd1) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1) & (icmp_ln10_reg_1664 == 1'd0)) | ((tmp_7_reg_1596 == 2'd0) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1) & (icmp_ln10_reg_1664 == 1'd0)))))) begin
        ap_phi_reg_pp0_iter3_r_aux_2_reg_529 <= 12'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_r_aux_2_reg_529 <= ap_phi_reg_pp0_iter2_r_aux_2_reg_529;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (((tmp_7_reg_1596 == 2'd2) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1) & (icmp_ln10_reg_1664 == 1'd0)) | ((tmp_7_reg_1596 == 2'd3) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1) & (icmp_ln10_reg_1664 == 1'd0)))) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (((tmp_7_reg_1596 == 2'd1) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1) & (icmp_ln10_reg_1664 == 1'd0)) | ((tmp_7_reg_1596 == 2'd0) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1) & (icmp_ln10_reg_1664 == 1'd0)))) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_10_reg_1625 == 2'd2) & (icmp_ln10_reg_1664 == 1'd0)))) begin
        ap_phi_reg_pp0_iter3_r_direct_product_1_reg_551 <= 23'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_r_direct_product_1_reg_551 <= ap_phi_reg_pp0_iter2_r_direct_product_1_reg_551;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if (((tmp_10_reg_1625 == 2'd2) & (icmp_ln10_reg_1664 == 1'd0))) begin
            ap_phi_reg_pp0_iter3_r_tag_4_reg_591 <= 4'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_r_tag_4_reg_591 <= ap_phi_reg_pp0_iter2_r_tag_4_reg_591;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (((tmp_7_reg_1596 == 2'd2) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1) & (icmp_ln10_reg_1664 == 1'd0)) | ((tmp_7_reg_1596 == 2'd3) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1) & (icmp_ln10_reg_1664 == 1'd0)))) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (((tmp_7_reg_1596 == 2'd1) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1) & (icmp_ln10_reg_1664 == 1'd0)) | ((tmp_7_reg_1596 == 2'd0) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1) & (icmp_ln10_reg_1664 == 1'd0)))) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_10_reg_1625 == 2'd2) & (icmp_ln10_reg_1664 == 1'd0)))) begin
        ap_phi_reg_pp0_iter3_r_use_direct_reg_612 <= 1'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_r_use_direct_reg_612 <= ap_phi_reg_pp0_iter2_r_use_direct_reg_612;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if ((ap_predicate_pred455_state4 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_r_a_3_reg_493 <= {{ant_q0[23:12]}};
        end else if ((ap_predicate_pred450_state4 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_r_a_3_reg_493 <= trunc_ln62_6_fu_1131_p1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_r_a_3_reg_493 <= ap_phi_reg_pp0_iter3_r_a_3_reg_493;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if (((icmp_ln10_reg_1664_pp0_iter2_reg == 1'd0) & (tmp_10_reg_1625 == 2'd0))) begin
            ap_phi_reg_pp0_iter4_r_aux_2_reg_529 <= r_aux_fu_1263_p9;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_r_aux_2_reg_529 <= ap_phi_reg_pp0_iter3_r_aux_2_reg_529;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if (((icmp_ln10_reg_1664_pp0_iter2_reg == 1'd0) & (tmp_10_reg_1625 == 2'd0))) begin
            ap_phi_reg_pp0_iter4_r_b_3_reg_511 <= r_b_fu_1282_p9;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_r_b_3_reg_511 <= ap_phi_reg_pp0_iter3_r_b_3_reg_511;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_6_reg_1592 == 1'd1) & (tmp_10_reg_1625 == 2'd1) & (icmp_ln10_reg_1664_pp0_iter3_reg == 1'd0))) begin
        ap_phi_reg_pp0_iter5_r_a_3_reg_493 <= r_a_2_reg_1780_pp0_iter3_reg;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_10_reg_1625 == 2'd0) & (icmp_ln10_reg_1664_pp0_iter3_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_10_reg_1625 == 2'd2) & (icmp_ln10_reg_1664_pp0_iter3_reg == 1'd0)))) begin
        ap_phi_reg_pp0_iter5_r_a_3_reg_493 <= grp_fu_695_p3;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_phi_reg_pp0_iter5_r_a_3_reg_493 <= ap_phi_reg_pp0_iter4_r_a_3_reg_493;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        if ((1'b1 == ap_condition_447)) begin
            ap_phi_reg_pp0_iter5_r_aux_2_reg_529 <= 12'd0;
        end else if (((tmp_10_reg_1625 == 2'd2) & (icmp_ln10_reg_1664_pp0_iter3_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter5_r_aux_2_reg_529 <= r_aux_1_fu_1409_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter5_r_aux_2_reg_529 <= ap_phi_reg_pp0_iter4_r_aux_2_reg_529;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        if ((1'b1 == ap_condition_447)) begin
            ap_phi_reg_pp0_iter5_r_b_3_reg_511 <= r_b_2_reg_1850;
        end else if (((tmp_10_reg_1625 == 2'd2) & (icmp_ln10_reg_1664_pp0_iter3_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter5_r_b_3_reg_511 <= r_b_1_fu_1379_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter5_r_b_3_reg_511 <= ap_phi_reg_pp0_iter4_r_b_3_reg_511;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        if ((1'b1 == ap_condition_447)) begin
            ap_phi_reg_pp0_iter5_r_direct_product_1_reg_551 <= 23'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter5_r_direct_product_1_reg_551 <= ap_phi_reg_pp0_iter4_r_direct_product_1_reg_551;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        if ((1'b1 == ap_condition_447)) begin
            ap_phi_reg_pp0_iter5_r_use_direct_reg_612 <= 1'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter5_r_use_direct_reg_612 <= ap_phi_reg_pp0_iter4_r_use_direct_reg_612;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        block_fu_214 <= 32'd0;
    end else if ((((icmp_ln10_fu_753_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_10_reg_1625 == 2'd0)) | ((icmp_ln10_fu_753_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_10_reg_1625 == 2'd2)))) begin
        block_fu_214 <= grp_fu_658_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            n_fu_198 <= 8'd0;
        end else if (((icmp_ln10_fu_753_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            n_fu_198 <= add_ln10_fu_759_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        offset_fu_210 <= 32'd0;
    end else if ((((icmp_ln10_fu_753_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_10_reg_1625 == 2'd0)) | ((icmp_ln10_fu_753_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_10_reg_1625 == 2'd2)))) begin
        offset_fu_210 <= grp_fu_650_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            pair_base_fu_202 <= 32'd0;
        end else if ((1'b1 == ap_condition_1295)) begin
            pair_base_fu_202 <= pair_base_2_fu_1075_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        if ((ap_predicate_pred409_state5 == 1'b1)) begin
            r_tag_3_i_i_reg_473 <= r_tag_2_fu_1329_p3;
        end else if ((ap_predicate_pred401_state5 == 1'b1)) begin
            r_tag_3_i_i_reg_473 <= zext_ln12_fu_1337_p1;
        end else if (~(icmp_ln10_reg_1664_pp0_iter3_reg == 1'd1)) begin
            r_tag_3_i_i_reg_473 <= ap_phi_reg_pp0_iter4_r_tag_3_i_i_reg_473;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        if ((ap_predicate_pred423_state5 == 1'b1)) begin
            r_tag_3_ph_i_i_reg_483 <= r_tag_3_fu_1321_p3;
        end else if ((ap_predicate_pred417_state5 == 1'b1)) begin
            r_tag_3_ph_i_i_reg_483 <= select_ln12_cast_i_cast_fu_1341_p3;
        end else if (~(icmp_ln10_reg_1664_pp0_iter3_reg == 1'd1)) begin
            r_tag_3_ph_i_i_reg_483 <= ap_phi_reg_pp0_iter4_r_tag_3_ph_i_i_reg_483;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            start_fu_206 <= 32'd0;
        end else if ((1'b1 == ap_condition_1308)) begin
            start_fu_206 <= start_2_fu_953_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        a2_reg_1904[22 : 5] <= a2_fu_1473_p2[22 : 5];
        a_reg_1860 <= a_fu_1223_p9;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_predicate_pred1147_state4 <= ((lane_2_reg_1687 == 1'd1) & (tmp_6_reg_1592 == 1'd1) & (tmp_10_reg_1625 == 2'd1) & (icmp_ln10_reg_1664 == 1'd0));
        ap_predicate_pred401_state5 <= ((icmp_ln10_reg_1664_pp0_iter2_reg == 1'd0) & (tmp_7_reg_1596 == 2'd0) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1));
        ap_predicate_pred409_state5 <= ((icmp_ln10_reg_1664_pp0_iter2_reg == 1'd0) & (tmp_7_reg_1596 == 2'd1) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1));
        ap_predicate_pred417_state5 <= ((icmp_ln10_reg_1664_pp0_iter2_reg == 1'd0) & (tmp_7_reg_1596 == 2'd3) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1));
        ap_predicate_pred423_state5 <= ((icmp_ln10_reg_1664_pp0_iter2_reg == 1'd0) & (tmp_7_reg_1596 == 2'd2) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1));
        ap_predicate_pred450_state4 <= (((tmp_7_reg_1596 == 2'd1) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1) & (icmp_ln10_reg_1664 == 1'd0)) | ((tmp_7_reg_1596 == 2'd0) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1) & (icmp_ln10_reg_1664 == 1'd0)));
        ap_predicate_pred455_state4 <= (((tmp_7_reg_1596 == 2'd2) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1) & (icmp_ln10_reg_1664 == 1'd0)) | ((tmp_7_reg_1596 == 2'd3) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1) & (icmp_ln10_reg_1664 == 1'd0)));
        b_reg_1855 <= b_fu_1204_p9;
        bi_i_reg_1698_pp0_iter2_reg <= bi_i_reg_1698;
        bi_i_reg_1698_pp0_iter3_reg <= bi_i_reg_1698_pp0_iter2_reg;
        bi_i_reg_1698_pp0_iter4_reg <= bi_i_reg_1698_pp0_iter3_reg;
        icmp_ln10_reg_1664_pp0_iter2_reg <= icmp_ln10_reg_1664;
        icmp_ln10_reg_1664_pp0_iter3_reg <= icmp_ln10_reg_1664_pp0_iter2_reg;
        icmp_ln10_reg_1664_pp0_iter4_reg <= icmp_ln10_reg_1664_pp0_iter3_reg;
        lane_2_reg_1687_pp0_iter2_reg <= lane_2_reg_1687;
        lane_2_reg_1687_pp0_iter3_reg <= lane_2_reg_1687_pp0_iter2_reg;
        lane_2_reg_1687_pp0_iter4_reg <= lane_2_reg_1687_pp0_iter3_reg;
        r_a_2_reg_1780 <= r_a_2_fu_1019_p3;
        r_a_2_reg_1780_pp0_iter3_reg <= r_a_2_reg_1780;
        r_addr_reg_1825 <= r_addr_fu_1119_p2;
        r_addr_reg_1825_pp0_iter3_reg <= r_addr_reg_1825;
        r_addr_reg_1825_pp0_iter4_reg <= r_addr_reg_1825_pp0_iter3_reg;
        r_b_2_reg_1850 <= r_b_2_fu_1185_p3;
        sel_tmp5_i_reg_1753_pp0_iter2_reg <= sel_tmp5_i_reg_1753;
        sel_tmp_i_reg_1731_pp0_iter2_reg <= sel_tmp_i_reg_1731;
        tmp_11_reg_1835 <= r_addr_fu_1119_p2[32'd7];
        trunc_ln10_reg_1668_pp0_iter2_reg <= trunc_ln10_reg_1668;
        x_11_reg_1885 <= x_11_fu_1314_p3;
        x_11_reg_1885_pp0_iter4_reg <= x_11_reg_1885;
        x_21_reg_1759 <= bnt_q0;
        x_21_reg_1759_pp0_iter3_reg <= x_21_reg_1759;
        x_21_reg_1759_pp0_iter4_reg <= x_21_reg_1759_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        bi_i_reg_1698 <= {{n_fu_198[6:1]}};
        current_reg_1742 <= {{start_fu_206[8:1]}};
        icmp_ln10_reg_1664 <= icmp_ln10_fu_753_p2;
        icmp_ln15_i_read_reg_1613 <= icmp_ln15_i;
        icmp_ln22_i_read_reg_1601 <= icmp_ln22_i;
        lane_2_reg_1687 <= lane_2_fu_800_p1;
        lane_reg_1725 <= lane_fu_858_p3;
        len_cast11_i_i_cast_reg_1637[7 : 0] <= len_cast11_i_i_cast_fu_709_p1[7 : 0];
        n_5_reg_1657 <= n_fu_198;
        prev_reg_1747 <= prev_fu_924_p2;
        prevlen_i_read_reg_1631 <= prevlen_i;
        sel_tmp5_i_reg_1753 <= sel_tmp5_i_fu_941_p3;
        sel_tmp_i_reg_1731 <= sel_tmp_i_fu_877_p3;
        sext_ln19_reg_1647 <= sext_ln19_fu_717_p1;
        tmp_10_reg_1625 <= empty_36;
        tmp_6_reg_1592 <= empty_40;
        tmp_7_reg_1596 <= empty_39;
        tmp_8_reg_1607 <= empty_38;
        tmp_9_reg_1619 <= empty_37;
        tmp_reg_1587 <= empty;
        trunc_ln10_2_reg_1674 <= trunc_ln10_2_fu_779_p1;
        trunc_ln10_4_reg_1681 <= trunc_ln10_4_fu_787_p1;
        trunc_ln10_reg_1668 <= trunc_ln10_fu_775_p1;
        zext_ln10_i_cast_reg_1642[8 : 0] <= zext_ln10_i_cast_fu_713_p1[8 : 0];
        zext_ln21_reg_1652[6 : 0] <= zext_ln21_fu_721_p1[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_ai_2_i_i_reg_455 <= ap_phi_reg_pp0_iter0_ai_2_i_i_reg_455;
        ap_phi_reg_pp0_iter1_ai_2_ph_i_i_reg_464 <= ap_phi_reg_pp0_iter0_ai_2_ph_i_i_reg_464;
        ap_phi_reg_pp0_iter1_r_a_3_reg_493 <= ap_phi_reg_pp0_iter0_r_a_3_reg_493;
        ap_phi_reg_pp0_iter1_r_addr_3_reg_574 <= ap_phi_reg_pp0_iter0_r_addr_3_reg_574;
        ap_phi_reg_pp0_iter1_r_aux_2_reg_529 <= ap_phi_reg_pp0_iter0_r_aux_2_reg_529;
        ap_phi_reg_pp0_iter1_r_b_3_reg_511 <= ap_phi_reg_pp0_iter0_r_b_3_reg_511;
        ap_phi_reg_pp0_iter1_r_direct_product_1_reg_551 <= ap_phi_reg_pp0_iter0_r_direct_product_1_reg_551;
        ap_phi_reg_pp0_iter1_r_tag_4_reg_591 <= ap_phi_reg_pp0_iter0_r_tag_4_reg_591;
        ap_phi_reg_pp0_iter1_r_use_direct_reg_612 <= ap_phi_reg_pp0_iter0_r_use_direct_reg_612;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_r_a_3_reg_493 <= ap_phi_reg_pp0_iter1_r_a_3_reg_493;
        ap_phi_reg_pp0_iter2_r_addr_3_reg_574 <= ap_phi_reg_pp0_iter1_r_addr_3_reg_574;
        ap_phi_reg_pp0_iter2_r_aux_2_reg_529 <= ap_phi_reg_pp0_iter1_r_aux_2_reg_529;
        ap_phi_reg_pp0_iter2_r_b_3_reg_511 <= ap_phi_reg_pp0_iter1_r_b_3_reg_511;
        icmp_ln26_reg_1737 <= grp_fu_636_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_r_a_3_reg_493 <= ap_phi_reg_pp0_iter2_r_a_3_reg_493;
        ap_phi_reg_pp0_iter3_r_b_3_reg_511 <= ap_phi_reg_pp0_iter2_r_b_3_reg_511;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_phi_reg_pp0_iter4_r_addr_3_reg_574 <= ap_phi_reg_pp0_iter3_r_addr_3_reg_574;
        ap_phi_reg_pp0_iter4_r_direct_product_1_reg_551 <= ap_phi_reg_pp0_iter3_r_direct_product_1_reg_551;
        ap_phi_reg_pp0_iter4_r_tag_4_reg_591 <= ap_phi_reg_pp0_iter3_r_tag_4_reg_591;
        ap_phi_reg_pp0_iter4_r_use_direct_reg_612 <= ap_phi_reg_pp0_iter3_r_use_direct_reg_612;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_phi_reg_pp0_iter5_r_addr_3_reg_574 <= ap_phi_reg_pp0_iter4_r_addr_3_reg_574;
        ap_phi_reg_pp0_iter5_r_tag_4_reg_591 <= ap_phi_reg_pp0_iter4_r_tag_4_reg_591;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((1'b1 == ap_condition_455)) begin
            ant_address0_local = zext_ln35_1_fu_1002_p1;
        end else if ((1'b1 == ap_condition_450)) begin
            ant_address0_local = zext_ln35_2_fu_997_p1;
        end else begin
            ant_address0_local = 'bx;
        end
    end else begin
        ant_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (((tmp_7_reg_1596 == 2'd2) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1) & (icmp_ln10_reg_1664 == 1'd0)) | ((tmp_7_reg_1596 == 2'd3) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1) & (icmp_ln10_reg_1664 == 1'd0)))) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (((tmp_7_reg_1596 == 2'd1) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1) & (icmp_ln10_reg_1664 == 1'd0)) | ((tmp_7_reg_1596 == 2'd0) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1) & (icmp_ln10_reg_1664 == 1'd0)))))) begin
        ant_ce0_local = 1'b1;
    end else begin
        ant_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln10_fu_753_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_7_reg_1596 == 2'd1) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1) & (icmp_ln10_reg_1664 == 1'd0))) begin
        ap_phi_mux_ai_2_i_i_phi_fu_458_p4 = ai_fu_992_p1;
    end else begin
        ap_phi_mux_ai_2_i_i_phi_fu_458_p4 = ap_phi_reg_pp0_iter2_ai_2_i_i_reg_455;
    end
end

always @ (*) begin
    if (((tmp_7_reg_1596 == 2'd3) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1) & (icmp_ln10_reg_1664 == 1'd0))) begin
        ap_phi_mux_ai_2_ph_i_i_phi_fu_467_p4 = ai_fu_992_p1;
    end else begin
        ap_phi_mux_ai_2_ph_i_i_phi_fu_467_p4 = ap_phi_reg_pp0_iter2_ai_2_ph_i_i_reg_464;
    end
end

always @ (*) begin
    if (((icmp_ln10_reg_1664_pp0_iter4_reg == 1'd0) & (tmp_10_reg_1625 == 2'd3))) begin
        ap_phi_mux_r_a_3_phi_fu_496_p12 = 12'd0;
    end else begin
        ap_phi_mux_r_a_3_phi_fu_496_p12 = ap_phi_reg_pp0_iter5_r_a_3_reg_493;
    end
end

always @ (*) begin
    if ((((icmp_ln10_reg_1664_pp0_iter4_reg == 1'd0) & (tmp_6_reg_1592 == 1'd1) & (tmp_10_reg_1625 == 2'd1)) | ((icmp_ln10_reg_1664_pp0_iter4_reg == 1'd0) & (tmp_7_reg_1596 == 2'd2) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1)) | ((icmp_ln10_reg_1664_pp0_iter4_reg == 1'd0) & (tmp_7_reg_1596 == 2'd3) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1)) | ((icmp_ln10_reg_1664_pp0_iter4_reg == 1'd0) & (tmp_7_reg_1596 == 2'd1) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1)) | ((icmp_ln10_reg_1664_pp0_iter4_reg == 1'd0) & (tmp_7_reg_1596 == 2'd0) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1)))) begin
        ap_phi_mux_r_addr_3_phi_fu_577_p12 = zext_ln28_fu_1479_p1;
    end else if (((icmp_ln10_reg_1664_pp0_iter4_reg == 1'd0) & (tmp_10_reg_1625 == 2'd3))) begin
        ap_phi_mux_r_addr_3_phi_fu_577_p12 = r_addr_reg_1825_pp0_iter4_reg;
    end else begin
        ap_phi_mux_r_addr_3_phi_fu_577_p12 = ap_phi_reg_pp0_iter5_r_addr_3_reg_574;
    end
end

always @ (*) begin
    if (((icmp_ln10_reg_1664_pp0_iter4_reg == 1'd0) & (tmp_10_reg_1625 == 2'd3))) begin
        ap_phi_mux_r_aux_2_phi_fu_533_p12 = 12'd0;
    end else begin
        ap_phi_mux_r_aux_2_phi_fu_533_p12 = ap_phi_reg_pp0_iter5_r_aux_2_reg_529;
    end
end

always @ (*) begin
    if ((((icmp_ln10_reg_1664_pp0_iter4_reg == 1'd0) & (tmp_7_reg_1596 == 2'd2) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1)) | ((icmp_ln10_reg_1664_pp0_iter4_reg == 1'd0) & (tmp_7_reg_1596 == 2'd3) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1)))) begin
        ap_phi_mux_r_b_3_phi_fu_514_p12 = {{x_21_reg_1759_pp0_iter4_reg[23:12]}};
    end else if ((((icmp_ln10_reg_1664_pp0_iter4_reg == 1'd0) & (tmp_7_reg_1596 == 2'd1) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1)) | ((icmp_ln10_reg_1664_pp0_iter4_reg == 1'd0) & (tmp_7_reg_1596 == 2'd0) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1)))) begin
        ap_phi_mux_r_b_3_phi_fu_514_p12 = trunc_ln62_7_fu_1490_p1;
    end else if (((icmp_ln10_reg_1664_pp0_iter4_reg == 1'd0) & (tmp_10_reg_1625 == 2'd3))) begin
        ap_phi_mux_r_b_3_phi_fu_514_p12 = 12'd0;
    end else begin
        ap_phi_mux_r_b_3_phi_fu_514_p12 = ap_phi_reg_pp0_iter5_r_b_3_reg_511;
    end
end

always @ (*) begin
    if (((icmp_ln10_reg_1664_pp0_iter4_reg == 1'd0) & (tmp_10_reg_1625 == 2'd3))) begin
        ap_phi_mux_r_direct_product_1_phi_fu_555_p12 = direct_fu_1518_p2;
    end else begin
        ap_phi_mux_r_direct_product_1_phi_fu_555_p12 = ap_phi_reg_pp0_iter5_r_direct_product_1_reg_551;
    end
end

always @ (*) begin
    if ((((icmp_ln10_reg_1664_pp0_iter4_reg == 1'd0) & (tmp_7_reg_1596 == 2'd2) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1)) | ((icmp_ln10_reg_1664_pp0_iter4_reg == 1'd0) & (tmp_7_reg_1596 == 2'd3) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1)))) begin
        ap_phi_mux_r_tag_4_phi_fu_595_p12 = zext_ln12_1_fu_1494_p1;
    end else if ((((icmp_ln10_reg_1664_pp0_iter4_reg == 1'd0) & (tmp_7_reg_1596 == 2'd1) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1)) | ((icmp_ln10_reg_1664_pp0_iter4_reg == 1'd0) & (tmp_7_reg_1596 == 2'd0) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1)))) begin
        ap_phi_mux_r_tag_4_phi_fu_595_p12 = zext_ln12_2_fu_1485_p1;
    end else if (((icmp_ln10_reg_1664_pp0_iter4_reg == 1'd0) & (tmp_6_reg_1592 == 1'd1) & (tmp_10_reg_1625 == 2'd1))) begin
        ap_phi_mux_r_tag_4_phi_fu_595_p12 = r_tag_fu_1507_p3;
    end else if (((icmp_ln10_reg_1664_pp0_iter4_reg == 1'd0) & (tmp_10_reg_1625 == 2'd3))) begin
        ap_phi_mux_r_tag_4_phi_fu_595_p12 = 4'd0;
    end else begin
        ap_phi_mux_r_tag_4_phi_fu_595_p12 = ap_phi_reg_pp0_iter5_r_tag_4_reg_591;
    end
end

always @ (*) begin
    if (((icmp_ln10_reg_1664_pp0_iter4_reg == 1'd0) & (tmp_10_reg_1625 == 2'd3))) begin
        ap_phi_mux_r_use_direct_phi_fu_616_p12 = 1'd1;
    end else begin
        ap_phi_mux_r_use_direct_phi_fu_616_p12 = ap_phi_reg_pp0_iter5_r_use_direct_reg_612;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bm_in_0_ce0_local = 1'b1;
    end else begin
        bm_in_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bm_in_4_ce0_local = 1'b1;
    end else begin
        bm_in_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bnt_ce0_local = 1'b1;
    end else begin
        bnt_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        rq_blk_n = rq_full_n;
    end else begin
        rq_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        rq_write = 1'b1;
    end else begin
        rq_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if (((tmp_10_reg_1625 == 2'd3) & (icmp_ln10_reg_1664 == 1'd0))) begin
            src_address0_local = zext_ln10_fu_984_p1;
        end else if ((1'b1 == ap_condition_685)) begin
            src_address0_local = zext_ln16_1_fu_1114_p1;
        end else if ((1'b1 == ap_condition_677)) begin
            src_address0_local = zext_ln15_fu_1091_p1;
        end else if ((1'b1 == ap_condition_668)) begin
            src_address0_local = zext_ln23_1_fu_1056_p1;
        end else if ((1'b1 == ap_condition_655)) begin
            src_address0_local = zext_ln22_fu_1031_p1;
        end else begin
            src_address0_local = 'bx;
        end
    end else begin
        src_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((1'b1 == ap_condition_685)) begin
            src_address1_local = zext_ln16_fu_1100_p1;
        end else if ((1'b1 == ap_condition_668)) begin
            src_address1_local = zext_ln23_fu_1041_p1;
        end else begin
            src_address1_local = 'bx;
        end
    end else begin
        src_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (sel_tmp5_i_reg_1753 == 2'd2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_10_reg_1625 == 2'd0) & (icmp_ln10_reg_1664 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (sel_tmp_i_reg_1731 == 2'd2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_10_reg_1625 == 2'd2) & (icmp_ln10_reg_1664 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (((sel_tmp5_i_reg_1753 == 2'd1) & (tmp_10_reg_1625 == 2'd0) & (icmp_ln10_reg_1664 == 1'd0)) | ((sel_tmp5_i_reg_1753 == 2'd0) & (tmp_10_reg_1625 == 2'd0) & (icmp_ln10_reg_1664 == 1'd0)))) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (((sel_tmp_i_reg_1731 == 2'd1) & (tmp_10_reg_1625 == 2'd2) & (icmp_ln10_reg_1664 == 1'd0)) | ((sel_tmp_i_reg_1731 == 2'd0) & (tmp_10_reg_1625 == 2'd2) & (icmp_ln10_reg_1664 == 1'd0)))) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_10_reg_1625 == 2'd3) & (icmp_ln10_reg_1664 == 1'd0)))) begin
        src_ce0_local = 1'b1;
    end else begin
        src_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (((sel_tmp5_i_reg_1753 == 2'd1) & (tmp_10_reg_1625 == 2'd0) & (icmp_ln10_reg_1664 == 1'd0)) | ((sel_tmp5_i_reg_1753 == 2'd0) & (tmp_10_reg_1625 == 2'd0) & (icmp_ln10_reg_1664 == 1'd0)))) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (((sel_tmp_i_reg_1731 == 2'd1) & (tmp_10_reg_1625 == 2'd2) & (icmp_ln10_reg_1664 == 1'd0)) | ((sel_tmp_i_reg_1731 == 2'd0) & (tmp_10_reg_1625 == 2'd2) & (icmp_ln10_reg_1664 == 1'd0)))))) begin
        src_ce1_local = 1'b1;
    end else begin
        src_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1312)) begin
        if ((tmp_10_reg_1625 == 2'd0)) begin
            zetas39c_address0_local = zext_ln18_fu_1305_p1;
        end else if ((tmp_10_reg_1625 == 2'd2)) begin
            zetas39c_address0_local = zext_ln25_fu_1246_p1;
        end else begin
            zetas39c_address0_local = 'bx;
        end
    end else begin
        zetas39c_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln10_reg_1664_pp0_iter2_reg == 1'd0) & (tmp_10_reg_1625 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln10_reg_1664_pp0_iter2_reg == 1'd0) & (tmp_10_reg_1625 == 2'd2)))) begin
        zetas39c_ce0_local = 1'b1;
    end else begin
        zetas39c_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        zetas39c_ce1_local = 1'b1;
    end else begin
        zetas39c_ce1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a0_fu_1439_p2 = (zext_ln40_fu_1431_p1 + zext_ln40_1_fu_1435_p1);

assign a1_fu_1456_p2 = (a0_fu_1439_p2 + zext_ln40_2_fu_1452_p1);

assign a2_fu_1473_p2 = (a1_fu_1456_p2 + zext_ln40_3_fu_1469_p1);

assign a_fu_1223_p2 = {{src_q0[23:12]}};

assign a_fu_1223_p4 = src_q0[11:0];

assign a_fu_1223_p6 = {{src_q0[23:12]}};

assign a_fu_1223_p7 = 'bx;

assign add_ln10_fu_759_p2 = (n_fu_198 + 8'd1);

assign add_ln16_1_fu_1105_p2 = (tmp_9_reg_1619 + prev_reg_1747);

assign add_ln16_2_fu_1109_p2 = (add_ln16_1_fu_1105_p2 + trunc_ln10_2_reg_1674);

assign add_ln16_fu_1096_p2 = (prev_reg_1747 + trunc_ln10_2_reg_1674);

assign add_ln18_fu_1301_p2 = (trunc_ln10_reg_1668_pp0_iter2_reg + tmp_8_reg_1607);

assign add_ln22_fu_1026_p2 = (trunc_ln10_1_fu_988_p1 + trunc_ln10_2_reg_1674);

assign add_ln23_1_fu_1046_p2 = (prevlen_i_read_reg_1631 + lane_reg_1725);

assign add_ln23_2_fu_1050_p2 = (add_ln23_1_fu_1046_p2 + trunc_ln10_1_fu_988_p1);

assign add_ln23_fu_1036_p2 = (trunc_ln10_1_fu_988_p1 + lane_reg_1725);

assign add_ln50_6_fu_1151_p2 = ($signed(zetas39c_q1) + $signed(12'd3329));

assign add_ln54_fu_1403_p2 = (trunc_ln54_fu_1399_p1 + 12'd767);

assign add_ln58_fu_1373_p2 = ($signed(trunc_ln58_fu_1369_p1) + $signed(12'd3329));

assign ai_fu_992_p1 = n_5_reg_1657[6:0];

assign and_ln10_fu_935_p2 = (xor_ln15_fu_930_p2 & trunc_ln10_3_fu_783_p1);

assign and_ln23_fu_871_p2 = (xor_ln22_fu_866_p2 & icmp_ln23_fu_848_p2);

assign ant_address0 = ant_address0_local;

assign ant_ce0 = ant_ce0_local;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter5));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter5));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter5));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_pp0_stage0_iter5 = (rq_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_1295 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_10_reg_1625 == 2'd2) & (icmp_ln10_reg_1664 == 1'd0));
end

always @ (*) begin
    ap_condition_1308 = ((icmp_ln10_fu_753_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_10_reg_1625 == 2'd0));
end

always @ (*) begin
    ap_condition_1312 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln10_reg_1664_pp0_iter2_reg == 1'd0));
end

always @ (*) begin
    ap_condition_276 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_367 = ((icmp_ln10_fu_753_p2 == 1'd0) & (tmp_7_reg_1596 == 2'd0) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1));
end

always @ (*) begin
    ap_condition_390 = ((icmp_ln10_fu_753_p2 == 1'd0) & (tmp_7_reg_1596 == 2'd2) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1));
end

always @ (*) begin
    ap_condition_447 = ((tmp_6_reg_1592 == 1'd1) & (tmp_10_reg_1625 == 2'd1) & (icmp_ln10_reg_1664_pp0_iter3_reg == 1'd0));
end

always @ (*) begin
    ap_condition_450 = (((tmp_7_reg_1596 == 2'd1) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1) & (icmp_ln10_reg_1664 == 1'd0)) | ((tmp_7_reg_1596 == 2'd0) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1) & (icmp_ln10_reg_1664 == 1'd0)));
end

always @ (*) begin
    ap_condition_455 = (((tmp_7_reg_1596 == 2'd2) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1) & (icmp_ln10_reg_1664 == 1'd0)) | ((tmp_7_reg_1596 == 2'd3) & (tmp_6_reg_1592 == 1'd0) & (tmp_10_reg_1625 == 2'd1) & (icmp_ln10_reg_1664 == 1'd0)));
end

always @ (*) begin
    ap_condition_655 = ((sel_tmp_i_reg_1731 == 2'd2) & (tmp_10_reg_1625 == 2'd2) & (icmp_ln10_reg_1664 == 1'd0));
end

always @ (*) begin
    ap_condition_668 = (((sel_tmp_i_reg_1731 == 2'd1) & (tmp_10_reg_1625 == 2'd2) & (icmp_ln10_reg_1664 == 1'd0)) | ((sel_tmp_i_reg_1731 == 2'd0) & (tmp_10_reg_1625 == 2'd2) & (icmp_ln10_reg_1664 == 1'd0)));
end

always @ (*) begin
    ap_condition_677 = ((sel_tmp5_i_reg_1753 == 2'd2) & (tmp_10_reg_1625 == 2'd0) & (icmp_ln10_reg_1664 == 1'd0));
end

always @ (*) begin
    ap_condition_685 = (((sel_tmp5_i_reg_1753 == 2'd1) & (tmp_10_reg_1625 == 2'd0) & (icmp_ln10_reg_1664 == 1'd0)) | ((sel_tmp5_i_reg_1753 == 2'd0) & (tmp_10_reg_1625 == 2'd0) & (icmp_ln10_reg_1664 == 1'd0)));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_phi_reg_pp0_iter0_ai_2_i_i_reg_455 = 'bx;

assign ap_phi_reg_pp0_iter0_ai_2_ph_i_i_reg_464 = 'bx;

assign ap_phi_reg_pp0_iter0_r_a_3_reg_493 = 'bx;

assign ap_phi_reg_pp0_iter0_r_addr_3_reg_574 = 'bx;

assign ap_phi_reg_pp0_iter0_r_aux_2_reg_529 = 'bx;

assign ap_phi_reg_pp0_iter0_r_b_3_reg_511 = 'bx;

assign ap_phi_reg_pp0_iter0_r_direct_product_1_reg_551 = 'bx;

assign ap_phi_reg_pp0_iter0_r_tag_4_reg_591 = 'bx;

assign ap_phi_reg_pp0_iter0_r_use_direct_reg_612 = 'bx;

assign ap_phi_reg_pp0_iter4_r_tag_3_i_i_reg_473 = 'bx;

assign ap_phi_reg_pp0_iter4_r_tag_3_ph_i_i_reg_483 = 'bx;

assign ap_ready = ap_ready_sig;

assign b_fu_1204_p2 = src_q0[11:0];

assign b_fu_1204_p4 = src_q1[11:0];

assign b_fu_1204_p6 = {{src_q1[23:12]}};

assign b_fu_1204_p7 = 'bx;

assign bi_i_fu_804_p4 = {{n_fu_198[6:1]}};

assign biw_fu_820_p3 = {{bi_i_fu_804_p4}, {xor_ln31_fu_814_p2}};

assign bm_in_0_address0 = zext_ln36_1_fu_842_p1;

assign bm_in_0_ce0 = bm_in_0_ce0_local;

assign bm_in_4_address0 = zext_ln36_1_fu_842_p1;

assign bm_in_4_ce0 = bm_in_4_ce0_local;

assign bnt_address0 = zext_ln35_fu_828_p1;

assign bnt_ce0 = bnt_ce0_local;

assign d_fu_1355_p2 = (zext_ln58_fu_1349_p1 - zext_ln58_1_fu_1352_p1);

assign direct_fu_1518_p2 = (a2_reg_1904 + zext_ln41_fu_1515_p1);

assign grp_fu_636_p2 = ((offset_fu_210 == sext_ln19_reg_1647) ? 1'b1 : 1'b0);

assign grp_fu_640_p2 = (block_fu_214 + 32'd1);

assign grp_fu_645_p2 = (offset_fu_210 + 32'd1);

assign grp_fu_650_p3 = ((grp_fu_636_p2[0:0] == 1'b1) ? 32'd0 : grp_fu_645_p2);

assign grp_fu_658_p3 = ((grp_fu_636_p2[0:0] == 1'b1) ? grp_fu_640_p2 : block_fu_214);

assign grp_fu_665_p3 = {{src_q0[23:12]}};

assign grp_fu_681_p3 = zetas39c_q0[32'd11];

assign grp_fu_689_p2 = ($signed(zetas39c_q0) + $signed(12'd3329));

assign grp_fu_695_p3 = ((grp_fu_681_p3[0:0] == 1'b1) ? grp_fu_689_p2 : zetas39c_q0);

assign icmp_ln10_fu_753_p2 = ((n_fu_198 == 8'd128) ? 1'b1 : 1'b0);

assign icmp_ln23_fu_848_p2 = (($signed(offset_fu_210) < $signed(zext_ln21_reg_1652)) ? 1'b1 : 1'b0);

assign icmp_ln37_fu_1165_p2 = ((z_fu_1157_p3 != 12'd0) ? 1'b1 : 1'b0);

assign icmp_ln54_fu_1393_p2 = ((s_fu_1387_p2 > 13'd3328) ? 1'b1 : 1'b0);

assign j_fu_1087_p2 = (current_reg_1742 + trunc_ln10_4_reg_1681);

assign lane_2_fu_800_p1 = n_fu_198[0:0];

assign lane_fu_858_p3 = ((icmp_ln23_fu_848_p2[0:0] == 1'b1) ? trunc_ln10_2_fu_779_p1 : sub_ln23_fu_853_p2);

assign len_cast11_i_i_cast_fu_709_p1 = len_cast11_i_i;

assign or_ln48_5_i_fu_1524_p10 = {{{{{{{{{ap_phi_mux_r_use_direct_phi_fu_616_p12}, {tmp_10_reg_1625}}, {ap_phi_mux_r_tag_4_phi_fu_595_p12}}, {ap_phi_mux_r_addr_3_phi_fu_577_p12}}, {1'd0}}, {ap_phi_mux_r_direct_product_1_phi_fu_555_p12}}, {ap_phi_mux_r_aux_2_phi_fu_533_p12}}, {ap_phi_mux_r_b_3_phi_fu_514_p12}}, {ap_phi_mux_r_a_3_phi_fu_496_p12}};

assign pair_base_1_fu_1070_p2 = (pair_base_fu_202 + len_cast11_i_i_cast_reg_1637);

assign pair_base_2_fu_1075_p3 = ((icmp_ln26_reg_1737[0:0] == 1'b1) ? pair_base_1_fu_1070_p2 : pair_base_fu_202);

assign prev_fu_924_p2 = (trunc_ln14_1_i_fu_907_p4 - select_ln16_fu_917_p3);

assign r_a_2_fu_1019_p3 = ((lane_2_reg_1687[0:0] == 1'b1) ? bm_in_4_q0 : bm_in_0_q0);

assign r_addr_2_fu_1065_p2 = (trunc_ln25_fu_1061_p1 + trunc_ln10_4_reg_1681);

assign r_addr_fu_1119_p2 = (n_5_reg_1657 + tmp_reg_1587);

assign r_aux_1_fu_1409_p3 = ((icmp_ln54_fu_1393_p2[0:0] == 1'b1) ? add_ln54_fu_1403_p2 : trunc_ln54_fu_1399_p1);

assign r_aux_fu_1263_p2 = src_q0[11:0];

assign r_aux_fu_1263_p4 = {{src_q1[23:12]}};

assign r_aux_fu_1263_p6 = src_q1[11:0];

assign r_aux_fu_1263_p7 = 'bx;

assign r_b_1_fu_1379_p3 = ((tmp_14_fu_1361_p3[0:0] == 1'b1) ? add_ln58_fu_1373_p2 : trunc_ln58_fu_1369_p1);

assign r_b_2_fu_1185_p3 = ((lane_2_reg_1687_pp0_iter2_reg[0:0] == 1'b1) ? select_ln37_fu_1177_p3 : z_fu_1157_p3);

assign r_b_fu_1282_p2 = {{src_q0[23:12]}};

assign r_b_fu_1282_p4 = {{src_q0[23:12]}};

assign r_b_fu_1282_p6 = src_q0[11:0];

assign r_b_fu_1282_p7 = 'bx;

assign r_tag_2_fu_1329_p3 = ((lane_2_reg_1687_pp0_iter3_reg[0:0] == 1'b1) ? 2'd3 : 2'd2);

assign r_tag_3_fu_1321_p3 = ((lane_2_reg_1687_pp0_iter3_reg[0:0] == 1'b1) ? 3'd5 : 3'd4);

assign r_tag_fu_1507_p3 = ((lane_2_reg_1687_pp0_iter4_reg[0:0] == 1'b1) ? 4'd9 : 4'd8);

assign rq_din = or_ln48_5_i_fu_1524_p10;

assign s_fu_1387_p2 = (zext_ln58_fu_1349_p1 + zext_ln58_1_fu_1352_p1);

assign sel_tmp5_i_fu_941_p3 = {{icmp_ln15_i_read_reg_1613}, {and_ln10_fu_935_p2}};

assign sel_tmp_i_fu_877_p3 = {{icmp_ln22_i_read_reg_1601}, {and_ln23_fu_871_p2}};

assign select_ln12_cast_i_cast_fu_1341_p3 = ((lane_2_reg_1687_pp0_iter3_reg[0:0] == 1'b1) ? 3'd7 : 3'd6);

assign select_ln16_fu_917_p3 = ((trunc_ln10_3_fu_783_p1[0:0] == 1'b1) ? tmp_9_reg_1619 : 7'd0);

assign select_ln37_fu_1177_p3 = ((icmp_ln37_fu_1165_p2[0:0] == 1'b1) ? sub_ln37_fu_1171_p2 : 12'd0);

assign sext_ln19_fu_717_p1 = $signed(add_ln19_i);

assign shl_ln1_i_fu_1417_p3 = {{x_11_reg_1885}, {10'd0}};

assign shl_ln40_1_i_fu_1424_p3 = {{x_11_reg_1885}, {8'd0}};

assign shl_ln40_2_i_fu_1445_p3 = {{x_11_reg_1885}, {7'd0}};

assign shl_ln40_3_i_fu_1462_p3 = {{x_11_reg_1885}, {5'd0}};

assign src_address0 = src_address0_local;

assign src_address1 = src_address1_local;

assign src_ce0 = src_ce0_local;

assign src_ce1 = src_ce1_local;

assign start_1_fu_948_p2 = (start_fu_206 + zext_ln10_i_cast_reg_1642);

assign start_2_fu_953_p3 = ((grp_fu_636_p2[0:0] == 1'b1) ? start_1_fu_948_p2 : start_fu_206);

assign sub_ln23_fu_853_p2 = (trunc_ln10_2_fu_779_p1 - prevlen_i_read_reg_1631);

assign sub_ln25_fu_1242_p2 = (tmp_8_reg_1607 - trunc_ln10_reg_1668_pp0_iter2_reg);

assign sub_ln37_fu_1171_p2 = ($signed(12'd3329) - $signed(z_fu_1157_p3));

assign tmp_14_fu_1361_p3 = d_fu_1355_p2[32'd12];

assign tmp_15_fu_1143_p3 = zetas39c_q1[32'd11];

assign trunc_ln10_1_fu_988_p1 = pair_base_fu_202[6:0];

assign trunc_ln10_2_fu_779_p1 = offset_fu_210[6:0];

assign trunc_ln10_3_fu_783_p1 = block_fu_214[0:0];

assign trunc_ln10_4_fu_787_p1 = offset_fu_210[7:0];

assign trunc_ln10_fu_775_p1 = block_fu_214[6:0];

assign trunc_ln14_1_i_fu_907_p4 = {{start_fu_206[7:1]}};

assign trunc_ln25_fu_1061_p1 = pair_base_fu_202[7:0];

assign trunc_ln54_fu_1399_p1 = s_fu_1387_p2[11:0];

assign trunc_ln58_fu_1369_p1 = d_fu_1355_p2[11:0];

assign trunc_ln62_6_fu_1131_p1 = ant_q0[11:0];

assign trunc_ln62_7_fu_1490_p1 = x_21_reg_1759_pp0_iter4_reg[11:0];

assign x_11_fu_1314_p3 = ((tmp_11_reg_1835[0:0] == 1'b1) ? grp_fu_665_p3 : x_9_fu_1310_p1);

assign x_9_fu_1310_p1 = src_q0[11:0];

assign xor_ln15_fu_930_p2 = (icmp_ln15_i_read_reg_1613 ^ 1'd1);

assign xor_ln22_fu_866_p2 = (icmp_ln22_i_read_reg_1601 ^ 1'd1);

assign xor_ln31_fu_814_p2 = (lane_2_fu_800_p1 ^ 1'd1);

assign z_fu_1157_p3 = ((tmp_15_fu_1143_p3[0:0] == 1'b1) ? add_ln50_6_fu_1151_p2 : zetas39c_q1);

assign zetas39c_address1 = zext_ln36_fu_1014_p1;

assign zext_ln10_fu_984_p1 = n_5_reg_1657;

assign zext_ln10_i_cast_fu_713_p1 = zext_ln10_i;

assign zext_ln12_1_fu_1494_p1 = r_tag_3_ph_i_i_reg_483;

assign zext_ln12_2_fu_1485_p1 = r_tag_3_i_i_reg_473;

assign zext_ln12_fu_1337_p1 = lane_2_reg_1687_pp0_iter3_reg;

assign zext_ln15_fu_1091_p1 = j_fu_1087_p2;

assign zext_ln16_1_fu_1114_p1 = add_ln16_2_fu_1109_p2;

assign zext_ln16_fu_1100_p1 = add_ln16_fu_1096_p2;

assign zext_ln18_fu_1305_p1 = add_ln18_fu_1301_p2;

assign zext_ln21_fu_721_p1 = prevlen_i;

assign zext_ln22_fu_1031_p1 = add_ln22_fu_1026_p2;

assign zext_ln23_1_fu_1056_p1 = add_ln23_2_fu_1050_p2;

assign zext_ln23_fu_1041_p1 = add_ln23_fu_1036_p2;

assign zext_ln25_fu_1246_p1 = sub_ln25_fu_1242_p2;

assign zext_ln28_fu_1479_p1 = bi_i_reg_1698_pp0_iter4_reg;

assign zext_ln35_1_fu_1002_p1 = ap_phi_mux_ai_2_ph_i_i_phi_fu_467_p4;

assign zext_ln35_2_fu_997_p1 = ap_phi_mux_ai_2_i_i_phi_fu_458_p4;

assign zext_ln35_fu_828_p1 = biw_fu_820_p3;

assign zext_ln36_1_fu_842_p1 = bi_i_fu_804_p4;

assign zext_ln36_fu_1014_p1 = zext_ln36_i_cast_fu_1007_p3;

assign zext_ln36_i_cast_fu_1007_p3 = {{1'd1}, {bi_i_reg_1698}};

assign zext_ln40_1_fu_1435_p1 = shl_ln40_1_i_fu_1424_p3;

assign zext_ln40_2_fu_1452_p1 = shl_ln40_2_i_fu_1445_p3;

assign zext_ln40_3_fu_1469_p1 = shl_ln40_3_i_fu_1462_p3;

assign zext_ln40_fu_1431_p1 = shl_ln1_i_fu_1417_p3;

assign zext_ln41_fu_1515_p1 = x_11_reg_1885_pp0_iter4_reg;

assign zext_ln58_1_fu_1352_p1 = b_reg_1855;

assign zext_ln58_fu_1349_p1 = a_reg_1860;

always @ (posedge ap_clk) begin
    len_cast11_i_i_cast_reg_1637[31:8] <= 24'b000000000000000000000000;
    zext_ln10_i_cast_reg_1642[31:9] <= 23'b00000000000000000000000;
    zext_ln21_reg_1652[31:7] <= 25'b0000000000000000000000000;
    a2_reg_1904[4:0] <= 5'b00000;
end

endmodule //mlkem_poly_mul256_v39e_true_one_dsp_issue39d_Pipeline_issue39d_loop
