// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mlkem_poly_mul256_v39e_true_one_dsp_mlkem_poly_mul256_v39e_true_one_dsp_Pipeline_load_a39d (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a_address0,
        a_ce0,
        a_q0,
        a_address1,
        a_ce1,
        a_q1,
        ping_address0,
        ping_ce0,
        ping_we0,
        ping_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] a_address0;
output   a_ce0;
input  [15:0] a_q0;
output  [7:0] a_address1;
output   a_ce1;
input  [15:0] a_q1;
output  [6:0] ping_address0;
output   ping_ce0;
output   ping_we0;
output  [23:0] ping_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln92_fu_110_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln92_fu_122_p1;
reg   [63:0] zext_ln92_reg_259;
reg   [63:0] zext_ln92_reg_259_pp0_iter1_reg;
wire   [11:0] l_fu_187_p3;
reg   [11:0] l_reg_274;
wire   [11:0] h_fu_233_p3;
reg   [11:0] h_reg_279;
wire    ap_block_pp0_stage0;
wire   [63:0] add_ln94_cast_cast_cast_fu_139_p1;
reg   [7:0] i_fu_60;
wire   [7:0] add_ln92_fu_116_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_i_4;
reg    a_ce1_local;
reg    a_ce0_local;
reg    ping_we0_local;
wire   [23:0] x_fu_241_p3;
reg    ping_ce0_local;
wire   [6:0] trunc_ln94_fu_127_p1;
wire   [7:0] add_ln94_cast_cast_fu_131_p3;
wire   [0:0] tmp_fu_149_p3;
wire   [15:0] y_6_fu_157_p2;
wire   [15:0] y_7_fu_163_p3;
wire   [11:0] trunc_ln50_fu_177_p1;
wire   [0:0] icmp_ln50_1_fu_171_p2;
wire   [11:0] add_ln50_fu_181_p2;
wire   [0:0] tmp_5_fu_195_p3;
wire   [15:0] y_9_fu_203_p2;
wire   [15:0] y_10_fu_209_p3;
wire   [11:0] trunc_ln50_2_fu_223_p1;
wire   [0:0] icmp_ln50_fu_217_p2;
wire   [11:0] add_ln50_2_fu_227_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 i_fu_60 = 8'd0;
#0 ap_done_reg = 1'b0;
end

mlkem_poly_mul256_v39e_true_one_dsp_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln92_fu_110_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_60 <= add_ln92_fu_116_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_60 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        h_reg_279 <= h_fu_233_p3;
        l_reg_274 <= l_fu_187_p3;
        zext_ln92_reg_259[7 : 0] <= zext_ln92_fu_122_p1[7 : 0];
        zext_ln92_reg_259_pp0_iter1_reg[7 : 0] <= zext_ln92_reg_259[7 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_ce0_local = 1'b1;
    end else begin
        a_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_ce1_local = 1'b1;
    end else begin
        a_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln92_fu_110_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_4 = 8'd0;
    end else begin
        ap_sig_allocacmp_i_4 = i_fu_60;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ping_ce0_local = 1'b1;
    end else begin
        ping_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ping_we0_local = 1'b1;
    end else begin
        ping_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_address0 = add_ln94_cast_cast_cast_fu_139_p1;

assign a_address1 = zext_ln92_fu_122_p1;

assign a_ce0 = a_ce0_local;

assign a_ce1 = a_ce1_local;

assign add_ln50_2_fu_227_p2 = (trunc_ln50_2_fu_223_p1 + 12'd767);

assign add_ln50_fu_181_p2 = (trunc_ln50_fu_177_p1 + 12'd767);

assign add_ln92_fu_116_p2 = (ap_sig_allocacmp_i_4 + 8'd1);

assign add_ln94_cast_cast_cast_fu_139_p1 = add_ln94_cast_cast_fu_131_p3;

assign add_ln94_cast_cast_fu_131_p3 = {{1'd1}, {trunc_ln94_fu_127_p1}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign h_fu_233_p3 = ((icmp_ln50_fu_217_p2[0:0] == 1'b1) ? add_ln50_2_fu_227_p2 : trunc_ln50_2_fu_223_p1);

assign icmp_ln50_1_fu_171_p2 = (($signed(y_7_fu_163_p3) > $signed(16'd3328)) ? 1'b1 : 1'b0);

assign icmp_ln50_fu_217_p2 = (($signed(y_10_fu_209_p3) > $signed(16'd3328)) ? 1'b1 : 1'b0);

assign icmp_ln92_fu_110_p2 = ((ap_sig_allocacmp_i_4 == 8'd128) ? 1'b1 : 1'b0);

assign l_fu_187_p3 = ((icmp_ln50_1_fu_171_p2[0:0] == 1'b1) ? add_ln50_fu_181_p2 : trunc_ln50_fu_177_p1);

assign ping_address0 = zext_ln92_reg_259_pp0_iter1_reg;

assign ping_ce0 = ping_ce0_local;

assign ping_d0 = x_fu_241_p3;

assign ping_we0 = ping_we0_local;

assign tmp_5_fu_195_p3 = a_q0[32'd15];

assign tmp_fu_149_p3 = a_q1[32'd15];

assign trunc_ln50_2_fu_223_p1 = y_10_fu_209_p3[11:0];

assign trunc_ln50_fu_177_p1 = y_7_fu_163_p3[11:0];

assign trunc_ln94_fu_127_p1 = ap_sig_allocacmp_i_4[6:0];

assign x_fu_241_p3 = {{h_reg_279}, {l_reg_274}};

assign y_10_fu_209_p3 = ((tmp_5_fu_195_p3[0:0] == 1'b1) ? y_9_fu_203_p2 : a_q0);

assign y_6_fu_157_p2 = (a_q1 + 16'd3329);

assign y_7_fu_163_p3 = ((tmp_fu_149_p3[0:0] == 1'b1) ? y_6_fu_157_p2 : a_q1);

assign y_9_fu_203_p2 = (a_q0 + 16'd3329);

assign zext_ln92_fu_122_p1 = ap_sig_allocacmp_i_4;

always @ (posedge ap_clk) begin
    zext_ln92_reg_259[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln92_reg_259_pp0_iter1_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
end

endmodule //mlkem_poly_mul256_v39e_true_one_dsp_mlkem_poly_mul256_v39e_true_one_dsp_Pipeline_load_a39d
