// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1 ns / 1 ps
(* DowngradeIPIdentifiedWarnings="yes" *) module mlkem_poly_mul256_v39e_true_one_dsp_dummy_1_RAM_1P_LUTRAM_0R0W (
    address0, ce0,
    d0, we0,
    reset, clk);

parameter DataWidth = 12;
parameter AddressWidth = 6;
parameter AddressRange = 64;

input [AddressWidth-1:0] address0;
input ce0;
input [DataWidth-1:0] d0;
input we0;
input reset;
input clk;

(* ram_style = "distributed" *) reg [DataWidth-1:0] ram[0:AddressRange-1];


always @(posedge clk)
begin
    if (ce0)
    begin
        if (we0)
            ram[address0] <= d0;
    end
end


endmodule

