// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mlkem_poly_mul256_v39e_true_one_dsp_pe39c (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        rq_dout,
        rq_empty_n,
        rq_read,
        rq_num_data_valid,
        rq_fifo_cap,
        rs_din,
        rs_full_n,
        rs_write,
        rs_num_data_valid,
        rs_fifo_cap,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [75:0] rq_dout;
input   rq_empty_n;
output   rq_read;
input  [2:0] rq_num_data_valid;
input  [2:0] rq_fifo_cap;
output  [38:0] rs_din;
input   rs_full_n;
output   rs_write;
input  [31:0] rs_num_data_valid;
input  [31:0] rs_fifo_cap;
output   start_out;
output   start_write;

reg ap_idle;
reg rq_read;
reg rs_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln130_fu_145_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    rq_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    rs_blk_n;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] r_use_direct_reg_391;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [0:0] r_use_direct_reg_391_pp0_iter2_reg;
reg   [11:0] r_aux_reg_396;
reg   [11:0] r_aux_reg_396_pp0_iter2_reg;
reg   [11:0] r_aux_reg_396_pp0_iter3_reg;
reg   [11:0] r_aux_reg_396_pp0_iter4_reg;
reg   [11:0] r_aux_reg_396_pp0_iter5_reg;
reg   [11:0] r_aux_reg_396_pp0_iter6_reg;
reg   [11:0] r_aux_reg_396_pp0_iter7_reg;
reg   [11:0] r_aux_reg_396_pp0_iter8_reg;
reg   [11:0] r_aux_reg_396_pp0_iter9_reg;
reg   [11:0] r_aux_reg_396_pp0_iter10_reg;
reg   [11:0] r_aux_reg_396_pp0_iter11_reg;
reg   [23:0] r_direct_product_reg_401;
reg   [23:0] r_direct_product_reg_401_pp0_iter2_reg;
reg   [0:0] tmp_3_reg_416;
reg   [0:0] tmp_3_reg_416_pp0_iter2_reg;
reg   [0:0] tmp_3_reg_416_pp0_iter3_reg;
reg   [0:0] tmp_3_reg_416_pp0_iter4_reg;
reg   [0:0] tmp_3_reg_416_pp0_iter5_reg;
reg   [0:0] tmp_3_reg_416_pp0_iter6_reg;
reg   [0:0] tmp_3_reg_416_pp0_iter7_reg;
reg   [0:0] tmp_3_reg_416_pp0_iter8_reg;
reg   [0:0] tmp_3_reg_416_pp0_iter9_reg;
reg   [0:0] tmp_3_reg_416_pp0_iter10_reg;
reg   [0:0] tmp_3_reg_416_pp0_iter11_reg;
reg   [13:0] tmp_1_reg_421;
reg   [13:0] tmp_1_reg_421_pp0_iter2_reg;
reg   [13:0] tmp_1_reg_421_pp0_iter3_reg;
reg   [13:0] tmp_1_reg_421_pp0_iter4_reg;
reg   [13:0] tmp_1_reg_421_pp0_iter5_reg;
reg   [13:0] tmp_1_reg_421_pp0_iter6_reg;
reg   [13:0] tmp_1_reg_421_pp0_iter7_reg;
reg   [13:0] tmp_1_reg_421_pp0_iter8_reg;
reg   [13:0] tmp_1_reg_421_pp0_iter9_reg;
reg   [13:0] tmp_1_reg_421_pp0_iter10_reg;
reg   [13:0] tmp_1_reg_421_pp0_iter11_reg;
wire   [7:0] l1_fu_242_p1;
reg   [7:0] l1_reg_426;
reg   [15:0] h1_reg_431;
reg   [15:0] h1_reg_431_pp0_iter4_reg;
reg   [15:0] h1_reg_431_pp0_iter5_reg;
wire   [11:0] grp_fu_257_p2;
reg   [11:0] m1_reg_441;
wire   [16:0] grp_fu_269_p2;
reg   [16:0] k1_reg_456;
reg   [16:0] k1_reg_456_pp0_iter8_reg;
reg   [16:0] k1_reg_456_pp0_iter9_reg;
reg   [16:0] k1_reg_456_pp0_iter10_reg;
wire   [7:0] l2_fu_275_p1;
reg   [7:0] l2_reg_461;
reg   [7:0] h2_reg_466;
reg   [7:0] h2_reg_466_pp0_iter8_reg;
reg   [7:0] h2_reg_466_pp0_iter9_reg;
wire   [11:0] grp_fu_292_p2;
reg   [11:0] m2_reg_476;
wire   [11:0] c_fu_363_p3;
reg   [11:0] c_reg_491;
reg   [7:0] n_fu_120;
wire   [7:0] n_4_fu_151_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_n_3;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_01001_grp1;
wire   [11:0] r_a_fu_162_p1;
wire   [11:0] r_b_fu_174_p4;
wire   [11:0] grp_fu_212_p0;
wire   [11:0] grp_fu_212_p1;
wire   [23:0] grp_fu_212_p2;
wire   [23:0] p_fu_236_p3;
wire   [7:0] grp_fu_257_p0;
wire   [4:0] grp_fu_257_p1;
wire   [16:0] grp_fu_269_p0;
wire   [16:0] grp_fu_269_p1;
wire   [7:0] grp_fu_292_p0;
wire   [4:0] grp_fu_292_p1;
wire   [12:0] grp_fu_304_p0;
wire   [12:0] grp_fu_304_p1;
wire   [12:0] grp_fu_304_p2;
wire   [0:0] icmp_ln149_fu_321_p2;
wire   [11:0] select_ln149_fu_327_p3;
wire   [11:0] trunc_ln149_fu_310_p1;
wire   [0:0] tmp_2_fu_341_p3;
wire   [11:0] c_3_fu_349_p2;
wire   [0:0] tmp_fu_314_p3;
wire   [11:0] c_2_fu_335_p2;
wire   [11:0] c_4_fu_355_p3;
reg    grp_fu_212_ce;
reg    grp_fu_257_ce;
reg    grp_fu_269_ce;
reg    grp_fu_292_ce;
reg    grp_fu_304_ce;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_done_sig;
wire   [23:0] grp_fu_212_p00;
wire   [23:0] grp_fu_212_p10;
wire   [11:0] grp_fu_257_p00;
wire   [11:0] grp_fu_292_p00;
reg    ap_condition_247;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 n_fu_120 = 8'd0;
end

mlkem_poly_mul256_v39e_true_one_dsp_mul_12ns_12ns_24_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 24 ))
mul_12ns_12ns_24_3_1_U37(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_212_p0),
    .din1(grp_fu_212_p1),
    .ce(grp_fu_212_ce),
    .dout(grp_fu_212_p2)
);

mlkem_poly_mul256_v39e_true_one_dsp_mul_8ns_5ns_12_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 12 ))
mul_8ns_5ns_12_2_1_U38(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_257_p0),
    .din1(grp_fu_257_p1),
    .ce(grp_fu_257_ce),
    .dout(grp_fu_257_p2)
);

mlkem_poly_mul256_v39e_true_one_dsp_sub_17ns_17ns_17_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
sub_17ns_17ns_17_2_1_U39(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_269_p0),
    .din1(grp_fu_269_p1),
    .ce(grp_fu_269_ce),
    .dout(grp_fu_269_p2)
);

mlkem_poly_mul256_v39e_true_one_dsp_mul_8ns_5ns_12_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 12 ))
mul_8ns_5ns_12_2_1_U40(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_292_p0),
    .din1(grp_fu_292_p1),
    .ce(grp_fu_292_ce),
    .dout(grp_fu_292_p2)
);

mlkem_poly_mul256_v39e_true_one_dsp_sub_13ns_13ns_13_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 13 ))
sub_13ns_13ns_13_2_1_U41(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_304_p0),
    .din1(grp_fu_304_p1),
    .ce(grp_fu_304_ce),
    .dout(grp_fu_304_p2)
);

mlkem_poly_mul256_v39e_true_one_dsp_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_247)) begin
        if ((icmp_ln130_fu_145_p2 == 1'd0)) begin
            n_fu_120 <= n_4_fu_151_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            n_fu_120 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        c_reg_491 <= c_fu_363_p3;
        h1_reg_431 <= {{p_fu_236_p3[23:8]}};
        h1_reg_431_pp0_iter4_reg <= h1_reg_431;
        h1_reg_431_pp0_iter5_reg <= h1_reg_431_pp0_iter4_reg;
        h2_reg_466 <= {{grp_fu_269_p2[15:8]}};
        h2_reg_466_pp0_iter8_reg <= h2_reg_466;
        h2_reg_466_pp0_iter9_reg <= h2_reg_466_pp0_iter8_reg;
        k1_reg_456 <= grp_fu_269_p2;
        k1_reg_456_pp0_iter10_reg <= k1_reg_456_pp0_iter9_reg;
        k1_reg_456_pp0_iter8_reg <= k1_reg_456;
        k1_reg_456_pp0_iter9_reg <= k1_reg_456_pp0_iter8_reg;
        l1_reg_426 <= l1_fu_242_p1;
        l2_reg_461 <= l2_fu_275_p1;
        m1_reg_441 <= grp_fu_257_p2;
        m2_reg_476 <= grp_fu_292_p2;
        r_aux_reg_396_pp0_iter10_reg <= r_aux_reg_396_pp0_iter9_reg;
        r_aux_reg_396_pp0_iter11_reg <= r_aux_reg_396_pp0_iter10_reg;
        r_aux_reg_396_pp0_iter2_reg <= r_aux_reg_396;
        r_aux_reg_396_pp0_iter3_reg <= r_aux_reg_396_pp0_iter2_reg;
        r_aux_reg_396_pp0_iter4_reg <= r_aux_reg_396_pp0_iter3_reg;
        r_aux_reg_396_pp0_iter5_reg <= r_aux_reg_396_pp0_iter4_reg;
        r_aux_reg_396_pp0_iter6_reg <= r_aux_reg_396_pp0_iter5_reg;
        r_aux_reg_396_pp0_iter7_reg <= r_aux_reg_396_pp0_iter6_reg;
        r_aux_reg_396_pp0_iter8_reg <= r_aux_reg_396_pp0_iter7_reg;
        r_aux_reg_396_pp0_iter9_reg <= r_aux_reg_396_pp0_iter8_reg;
        r_direct_product_reg_401_pp0_iter2_reg <= r_direct_product_reg_401;
        r_use_direct_reg_391_pp0_iter2_reg <= r_use_direct_reg_391;
        tmp_1_reg_421_pp0_iter10_reg <= tmp_1_reg_421_pp0_iter9_reg;
        tmp_1_reg_421_pp0_iter11_reg <= tmp_1_reg_421_pp0_iter10_reg;
        tmp_1_reg_421_pp0_iter2_reg <= tmp_1_reg_421;
        tmp_1_reg_421_pp0_iter3_reg <= tmp_1_reg_421_pp0_iter2_reg;
        tmp_1_reg_421_pp0_iter4_reg <= tmp_1_reg_421_pp0_iter3_reg;
        tmp_1_reg_421_pp0_iter5_reg <= tmp_1_reg_421_pp0_iter4_reg;
        tmp_1_reg_421_pp0_iter6_reg <= tmp_1_reg_421_pp0_iter5_reg;
        tmp_1_reg_421_pp0_iter7_reg <= tmp_1_reg_421_pp0_iter6_reg;
        tmp_1_reg_421_pp0_iter8_reg <= tmp_1_reg_421_pp0_iter7_reg;
        tmp_1_reg_421_pp0_iter9_reg <= tmp_1_reg_421_pp0_iter8_reg;
        tmp_3_reg_416_pp0_iter10_reg <= tmp_3_reg_416_pp0_iter9_reg;
        tmp_3_reg_416_pp0_iter11_reg <= tmp_3_reg_416_pp0_iter10_reg;
        tmp_3_reg_416_pp0_iter2_reg <= tmp_3_reg_416;
        tmp_3_reg_416_pp0_iter3_reg <= tmp_3_reg_416_pp0_iter2_reg;
        tmp_3_reg_416_pp0_iter4_reg <= tmp_3_reg_416_pp0_iter3_reg;
        tmp_3_reg_416_pp0_iter5_reg <= tmp_3_reg_416_pp0_iter4_reg;
        tmp_3_reg_416_pp0_iter6_reg <= tmp_3_reg_416_pp0_iter5_reg;
        tmp_3_reg_416_pp0_iter7_reg <= tmp_3_reg_416_pp0_iter6_reg;
        tmp_3_reg_416_pp0_iter8_reg <= tmp_3_reg_416_pp0_iter7_reg;
        tmp_3_reg_416_pp0_iter9_reg <= tmp_3_reg_416_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        r_aux_reg_396 <= {{rq_dout[35:24]}};
        r_direct_product_reg_401 <= {{rq_dout[59:36]}};
        r_use_direct_reg_391 <= rq_dout[32'd74];
        tmp_1_reg_421 <= {{rq_dout[73:60]}};
        tmp_3_reg_416 <= rq_dout[32'd75];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln130_fu_145_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_n_3 = 8'd0;
    end else begin
        ap_sig_allocacmp_n_3 = n_fu_120;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_212_ce = 1'b1;
    end else begin
        grp_fu_212_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_257_ce = 1'b1;
    end else begin
        grp_fu_257_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_269_ce = 1'b1;
    end else begin
        grp_fu_269_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_292_ce = 1'b1;
    end else begin
        grp_fu_292_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_304_ce = 1'b1;
    end else begin
        grp_fu_304_ce = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rq_blk_n = rq_empty_n;
    end else begin
        rq_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rq_read = 1'b1;
    end else begin
        rq_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        rs_blk_n = rs_full_n;
    end else begin
        rs_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        rs_write = 1'b1;
    end else begin
        rs_write = 1'b0;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((ap_done_reg == 1'b1) | ((rs_full_n == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b1)) | ((rq_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((rs_full_n == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b1)) | ((rq_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_done_reg == 1'b1) | ((rs_full_n == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b1)) | ((rq_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((rs_full_n == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b1)) | ((rq_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_condition_247 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign c_2_fu_335_p2 = (select_ln149_fu_327_p3 + trunc_ln149_fu_310_p1);

assign c_3_fu_349_p2 = ($signed(trunc_ln149_fu_310_p1) + $signed(12'd3329));

assign c_4_fu_355_p3 = ((tmp_2_fu_341_p3[0:0] == 1'b1) ? c_3_fu_349_p2 : trunc_ln149_fu_310_p1);

assign c_fu_363_p3 = ((tmp_fu_314_p3[0:0] == 1'b1) ? c_2_fu_335_p2 : c_4_fu_355_p3);

assign grp_fu_212_p0 = grp_fu_212_p00;

assign grp_fu_212_p00 = r_b_fu_174_p4;

assign grp_fu_212_p1 = grp_fu_212_p10;

assign grp_fu_212_p10 = r_a_fu_162_p1;

assign grp_fu_257_p0 = grp_fu_257_p00;

assign grp_fu_257_p00 = l1_reg_426;

assign grp_fu_257_p1 = 12'd13;

assign grp_fu_269_p0 = m1_reg_441;

assign grp_fu_269_p1 = h1_reg_431_pp0_iter5_reg;

assign grp_fu_292_p0 = grp_fu_292_p00;

assign grp_fu_292_p00 = l2_reg_461;

assign grp_fu_292_p1 = 12'd13;

assign grp_fu_304_p0 = m2_reg_476;

assign grp_fu_304_p1 = h2_reg_466_pp0_iter9_reg;

assign icmp_ln130_fu_145_p2 = ((ap_sig_allocacmp_n_3 == 8'd128) ? 1'b1 : 1'b0);

assign icmp_ln149_fu_321_p2 = (($signed(grp_fu_304_p2) > $signed(13'd3072)) ? 1'b1 : 1'b0);

assign l1_fu_242_p1 = p_fu_236_p3[7:0];

assign l2_fu_275_p1 = grp_fu_269_p2[7:0];

assign n_4_fu_151_p2 = (ap_sig_allocacmp_n_3 + 8'd1);

assign p_fu_236_p3 = ((r_use_direct_reg_391_pp0_iter2_reg[0:0] == 1'b1) ? r_direct_product_reg_401_pp0_iter2_reg : grp_fu_212_p2);

assign r_a_fu_162_p1 = rq_dout[11:0];

assign r_b_fu_174_p4 = {{rq_dout[23:12]}};

assign rs_din = {{{{tmp_3_reg_416_pp0_iter11_reg}, {tmp_1_reg_421_pp0_iter11_reg}}, {r_aux_reg_396_pp0_iter11_reg}}, {c_reg_491}};

assign select_ln149_fu_327_p3 = ((icmp_ln149_fu_321_p2[0:0] == 1'b1) ? 12'd1023 : 12'd256);

assign start_out = real_start;

assign tmp_2_fu_341_p3 = grp_fu_304_p2[32'd12];

assign tmp_fu_314_p3 = k1_reg_456_pp0_iter10_reg[32'd16];

assign trunc_ln149_fu_310_p1 = grp_fu_304_p2[11:0];

endmodule //mlkem_poly_mul256_v39e_true_one_dsp_pe39c
