// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mlkem_poly_mul256_v39e_true_one_dsp_write39d (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        rs_dout,
        rs_empty_n,
        rs_read,
        rs_num_data_valid,
        rs_fifo_cap,
        dst_address0,
        dst_ce0,
        dst_we0,
        dst_d0,
        bm_out_0_address0,
        bm_out_0_ce0,
        bm_out_0_we0,
        bm_out_0_d0,
        bm_out_1_address0,
        bm_out_1_ce0,
        bm_out_1_we0,
        bm_out_1_d0,
        bm_out_2_address0,
        bm_out_2_ce0,
        bm_out_2_we0,
        bm_out_2_d0,
        bm_out_3_address0,
        bm_out_3_ce0,
        bm_out_3_we0,
        bm_out_3_d0,
        bm_out_4_address0,
        bm_out_4_ce0,
        bm_out_4_we0,
        bm_out_4_d0,
        bm_out_5_address0,
        bm_out_5_ce0,
        bm_out_5_we0,
        bm_out_5_d0,
        bm_out_6_address0,
        bm_out_6_ce0,
        bm_out_6_we0,
        bm_out_6_d0,
        bm_out_7_address0,
        bm_out_7_ce0,
        bm_out_7_we0,
        bm_out_7_d0,
        bm_final_0_address0,
        bm_final_0_ce0,
        bm_final_0_we0,
        bm_final_0_d0,
        bm_final_1_address0,
        bm_final_1_ce0,
        bm_final_1_we0,
        bm_final_1_d0,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0,
        group_r
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [38:0] rs_dout;
input   rs_empty_n;
output   rs_read;
input  [2:0] rs_num_data_valid;
input  [2:0] rs_fifo_cap;
output  [6:0] dst_address0;
output   dst_ce0;
output   dst_we0;
output  [23:0] dst_d0;
output  [5:0] bm_out_0_address0;
output   bm_out_0_ce0;
output   bm_out_0_we0;
output  [11:0] bm_out_0_d0;
output  [5:0] bm_out_1_address0;
output   bm_out_1_ce0;
output   bm_out_1_we0;
output  [11:0] bm_out_1_d0;
output  [5:0] bm_out_2_address0;
output   bm_out_2_ce0;
output   bm_out_2_we0;
output  [11:0] bm_out_2_d0;
output  [5:0] bm_out_3_address0;
output   bm_out_3_ce0;
output   bm_out_3_we0;
output  [11:0] bm_out_3_d0;
output  [5:0] bm_out_4_address0;
output   bm_out_4_ce0;
output   bm_out_4_we0;
output  [11:0] bm_out_4_d0;
output  [5:0] bm_out_5_address0;
output   bm_out_5_ce0;
output   bm_out_5_we0;
output  [11:0] bm_out_5_d0;
output  [5:0] bm_out_6_address0;
output   bm_out_6_ce0;
output   bm_out_6_we0;
output  [11:0] bm_out_6_d0;
output  [5:0] bm_out_7_address0;
output   bm_out_7_ce0;
output   bm_out_7_we0;
output  [11:0] bm_out_7_d0;
output  [5:0] bm_final_0_address0;
output   bm_final_0_ce0;
output   bm_final_0_we0;
output  [11:0] bm_final_0_d0;
output  [5:0] bm_final_1_address0;
output   bm_final_1_ce0;
output   bm_final_1_we0;
output  [11:0] bm_final_1_d0;
output  [7:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [15:0] output_r_d0;
input  [2:0] group_r;

reg ap_idle;
reg rs_read;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln56_fu_342_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    rs_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg   [0:0] tmp_reg_562;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage0_11001;
wire   [11:0] s_reduced_fu_359_p1;
reg   [11:0] s_reduced_reg_570;
wire   [1:0] s_mode_fu_393_p4;
reg   [1:0] s_mode_reg_579;
reg   [11:0] s_aux_reg_583;
wire   [63:0] zext_ln60_fu_418_p1;
reg   [63:0] zext_ln60_reg_589;
wire    ap_block_pp0_stage0_grp0;
wire   [6:0] dst_addr_gep_fu_318_p3;
reg   [7:0] n_fu_146;
wire   [7:0] n_2_fu_348_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_n_1;
wire    ap_block_pp0_stage0;
reg    bm_out_7_we0_local;
wire   [3:0] s_tag_fu_383_p4;
reg    bm_out_7_ce0_local;
reg    bm_out_6_we0_local;
reg    bm_out_6_ce0_local;
reg    bm_out_5_we0_local;
reg    bm_out_5_ce0_local;
reg    bm_out_4_we0_local;
reg    bm_out_4_ce0_local;
reg    bm_out_3_we0_local;
reg    bm_out_3_ce0_local;
reg    bm_out_2_we0_local;
reg    bm_out_2_ce0_local;
reg    bm_out_1_we0_local;
reg    bm_out_1_ce0_local;
reg    bm_out_0_we0_local;
reg    bm_out_0_ce0_local;
reg    bm_final_1_we0_local;
reg    bm_final_1_ce0_local;
reg    bm_final_0_we0_local;
reg    bm_final_0_ce0_local;
reg    output_r_we0_local;
wire   [15:0] zext_ln58_fu_403_p1;
reg    output_r_ce0_local;
reg    dst_we0_local;
reg    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
reg    ap_block_pp0_stage0_subdone_grp0;
reg   [23:0] dst_d0_local;
wire   [23:0] x_1_fu_471_p3;
reg    dst_ce0_local;
reg   [6:0] dst_address0_local;
wire   [23:0] x_fu_546_p3;
wire   [7:0] s_addr_i_fu_373_p4;
wire   [12:0] zext_ln54_fu_478_p1;
wire   [12:0] zext_ln54_1_fu_481_p1;
wire   [12:0] s_fu_484_p2;
wire   [11:0] trunc_ln54_fu_496_p1;
wire   [0:0] icmp_ln54_fu_490_p2;
wire   [11:0] add_ln54_fu_500_p2;
wire   [12:0] d_fu_514_p2;
wire   [11:0] trunc_ln58_fu_528_p1;
wire   [0:0] tmp_1_fu_520_p3;
wire   [11:0] add_ln58_fu_532_p2;
wire   [11:0] h_fu_538_p3;
wire   [11:0] l_fu_506_p3;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_210;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 n_fu_146 = 8'd0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
end

mlkem_poly_mul256_v39e_true_one_dsp_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_210)) begin
        if ((icmp_ln56_fu_342_p2 == 1'd0)) begin
            n_fu_146 <= n_2_fu_348_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            n_fu_146 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_aux_reg_583 <= {{rs_dout[23:12]}};
        s_mode_reg_579 <= {{rs_dout[37:36]}};
        s_reduced_reg_570 <= s_reduced_fu_359_p1;
        tmp_reg_562 <= group_r[32'd2];
        zext_ln60_reg_589[7 : 0] <= zext_ln60_fu_418_p1[7 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln56_fu_342_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_n_1 = 8'd0;
    end else begin
        ap_sig_allocacmp_n_1 = n_fu_146;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bm_final_0_ce0_local = 1'b1;
    end else begin
        bm_final_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (s_tag_fu_383_p4 == 4'd8) & (1'b1 == ap_CS_fsm_pp0_stage0) & (s_mode_fu_393_p4 == 2'd1) & (tmp_reg_562 == 1'd1))) begin
        bm_final_0_we0_local = 1'b1;
    end else begin
        bm_final_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bm_final_1_ce0_local = 1'b1;
    end else begin
        bm_final_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (s_tag_fu_383_p4 == 4'd9) & (1'b1 == ap_CS_fsm_pp0_stage0) & (s_mode_fu_393_p4 == 2'd1) & (tmp_reg_562 == 1'd1))) begin
        bm_final_1_we0_local = 1'b1;
    end else begin
        bm_final_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bm_out_0_ce0_local = 1'b1;
    end else begin
        bm_out_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (s_tag_fu_383_p4 == 4'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (s_mode_fu_393_p4 == 2'd1) & (tmp_reg_562 == 1'd0))) begin
        bm_out_0_we0_local = 1'b1;
    end else begin
        bm_out_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bm_out_1_ce0_local = 1'b1;
    end else begin
        bm_out_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (s_tag_fu_383_p4 == 4'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (s_mode_fu_393_p4 == 2'd1) & (tmp_reg_562 == 1'd0))) begin
        bm_out_1_we0_local = 1'b1;
    end else begin
        bm_out_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bm_out_2_ce0_local = 1'b1;
    end else begin
        bm_out_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (s_tag_fu_383_p4 == 4'd2) & (1'b1 == ap_CS_fsm_pp0_stage0) & (s_mode_fu_393_p4 == 2'd1) & (tmp_reg_562 == 1'd0))) begin
        bm_out_2_we0_local = 1'b1;
    end else begin
        bm_out_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bm_out_3_ce0_local = 1'b1;
    end else begin
        bm_out_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (s_tag_fu_383_p4 == 4'd3) & (1'b1 == ap_CS_fsm_pp0_stage0) & (s_mode_fu_393_p4 == 2'd1) & (tmp_reg_562 == 1'd0))) begin
        bm_out_3_we0_local = 1'b1;
    end else begin
        bm_out_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bm_out_4_ce0_local = 1'b1;
    end else begin
        bm_out_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (s_tag_fu_383_p4 == 4'd4) & (1'b1 == ap_CS_fsm_pp0_stage0) & (s_mode_fu_393_p4 == 2'd1) & (tmp_reg_562 == 1'd0))) begin
        bm_out_4_we0_local = 1'b1;
    end else begin
        bm_out_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bm_out_5_ce0_local = 1'b1;
    end else begin
        bm_out_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (s_tag_fu_383_p4 == 4'd5) & (1'b1 == ap_CS_fsm_pp0_stage0) & (s_mode_fu_393_p4 == 2'd1) & (tmp_reg_562 == 1'd0))) begin
        bm_out_5_we0_local = 1'b1;
    end else begin
        bm_out_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bm_out_6_ce0_local = 1'b1;
    end else begin
        bm_out_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (s_tag_fu_383_p4 == 4'd6) & (1'b1 == ap_CS_fsm_pp0_stage0) & (s_mode_fu_393_p4 == 2'd1) & (tmp_reg_562 == 1'd0))) begin
        bm_out_6_we0_local = 1'b1;
    end else begin
        bm_out_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bm_out_7_ce0_local = 1'b1;
    end else begin
        bm_out_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (s_tag_fu_383_p4 == 4'd7) & (1'b1 == ap_CS_fsm_pp0_stage0) & (s_mode_fu_393_p4 == 2'd1) & (tmp_reg_562 == 1'd0))) begin
        bm_out_7_we0_local = 1'b1;
    end else begin
        bm_out_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((s_mode_reg_579 == 2'd0)) begin
            dst_address0_local = dst_addr_gep_fu_318_p3;
        end else if ((s_mode_reg_579 == 2'd2)) begin
            dst_address0_local = zext_ln60_reg_589;
        end else begin
            dst_address0_local = 'bx;
        end
    end else begin
        dst_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (s_mode_reg_579 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (s_mode_reg_579 == 2'd2)))) begin
        dst_ce0_local = 1'b1;
    end else begin
        dst_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((s_mode_reg_579 == 2'd0)) begin
            dst_d0_local = x_fu_546_p3;
        end else if ((s_mode_reg_579 == 2'd2)) begin
            dst_d0_local = x_1_fu_471_p3;
        end else begin
            dst_d0_local = 'bx;
        end
    end else begin
        dst_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (s_mode_reg_579 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (s_mode_reg_579 == 2'd2)))) begin
        dst_we0_local = 1'b1;
    end else begin
        dst_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        output_r_ce0_local = 1'b1;
    end else begin
        output_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (s_mode_fu_393_p4 == 2'd3))) begin
        output_r_we0_local = 1'b1;
    end else begin
        output_r_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rs_blk_n = rs_empty_n;
    end else begin
        rs_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rs_read = 1'b1;
    end else begin
        rs_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln54_fu_500_p2 = (trunc_ln54_fu_496_p1 + 12'd767);

assign add_ln58_fu_532_p2 = ($signed(trunc_ln58_fu_528_p1) + $signed(12'd3329));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((rs_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp0 = ((ap_done_reg == 1'b1) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_done_reg == 1'b1) | ((rs_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((rs_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp0 = ((ap_done_reg == 1'b1) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_condition_210 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bm_final_0_address0 = zext_ln60_fu_418_p1;

assign bm_final_0_ce0 = bm_final_0_ce0_local;

assign bm_final_0_d0 = s_reduced_fu_359_p1;

assign bm_final_0_we0 = bm_final_0_we0_local;

assign bm_final_1_address0 = zext_ln60_fu_418_p1;

assign bm_final_1_ce0 = bm_final_1_ce0_local;

assign bm_final_1_d0 = s_reduced_fu_359_p1;

assign bm_final_1_we0 = bm_final_1_we0_local;

assign bm_out_0_address0 = zext_ln60_fu_418_p1;

assign bm_out_0_ce0 = bm_out_0_ce0_local;

assign bm_out_0_d0 = s_reduced_fu_359_p1;

assign bm_out_0_we0 = bm_out_0_we0_local;

assign bm_out_1_address0 = zext_ln60_fu_418_p1;

assign bm_out_1_ce0 = bm_out_1_ce0_local;

assign bm_out_1_d0 = s_reduced_fu_359_p1;

assign bm_out_1_we0 = bm_out_1_we0_local;

assign bm_out_2_address0 = zext_ln60_fu_418_p1;

assign bm_out_2_ce0 = bm_out_2_ce0_local;

assign bm_out_2_d0 = s_reduced_fu_359_p1;

assign bm_out_2_we0 = bm_out_2_we0_local;

assign bm_out_3_address0 = zext_ln60_fu_418_p1;

assign bm_out_3_ce0 = bm_out_3_ce0_local;

assign bm_out_3_d0 = s_reduced_fu_359_p1;

assign bm_out_3_we0 = bm_out_3_we0_local;

assign bm_out_4_address0 = zext_ln60_fu_418_p1;

assign bm_out_4_ce0 = bm_out_4_ce0_local;

assign bm_out_4_d0 = s_reduced_fu_359_p1;

assign bm_out_4_we0 = bm_out_4_we0_local;

assign bm_out_5_address0 = zext_ln60_fu_418_p1;

assign bm_out_5_ce0 = bm_out_5_ce0_local;

assign bm_out_5_d0 = s_reduced_fu_359_p1;

assign bm_out_5_we0 = bm_out_5_we0_local;

assign bm_out_6_address0 = zext_ln60_fu_418_p1;

assign bm_out_6_ce0 = bm_out_6_ce0_local;

assign bm_out_6_d0 = s_reduced_fu_359_p1;

assign bm_out_6_we0 = bm_out_6_we0_local;

assign bm_out_7_address0 = zext_ln60_fu_418_p1;

assign bm_out_7_ce0 = bm_out_7_ce0_local;

assign bm_out_7_d0 = s_reduced_fu_359_p1;

assign bm_out_7_we0 = bm_out_7_we0_local;

assign d_fu_514_p2 = (zext_ln54_fu_478_p1 - zext_ln54_1_fu_481_p1);

assign dst_addr_gep_fu_318_p3 = zext_ln60_reg_589;

assign dst_address0 = dst_address0_local;

assign dst_ce0 = dst_ce0_local;

assign dst_d0 = dst_d0_local;

assign dst_we0 = dst_we0_local;

assign h_fu_538_p3 = ((tmp_1_fu_520_p3[0:0] == 1'b1) ? add_ln58_fu_532_p2 : trunc_ln58_fu_528_p1);

assign icmp_ln54_fu_490_p2 = ((s_fu_484_p2 > 13'd3328) ? 1'b1 : 1'b0);

assign icmp_ln56_fu_342_p2 = ((ap_sig_allocacmp_n_1 == 8'd128) ? 1'b1 : 1'b0);

assign l_fu_506_p3 = ((icmp_ln54_fu_490_p2[0:0] == 1'b1) ? add_ln54_fu_500_p2 : trunc_ln54_fu_496_p1);

assign n_2_fu_348_p2 = (ap_sig_allocacmp_n_1 + 8'd1);

assign output_r_address0 = zext_ln60_fu_418_p1;

assign output_r_ce0 = output_r_ce0_local;

assign output_r_d0 = zext_ln58_fu_403_p1;

assign output_r_we0 = output_r_we0_local;

assign s_addr_i_fu_373_p4 = {{rs_dout[31:24]}};

assign s_fu_484_p2 = (zext_ln54_fu_478_p1 + zext_ln54_1_fu_481_p1);

assign s_mode_fu_393_p4 = {{rs_dout[37:36]}};

assign s_reduced_fu_359_p1 = rs_dout[11:0];

assign s_tag_fu_383_p4 = {{rs_dout[35:32]}};

assign tmp_1_fu_520_p3 = d_fu_514_p2[32'd12];

assign trunc_ln54_fu_496_p1 = s_fu_484_p2[11:0];

assign trunc_ln58_fu_528_p1 = d_fu_514_p2[11:0];

assign x_1_fu_471_p3 = {{s_reduced_reg_570}, {s_aux_reg_583}};

assign x_fu_546_p3 = {{h_fu_538_p3}, {l_fu_506_p3}};

assign zext_ln54_1_fu_481_p1 = s_reduced_reg_570;

assign zext_ln54_fu_478_p1 = s_aux_reg_583;

assign zext_ln58_fu_403_p1 = s_reduced_fu_359_p1;

assign zext_ln60_fu_418_p1 = s_addr_i_fu_373_p4;

always @ (posedge ap_clk) begin
    zext_ln60_reg_589[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
end

endmodule //mlkem_poly_mul256_v39e_true_one_dsp_write39d
