// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mlkem_poly_mul256_v39e_true_one_dsp_mlkem_poly_mul256_v39e_true_one_dsp_Pipeline_pack39d (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        bm_final_address0,
        bm_final_ce0,
        bm_final_q0,
        bm_1_address0,
        bm_1_ce0,
        bm_1_q0,
        bm_final_1_address0,
        bm_final_1_ce0,
        bm_final_1_q0,
        bm_5_address0,
        bm_5_ce0,
        bm_5_q0,
        ant_address0,
        ant_ce0,
        ant_we0,
        ant_d0,
        ant_address1,
        ant_ce1,
        ant_we1,
        ant_d1,
        bm_2_address0,
        bm_2_ce0,
        bm_2_q0,
        bm_3_address0,
        bm_3_ce0,
        bm_3_q0,
        bm_6_address0,
        bm_6_ce0,
        bm_6_q0,
        bm_7_address0,
        bm_7_ce0,
        bm_7_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] bm_final_address0;
output   bm_final_ce0;
input  [11:0] bm_final_q0;
output  [5:0] bm_1_address0;
output   bm_1_ce0;
input  [11:0] bm_1_q0;
output  [5:0] bm_final_1_address0;
output   bm_final_1_ce0;
input  [11:0] bm_final_1_q0;
output  [5:0] bm_5_address0;
output   bm_5_ce0;
input  [11:0] bm_5_q0;
output  [6:0] ant_address0;
output   ant_ce0;
output   ant_we0;
output  [23:0] ant_d0;
output  [6:0] ant_address1;
output   ant_ce1;
output   ant_we1;
output  [23:0] ant_d1;
output  [5:0] bm_2_address0;
output   bm_2_ce0;
input  [11:0] bm_2_q0;
output  [5:0] bm_3_address0;
output   bm_3_ce0;
input  [11:0] bm_3_q0;
output  [5:0] bm_6_address0;
output   bm_6_ce0;
input  [11:0] bm_6_q0;
output  [5:0] bm_7_address0;
output   bm_7_ce0;
input  [11:0] bm_7_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln127_fu_207_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [6:0] i_2_reg_443;
wire    ap_block_pp0_stage0_11001;
reg   [6:0] i_2_reg_443_pp0_iter1_reg;
wire   [11:0] l_fu_268_p3;
reg   [11:0] l_reg_493;
wire   [11:0] h_fu_308_p3;
reg   [11:0] h_reg_498;
wire   [11:0] l_2_fu_348_p3;
reg   [11:0] l_2_reg_503;
wire   [11:0] h_2_fu_388_p3;
reg   [11:0] h_2_reg_508;
wire   [63:0] zext_ln127_fu_219_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln129_fu_411_p1;
wire   [63:0] zext_ln130_fu_431_p1;
reg   [6:0] i_fu_66;
wire   [6:0] add_ln127_fu_213_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_i_2;
reg    bm_final_ce0_local;
reg    bm_1_ce0_local;
reg    bm_final_1_ce0_local;
reg    bm_5_ce0_local;
reg    bm_2_ce0_local;
reg    bm_3_ce0_local;
reg    bm_6_ce0_local;
reg    bm_7_ce0_local;
reg    ant_we1_local;
wire   [23:0] x_fu_396_p3;
reg    ant_ce1_local;
reg    ant_we0_local;
wire   [23:0] x_2_fu_416_p3;
reg    ant_ce0_local;
wire   [12:0] zext_ln54_2_fu_240_p1;
wire   [12:0] zext_ln54_fu_236_p1;
wire   [12:0] s_fu_250_p2;
wire   [11:0] add_ln54_1_fu_244_p2;
wire   [0:0] icmp_ln54_fu_256_p2;
wire   [11:0] add_ln54_fu_262_p2;
wire   [12:0] zext_ln54_4_fu_280_p1;
wire   [12:0] zext_ln54_3_fu_276_p1;
wire   [12:0] s_1_fu_290_p2;
wire   [11:0] add_ln54_5_fu_284_p2;
wire   [0:0] icmp_ln54_1_fu_296_p2;
wire   [11:0] add_ln54_2_fu_302_p2;
wire   [12:0] zext_ln54_6_fu_320_p1;
wire   [12:0] zext_ln54_5_fu_316_p1;
wire   [12:0] s_2_fu_330_p2;
wire   [11:0] add_ln54_8_fu_324_p2;
wire   [0:0] icmp_ln54_2_fu_336_p2;
wire   [11:0] add_ln54_4_fu_342_p2;
wire   [12:0] zext_ln54_8_fu_360_p1;
wire   [12:0] zext_ln54_7_fu_356_p1;
wire   [12:0] s_3_fu_370_p2;
wire   [11:0] add_ln54_10_fu_364_p2;
wire   [0:0] icmp_ln54_3_fu_376_p2;
wire   [11:0] add_ln54_6_fu_382_p2;
wire   [6:0] shl_ln129_fu_406_p2;
wire   [5:0] trunc_ln129_fu_403_p1;
wire   [6:0] or_ln_fu_423_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 i_fu_66 = 7'd0;
#0 ap_done_reg = 1'b0;
end

mlkem_poly_mul256_v39e_true_one_dsp_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln127_fu_207_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_66 <= add_ln127_fu_213_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_66 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        h_2_reg_508 <= h_2_fu_388_p3;
        h_reg_498 <= h_fu_308_p3;
        i_2_reg_443 <= ap_sig_allocacmp_i_2;
        i_2_reg_443_pp0_iter1_reg <= i_2_reg_443;
        l_2_reg_503 <= l_2_fu_348_p3;
        l_reg_493 <= l_fu_268_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ant_ce0_local = 1'b1;
    end else begin
        ant_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ant_ce1_local = 1'b1;
    end else begin
        ant_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ant_we0_local = 1'b1;
    end else begin
        ant_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ant_we1_local = 1'b1;
    end else begin
        ant_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln127_fu_207_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_2 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_66;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bm_1_ce0_local = 1'b1;
    end else begin
        bm_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bm_2_ce0_local = 1'b1;
    end else begin
        bm_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bm_3_ce0_local = 1'b1;
    end else begin
        bm_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bm_5_ce0_local = 1'b1;
    end else begin
        bm_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bm_6_ce0_local = 1'b1;
    end else begin
        bm_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bm_7_ce0_local = 1'b1;
    end else begin
        bm_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bm_final_1_ce0_local = 1'b1;
    end else begin
        bm_final_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bm_final_ce0_local = 1'b1;
    end else begin
        bm_final_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln127_fu_213_p2 = (ap_sig_allocacmp_i_2 + 7'd1);

assign add_ln54_10_fu_364_p2 = (bm_7_q0 + bm_6_q0);

assign add_ln54_1_fu_244_p2 = (bm_1_q0 + bm_final_q0);

assign add_ln54_2_fu_302_p2 = (add_ln54_5_fu_284_p2 + 12'd767);

assign add_ln54_4_fu_342_p2 = (add_ln54_8_fu_324_p2 + 12'd767);

assign add_ln54_5_fu_284_p2 = (bm_5_q0 + bm_final_1_q0);

assign add_ln54_6_fu_382_p2 = (add_ln54_10_fu_364_p2 + 12'd767);

assign add_ln54_8_fu_324_p2 = (bm_3_q0 + bm_2_q0);

assign add_ln54_fu_262_p2 = (add_ln54_1_fu_244_p2 + 12'd767);

assign ant_address0 = zext_ln130_fu_431_p1;

assign ant_address1 = zext_ln129_fu_411_p1;

assign ant_ce0 = ant_ce0_local;

assign ant_ce1 = ant_ce1_local;

assign ant_d0 = x_2_fu_416_p3;

assign ant_d1 = x_fu_396_p3;

assign ant_we0 = ant_we0_local;

assign ant_we1 = ant_we1_local;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bm_1_address0 = zext_ln127_fu_219_p1;

assign bm_1_ce0 = bm_1_ce0_local;

assign bm_2_address0 = zext_ln127_fu_219_p1;

assign bm_2_ce0 = bm_2_ce0_local;

assign bm_3_address0 = zext_ln127_fu_219_p1;

assign bm_3_ce0 = bm_3_ce0_local;

assign bm_5_address0 = zext_ln127_fu_219_p1;

assign bm_5_ce0 = bm_5_ce0_local;

assign bm_6_address0 = zext_ln127_fu_219_p1;

assign bm_6_ce0 = bm_6_ce0_local;

assign bm_7_address0 = zext_ln127_fu_219_p1;

assign bm_7_ce0 = bm_7_ce0_local;

assign bm_final_1_address0 = zext_ln127_fu_219_p1;

assign bm_final_1_ce0 = bm_final_1_ce0_local;

assign bm_final_address0 = zext_ln127_fu_219_p1;

assign bm_final_ce0 = bm_final_ce0_local;

assign h_2_fu_388_p3 = ((icmp_ln54_3_fu_376_p2[0:0] == 1'b1) ? add_ln54_6_fu_382_p2 : add_ln54_10_fu_364_p2);

assign h_fu_308_p3 = ((icmp_ln54_1_fu_296_p2[0:0] == 1'b1) ? add_ln54_2_fu_302_p2 : add_ln54_5_fu_284_p2);

assign icmp_ln127_fu_207_p2 = ((ap_sig_allocacmp_i_2 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln54_1_fu_296_p2 = ((s_1_fu_290_p2 > 13'd3328) ? 1'b1 : 1'b0);

assign icmp_ln54_2_fu_336_p2 = ((s_2_fu_330_p2 > 13'd3328) ? 1'b1 : 1'b0);

assign icmp_ln54_3_fu_376_p2 = ((s_3_fu_370_p2 > 13'd3328) ? 1'b1 : 1'b0);

assign icmp_ln54_fu_256_p2 = ((s_fu_250_p2 > 13'd3328) ? 1'b1 : 1'b0);

assign l_2_fu_348_p3 = ((icmp_ln54_2_fu_336_p2[0:0] == 1'b1) ? add_ln54_4_fu_342_p2 : add_ln54_8_fu_324_p2);

assign l_fu_268_p3 = ((icmp_ln54_fu_256_p2[0:0] == 1'b1) ? add_ln54_fu_262_p2 : add_ln54_1_fu_244_p2);

assign or_ln_fu_423_p3 = {{trunc_ln129_fu_403_p1}, {1'd1}};

assign s_1_fu_290_p2 = (zext_ln54_4_fu_280_p1 + zext_ln54_3_fu_276_p1);

assign s_2_fu_330_p2 = (zext_ln54_6_fu_320_p1 + zext_ln54_5_fu_316_p1);

assign s_3_fu_370_p2 = (zext_ln54_8_fu_360_p1 + zext_ln54_7_fu_356_p1);

assign s_fu_250_p2 = (zext_ln54_2_fu_240_p1 + zext_ln54_fu_236_p1);

assign shl_ln129_fu_406_p2 = i_2_reg_443_pp0_iter1_reg << 7'd1;

assign trunc_ln129_fu_403_p1 = i_2_reg_443_pp0_iter1_reg[5:0];

assign x_2_fu_416_p3 = {{h_2_reg_508}, {l_2_reg_503}};

assign x_fu_396_p3 = {{h_reg_498}, {l_reg_493}};

assign zext_ln127_fu_219_p1 = ap_sig_allocacmp_i_2;

assign zext_ln129_fu_411_p1 = shl_ln129_fu_406_p2;

assign zext_ln130_fu_431_p1 = or_ln_fu_423_p3;

assign zext_ln54_2_fu_240_p1 = bm_1_q0;

assign zext_ln54_3_fu_276_p1 = bm_final_1_q0;

assign zext_ln54_4_fu_280_p1 = bm_5_q0;

assign zext_ln54_5_fu_316_p1 = bm_2_q0;

assign zext_ln54_6_fu_320_p1 = bm_3_q0;

assign zext_ln54_7_fu_356_p1 = bm_6_q0;

assign zext_ln54_8_fu_360_p1 = bm_7_q0;

assign zext_ln54_fu_236_p1 = bm_final_q0;

endmodule //mlkem_poly_mul256_v39e_true_one_dsp_mlkem_poly_mul256_v39e_true_one_dsp_Pipeline_pack39d
