// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mlkem512_basemul_acc_k2_mlkem512_basemul_acc_k2,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.630000,HLS_SYN_LAT=137,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=599,HLS_SYN_LUT=310,HLS_VERSION=2024_2}" *)

module mlkem512_basemul_acc_k2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a_0_address0,
        a_0_ce0,
        a_0_q0,
        a_0_address1,
        a_0_ce1,
        a_0_q1,
        a_1_address0,
        a_1_ce0,
        a_1_q0,
        a_1_address1,
        a_1_ce1,
        a_1_q1,
        b_0_address0,
        b_0_ce0,
        b_0_q0,
        b_0_address1,
        b_0_ce1,
        b_0_q1,
        b_1_address0,
        b_1_ce0,
        b_1_q0,
        b_1_address1,
        b_1_ce1,
        b_1_q1,
        b_cache_0_address0,
        b_cache_0_ce0,
        b_cache_0_q0,
        b_cache_1_address0,
        b_cache_1_ce0,
        b_cache_1_q0,
        result_address0,
        result_ce0,
        result_we0,
        result_d0,
        result_address1,
        result_ce1,
        result_we1,
        result_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] a_0_address0;
output   a_0_ce0;
input  [15:0] a_0_q0;
output  [7:0] a_0_address1;
output   a_0_ce1;
input  [15:0] a_0_q1;
output  [7:0] a_1_address0;
output   a_1_ce0;
input  [15:0] a_1_q0;
output  [7:0] a_1_address1;
output   a_1_ce1;
input  [15:0] a_1_q1;
output  [7:0] b_0_address0;
output   b_0_ce0;
input  [15:0] b_0_q0;
output  [7:0] b_0_address1;
output   b_0_ce1;
input  [15:0] b_0_q1;
output  [7:0] b_1_address0;
output   b_1_ce0;
input  [15:0] b_1_q0;
output  [7:0] b_1_address1;
output   b_1_ce1;
input  [15:0] b_1_q1;
output  [6:0] b_cache_0_address0;
output   b_cache_0_ce0;
input  [15:0] b_cache_0_q0;
output  [6:0] b_cache_1_address0;
output   b_cache_1_ce0;
input  [15:0] b_cache_1_q0;
output  [7:0] result_address0;
output   result_ce0;
output   result_we0;
output  [15:0] result_d0;
output  [7:0] result_address1;
output   result_ce1;
output   result_we1;
output  [15:0] result_d1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln33_fu_273_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] p_cast_fu_243_p1;
reg   [63:0] p_cast_reg_452;
wire    ap_block_pp0_stage0_11001;
reg   [63:0] p_cast_reg_452_pp0_iter1_reg;
reg   [63:0] p_cast_reg_452_pp0_iter2_reg;
reg   [63:0] p_cast_reg_452_pp0_iter3_reg;
reg   [63:0] p_cast_reg_452_pp0_iter4_reg;
reg   [63:0] p_cast_reg_452_pp0_iter5_reg;
reg   [63:0] p_cast_reg_452_pp0_iter6_reg;
reg   [63:0] p_cast_reg_452_pp0_iter7_reg;
wire   [63:0] zext_ln40_fu_259_p1;
reg   [63:0] zext_ln40_reg_457;
reg   [63:0] zext_ln40_reg_457_pp0_iter1_reg;
reg   [63:0] zext_ln40_reg_457_pp0_iter2_reg;
reg   [63:0] zext_ln40_reg_457_pp0_iter3_reg;
reg   [63:0] zext_ln40_reg_457_pp0_iter4_reg;
reg   [63:0] zext_ln40_reg_457_pp0_iter5_reg;
reg   [63:0] zext_ln40_reg_457_pp0_iter6_reg;
reg   [63:0] zext_ln40_reg_457_pp0_iter7_reg;
reg   [15:0] a_even_reg_516;
reg   [15:0] a_odd_reg_521;
reg   [15:0] b_even_reg_526;
reg  signed [15:0] b_odd_reg_531;
reg  signed [15:0] cached_odd_reg_536;
wire  signed [31:0] sext_ln46_2_fu_284_p1;
wire  signed [31:0] sext_ln47_2_fu_292_p1;
wire  signed [31:0] sext_ln47_3_fu_296_p1;
wire   [31:0] mul_ln47_1_fu_319_p2;
reg  signed [31:0] mul_ln47_1_reg_569;
wire   [31:0] mul_ln47_3_fu_325_p2;
reg  signed [31:0] mul_ln47_3_reg_574;
wire   [31:0] mul_ln49_1_fu_331_p2;
reg  signed [31:0] mul_ln49_1_reg_579;
wire   [31:0] mul_ln49_3_fu_337_p2;
reg  signed [31:0] mul_ln49_3_reg_584;
(* use_dsp48 = "no" *) wire   [31:0] even_fu_343_p2;
reg   [31:0] even_reg_589;
reg   [31:0] even_reg_589_pp0_iter5_reg;
reg  signed [31:0] even_reg_589_pp0_iter6_reg;
(* use_dsp48 = "no" *) wire   [31:0] odd_fu_347_p2;
reg   [31:0] odd_reg_594;
reg   [31:0] odd_reg_594_pp0_iter5_reg;
reg  signed [31:0] odd_reg_594_pp0_iter6_reg;
wire  signed [15:0] low_fu_351_p1;
reg  signed [15:0] low_reg_599;
wire  signed [15:0] low_1_fu_355_p1;
reg  signed [15:0] low_1_reg_604;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln33_fu_229_p1;
reg   [6:0] i1_fu_66;
wire   [6:0] i_fu_267_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_i1_load;
reg    a_0_ce1_local;
reg    a_0_ce0_local;
reg    b_0_ce1_local;
reg    b_0_ce0_local;
reg    b_cache_0_ce0_local;
reg    a_1_ce1_local;
reg    a_1_ce0_local;
reg    b_1_ce1_local;
reg    b_1_ce0_local;
reg    b_cache_1_ce0_local;
reg    result_we1_local;
reg    result_ce1_local;
reg    result_we0_local;
reg    result_ce0_local;
wire   [7:0] tmp_fu_235_p3;
wire   [7:0] tmp_2_fu_251_p3;
wire  signed [15:0] mul_ln47_1_fu_319_p0;
wire  signed [31:0] sext_ln47_1_fu_313_p1;
wire  signed [15:0] mul_ln47_1_fu_319_p1;
wire  signed [31:0] sext_ln47_fu_310_p1;
wire  signed [15:0] mul_ln47_3_fu_325_p1;
wire  signed [31:0] sext_ln46_fu_304_p1;
wire  signed [15:0] mul_ln49_1_fu_331_p0;
wire  signed [15:0] mul_ln49_1_fu_331_p1;
wire  signed [15:0] mul_ln49_3_fu_337_p1;
wire  signed [31:0] grp_fu_405_p3;
wire  signed [31:0] grp_fu_397_p3;
wire  signed [31:0] grp_fu_421_p3;
wire  signed [31:0] grp_fu_413_p3;
wire  signed [12:0] inverse_fu_359_p1;
wire  signed [15:0] inverse_fu_359_p2;
wire  signed [12:0] inverse_1_fu_368_p1;
wire  signed [15:0] inverse_1_fu_368_p2;
wire  signed [31:0] grp_fu_429_p3;
wire  signed [31:0] grp_fu_437_p3;
wire  signed [15:0] grp_fu_397_p0;
wire  signed [15:0] grp_fu_397_p1;
wire  signed [15:0] grp_fu_405_p1;
wire  signed [15:0] grp_fu_413_p0;
wire  signed [15:0] grp_fu_413_p1;
wire  signed [15:0] grp_fu_421_p1;
wire  signed [12:0] grp_fu_429_p1;
wire  signed [12:0] grp_fu_437_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_242;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 i1_fu_66 = 7'd0;
#0 ap_done_reg = 1'b0;
end

mlkem512_basemul_acc_k2_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U1(
    .din0(mul_ln47_1_fu_319_p0),
    .din1(mul_ln47_1_fu_319_p1),
    .dout(mul_ln47_1_fu_319_p2)
);

mlkem512_basemul_acc_k2_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U2(
    .din0(cached_odd_reg_536),
    .din1(mul_ln47_3_fu_325_p1),
    .dout(mul_ln47_3_fu_325_p2)
);

mlkem512_basemul_acc_k2_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U3(
    .din0(mul_ln49_1_fu_331_p0),
    .din1(mul_ln49_1_fu_331_p1),
    .dout(mul_ln49_1_fu_331_p2)
);

mlkem512_basemul_acc_k2_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U4(
    .din0(b_odd_reg_531),
    .din1(mul_ln49_3_fu_337_p1),
    .dout(mul_ln49_3_fu_337_p2)
);

mlkem512_basemul_acc_k2_mul_16s_13s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 16 ))
mul_16s_13s_16_1_1_U5(
    .din0(low_reg_599),
    .din1(inverse_fu_359_p1),
    .dout(inverse_fu_359_p2)
);

mlkem512_basemul_acc_k2_mul_16s_13s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 16 ))
mul_16s_13s_16_1_1_U6(
    .din0(low_1_reg_604),
    .din1(inverse_1_fu_368_p1),
    .dout(inverse_1_fu_368_p2)
);

mlkem512_basemul_acc_k2_mac_muladd_16s_16s_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32s_32_4_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_397_p0),
    .din1(grp_fu_397_p1),
    .din2(mul_ln47_1_reg_569),
    .ce(1'b1),
    .dout(grp_fu_397_p3)
);

mlkem512_basemul_acc_k2_mac_muladd_16s_16s_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32s_32_4_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b_cache_1_q0),
    .din1(grp_fu_405_p1),
    .din2(mul_ln47_3_reg_574),
    .ce(1'b1),
    .dout(grp_fu_405_p3)
);

mlkem512_basemul_acc_k2_mac_muladd_16s_16s_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32s_32_4_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_413_p0),
    .din1(grp_fu_413_p1),
    .din2(mul_ln49_1_reg_579),
    .ce(1'b1),
    .dout(grp_fu_413_p3)
);

mlkem512_basemul_acc_k2_mac_muladd_16s_16s_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32s_32_4_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b_1_q0),
    .din1(grp_fu_421_p1),
    .din2(mul_ln49_3_reg_584),
    .ce(1'b1),
    .dout(grp_fu_421_p3)
);

mlkem512_basemul_acc_k2_mac_muladd_16s_13s_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_13s_32s_32_4_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(inverse_fu_359_p2),
    .din1(grp_fu_429_p1),
    .din2(even_reg_589_pp0_iter6_reg),
    .ce(1'b1),
    .dout(grp_fu_429_p3)
);

mlkem512_basemul_acc_k2_mac_muladd_16s_13s_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_13s_32s_32_4_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(inverse_1_fu_368_p2),
    .din1(grp_fu_437_p1),
    .din2(odd_reg_594_pp0_iter6_reg),
    .ce(1'b1),
    .dout(grp_fu_437_p3)
);

mlkem512_basemul_acc_k2_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_242)) begin
        i1_fu_66 <= i_fu_267_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_even_reg_516 <= a_0_q1;
        a_odd_reg_521 <= a_0_q0;
        b_even_reg_526 <= b_0_q1;
        b_odd_reg_531 <= b_0_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        cached_odd_reg_536 <= b_cache_0_q0;
        p_cast_reg_452[7 : 1] <= p_cast_fu_243_p1[7 : 1];
        p_cast_reg_452_pp0_iter1_reg[7 : 1] <= p_cast_reg_452[7 : 1];
        zext_ln40_reg_457[7 : 1] <= zext_ln40_fu_259_p1[7 : 1];
        zext_ln40_reg_457_pp0_iter1_reg[7 : 1] <= zext_ln40_reg_457[7 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        even_reg_589 <= even_fu_343_p2;
        even_reg_589_pp0_iter5_reg <= even_reg_589;
        even_reg_589_pp0_iter6_reg <= even_reg_589_pp0_iter5_reg;
        low_1_reg_604 <= low_1_fu_355_p1;
        low_reg_599 <= low_fu_351_p1;
        mul_ln47_1_reg_569 <= mul_ln47_1_fu_319_p2;
        mul_ln47_3_reg_574 <= mul_ln47_3_fu_325_p2;
        mul_ln49_1_reg_579 <= mul_ln49_1_fu_331_p2;
        mul_ln49_3_reg_584 <= mul_ln49_3_fu_337_p2;
        odd_reg_594 <= odd_fu_347_p2;
        odd_reg_594_pp0_iter5_reg <= odd_reg_594;
        odd_reg_594_pp0_iter6_reg <= odd_reg_594_pp0_iter5_reg;
        p_cast_reg_452_pp0_iter2_reg[7 : 1] <= p_cast_reg_452_pp0_iter1_reg[7 : 1];
        p_cast_reg_452_pp0_iter3_reg[7 : 1] <= p_cast_reg_452_pp0_iter2_reg[7 : 1];
        p_cast_reg_452_pp0_iter4_reg[7 : 1] <= p_cast_reg_452_pp0_iter3_reg[7 : 1];
        p_cast_reg_452_pp0_iter5_reg[7 : 1] <= p_cast_reg_452_pp0_iter4_reg[7 : 1];
        p_cast_reg_452_pp0_iter6_reg[7 : 1] <= p_cast_reg_452_pp0_iter5_reg[7 : 1];
        p_cast_reg_452_pp0_iter7_reg[7 : 1] <= p_cast_reg_452_pp0_iter6_reg[7 : 1];
        zext_ln40_reg_457_pp0_iter2_reg[7 : 1] <= zext_ln40_reg_457_pp0_iter1_reg[7 : 1];
        zext_ln40_reg_457_pp0_iter3_reg[7 : 1] <= zext_ln40_reg_457_pp0_iter2_reg[7 : 1];
        zext_ln40_reg_457_pp0_iter4_reg[7 : 1] <= zext_ln40_reg_457_pp0_iter3_reg[7 : 1];
        zext_ln40_reg_457_pp0_iter5_reg[7 : 1] <= zext_ln40_reg_457_pp0_iter4_reg[7 : 1];
        zext_ln40_reg_457_pp0_iter6_reg[7 : 1] <= zext_ln40_reg_457_pp0_iter5_reg[7 : 1];
        zext_ln40_reg_457_pp0_iter7_reg[7 : 1] <= zext_ln40_reg_457_pp0_iter6_reg[7 : 1];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_0_ce0_local = 1'b1;
    end else begin
        a_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_0_ce1_local = 1'b1;
    end else begin
        a_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_1_ce0_local = 1'b1;
    end else begin
        a_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_1_ce1_local = 1'b1;
    end else begin
        a_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_273_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i1_load = 7'd0;
    end else begin
        ap_sig_allocacmp_i1_load = i1_fu_66;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_0_ce0_local = 1'b1;
    end else begin
        b_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_0_ce1_local = 1'b1;
    end else begin
        b_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_1_ce0_local = 1'b1;
    end else begin
        b_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_1_ce1_local = 1'b1;
    end else begin
        b_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_cache_0_ce0_local = 1'b1;
    end else begin
        b_cache_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_cache_1_ce0_local = 1'b1;
    end else begin
        b_cache_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        result_ce0_local = 1'b1;
    end else begin
        result_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        result_ce1_local = 1'b1;
    end else begin
        result_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        result_we0_local = 1'b1;
    end else begin
        result_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        result_we1_local = 1'b1;
    end else begin
        result_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_0_address0 = zext_ln40_fu_259_p1;

assign a_0_address1 = p_cast_fu_243_p1;

assign a_0_ce0 = a_0_ce0_local;

assign a_0_ce1 = a_0_ce1_local;

assign a_1_address0 = zext_ln40_fu_259_p1;

assign a_1_address1 = p_cast_fu_243_p1;

assign a_1_ce0 = a_1_ce0_local;

assign a_1_ce1 = a_1_ce1_local;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_242 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign b_0_address0 = zext_ln40_fu_259_p1;

assign b_0_address1 = p_cast_fu_243_p1;

assign b_0_ce0 = b_0_ce0_local;

assign b_0_ce1 = b_0_ce1_local;

assign b_1_address0 = zext_ln40_fu_259_p1;

assign b_1_address1 = p_cast_fu_243_p1;

assign b_1_ce0 = b_1_ce0_local;

assign b_1_ce1 = b_1_ce1_local;

assign b_cache_0_address0 = zext_ln33_fu_229_p1;

assign b_cache_0_ce0 = b_cache_0_ce0_local;

assign b_cache_1_address0 = zext_ln33_fu_229_p1;

assign b_cache_1_ce0 = b_cache_1_ce0_local;

assign even_fu_343_p2 = ($signed(grp_fu_405_p3) + $signed(grp_fu_397_p3));

assign grp_fu_397_p0 = sext_ln47_3_fu_296_p1;

assign grp_fu_397_p1 = sext_ln47_2_fu_292_p1;

assign grp_fu_405_p1 = sext_ln46_2_fu_284_p1;

assign grp_fu_413_p0 = sext_ln47_3_fu_296_p1;

assign grp_fu_413_p1 = sext_ln46_2_fu_284_p1;

assign grp_fu_421_p1 = sext_ln47_2_fu_292_p1;

assign grp_fu_429_p1 = 29'd536867583;

assign grp_fu_437_p1 = 29'd536867583;

assign i_fu_267_p2 = (ap_sig_allocacmp_i1_load + 7'd1);

assign icmp_ln33_fu_273_p2 = ((ap_sig_allocacmp_i1_load == 7'd127) ? 1'b1 : 1'b0);

assign inverse_1_fu_368_p1 = 16'd62209;

assign inverse_fu_359_p1 = 16'd62209;

assign low_1_fu_355_p1 = odd_fu_347_p2[15:0];

assign low_fu_351_p1 = even_fu_343_p2[15:0];

assign mul_ln47_1_fu_319_p0 = sext_ln47_1_fu_313_p1;

assign mul_ln47_1_fu_319_p1 = sext_ln47_fu_310_p1;

assign mul_ln47_3_fu_325_p1 = sext_ln46_fu_304_p1;

assign mul_ln49_1_fu_331_p0 = sext_ln47_1_fu_313_p1;

assign mul_ln49_1_fu_331_p1 = sext_ln46_fu_304_p1;

assign mul_ln49_3_fu_337_p1 = sext_ln47_fu_310_p1;

assign odd_fu_347_p2 = ($signed(grp_fu_421_p3) + $signed(grp_fu_413_p3));

assign p_cast_fu_243_p1 = tmp_fu_235_p3;

assign result_address0 = zext_ln40_reg_457_pp0_iter7_reg;

assign result_address1 = p_cast_reg_452_pp0_iter7_reg;

assign result_ce0 = result_ce0_local;

assign result_ce1 = result_ce1_local;

assign result_d0 = {{grp_fu_437_p3[31:16]}};

assign result_d1 = {{grp_fu_429_p3[31:16]}};

assign result_we0 = result_we0_local;

assign result_we1 = result_we1_local;

assign sext_ln46_2_fu_284_p1 = $signed(a_1_q0);

assign sext_ln46_fu_304_p1 = $signed(a_odd_reg_521);

assign sext_ln47_1_fu_313_p1 = $signed(b_even_reg_526);

assign sext_ln47_2_fu_292_p1 = $signed(a_1_q1);

assign sext_ln47_3_fu_296_p1 = $signed(b_1_q1);

assign sext_ln47_fu_310_p1 = $signed(a_even_reg_516);

assign tmp_2_fu_251_p3 = {{ap_sig_allocacmp_i1_load}, {1'd1}};

assign tmp_fu_235_p3 = {{ap_sig_allocacmp_i1_load}, {1'd0}};

assign zext_ln33_fu_229_p1 = ap_sig_allocacmp_i1_load;

assign zext_ln40_fu_259_p1 = tmp_2_fu_251_p3;

always @ (posedge ap_clk) begin
    p_cast_reg_452[0] <= 1'b0;
    p_cast_reg_452[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    p_cast_reg_452_pp0_iter1_reg[0] <= 1'b0;
    p_cast_reg_452_pp0_iter1_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    p_cast_reg_452_pp0_iter2_reg[0] <= 1'b0;
    p_cast_reg_452_pp0_iter2_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    p_cast_reg_452_pp0_iter3_reg[0] <= 1'b0;
    p_cast_reg_452_pp0_iter3_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    p_cast_reg_452_pp0_iter4_reg[0] <= 1'b0;
    p_cast_reg_452_pp0_iter4_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    p_cast_reg_452_pp0_iter5_reg[0] <= 1'b0;
    p_cast_reg_452_pp0_iter5_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    p_cast_reg_452_pp0_iter6_reg[0] <= 1'b0;
    p_cast_reg_452_pp0_iter6_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    p_cast_reg_452_pp0_iter7_reg[0] <= 1'b0;
    p_cast_reg_452_pp0_iter7_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln40_reg_457[0] <= 1'b1;
    zext_ln40_reg_457[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln40_reg_457_pp0_iter1_reg[0] <= 1'b1;
    zext_ln40_reg_457_pp0_iter1_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln40_reg_457_pp0_iter2_reg[0] <= 1'b1;
    zext_ln40_reg_457_pp0_iter2_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln40_reg_457_pp0_iter3_reg[0] <= 1'b1;
    zext_ln40_reg_457_pp0_iter3_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln40_reg_457_pp0_iter4_reg[0] <= 1'b1;
    zext_ln40_reg_457_pp0_iter4_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln40_reg_457_pp0_iter5_reg[0] <= 1'b1;
    zext_ln40_reg_457_pp0_iter5_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln40_reg_457_pp0_iter6_reg[0] <= 1'b1;
    zext_ln40_reg_457_pp0_iter6_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln40_reg_457_pp0_iter7_reg[0] <= 1'b1;
    zext_ln40_reg_457_pp0_iter7_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
end

endmodule //mlkem512_basemul_acc_k2
